-- ISO 9001 document import (Drive-linked, source_url).
-- Mirrors import-ikea-iway-documents.sql / import-fsc-coc-documents.sql: idempotent, re-runnable.
-- 37 files from Drive folder 'MMDI ISO 9001 - 2025 process' (single flat folder, no
-- subfolders, no exclusions needed -- all files are QMS manuals/procedures/formats).
-- content_text backfilled progressively for AI Copilot grounding, same pattern as prior categories.

insert into public.documents (title, summary, tags, category, file_name, source_url, mime_type, file_size_bytes, content_text, uploaded_at)
values
  ($q$MMDI-SOP -Production$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-SOP -Production.docx$q$, $q$https://drive.google.com/file/d/1ZOvpVa2d2IBp7YzNtjNX_AzdZ11yoJd-/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 46436, $q$MMDI SOP - Production Process (ISO 9001:2015 QMS, Doc No. MMDI-QMS-QSP NO 3, effective 1 April 2024). Purpose: standardized guidelines for large-format printing. Scope: pre-press technicians, printing machine operators, finishing staff, QC personnel. Responsibilities defined for Production Manager, Pre-press Technicians, Printing Machine Operators, Finishing Staff, QC Personnel. Procedure stages: pre-press preparation (file review, print-ready conversion, proofs); pre-printing operations (substrate/fabric verification); printing setup (substrate selection, machine config, nozzle/color calibration); printing process (monitoring, drying, dye-sublimation heat/pressure); finishing operations (trimming, hot-air seaming, eyelets, pocketing, mounting on rigid boards/canvas/aluminium frames); quality control checks; packaging and shipping; maintenance and cleaning; record keeping; continuous improvement; compliance with industry/environmental regulations; emergency procedures; documentation/reporting; periodic SOP review/revision; staff training and development.$q$, now()),
  ($q$MMDI-COMPETENCY MATRIX$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-COMPETENCY MATRIX.docx$q$, $q$https://drive.google.com/file/d/1H1ENviGIzwd2d1hcGIfb8wDEiepuUHm8/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 738613, NULL, now()),
  ($q$MMDI-QMS_QUALITY OBJECTIVES$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_QUALITY OBJECTIVES.docx$q$, $q$https://drive.google.com/file/d/1NITM5zaOGGZiCnaJmtBO6aFRzeiiChQg/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 736295, $q$ISO 9001:2015 QMS Quality Objectives, Doc No. MMDI-QMS-ANNEX 004, effective 1st April 2024, Issue 1 / Version 1.0. Nine objectives with target/responsibility/duration/monitoring: (1) Increase revenue 30% growth YoY, Sales/Marketing, 12 months, monitored by Directors. (2) Achieve 90%+ customer satisfaction, Customer Service, quarterly, Quality Assurance. (3) Maintain 95%+ print quality acceptance rate, Production, monthly, Production Manager. (4) 98%+ on-time delivery rate, Operations, weekly, Operations Manager. (5) Reduce waste/rework 10% annually, Quality Control, Quality Assurance. (6) Enhance employee skills/engagement via biannual surveys and training, HR, HR Manager. (7) Adhere to industry standards/regulations, Compliance, ongoing, Compliance Officer. (8) Continuously improve processes/technology, Process Improvement, quarterly, Operations Manager. (9) Maintain supplier quality/relationships via periodic evaluations, Procurement, semi-annually, Procurement Manager.$q$, now()),
  ($q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Health and Safety$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Health and Safety.docx$q$, $q$https://drive.google.com/file/d/1QU6CfNBZ3k-30X6Hg3eIJXZN4S9CLlxH/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 40814, NULL, now()),
  ($q$MMDI-QMS_FORMAT-Non-confirmity Report$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_FORMAT-Non-confirmity Report.docx$q$, $q$https://drive.google.com/file/d/1mAa1SuJ5CY9Mp2uAftm7Mdp-r2wurAcG/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 38250, NULL, now()),
  ($q$MMDI-QMS_FORMAT-Non-confirmity and Corrective Action Plan$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_FORMAT-Non-confirmity and Corrective Action Plan.docx$q$, $q$https://drive.google.com/file/d/1Fo1saLWIo8x94SnA0LcUYGtaNk8GSX4r/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 42288, NULL, now()),
  ($q$MACRO-SOP-PURCHASE$q$, NULL, '{}', $q$ISO 9001$q$, $q$MACRO-SOP-PURCHASE.docx$q$, $q$https://drive.google.com/file/d/1oPBYxmP47H7ymAhgnR3IjKfX2T3GB_6g/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 743850, $q$MMDI SOP - Purchase Process (ISO 9001:2015 QMS, Doc No. MMDI/QMS/SOP NO.2, effective 1 Sept 2023). Purpose: procedure for purchase of all materials at Macromedia Digital Imaging Pvt Ltd. Covers: outsourcing/supply schedule adherence, rate standardization, comparative statements for quotations, sub-contractor bill checking, bill tracking, quality inspection, supplier base widening. Supplier Master maintenance: approval based on price list, market standing, financial status, OEM/distributor association; periodic performance evaluation and rating (quality, delivery promptness, response, after-sales, commercial terms). Material purchase workflow: BOM/Kitting List receipt, quotation calls, PO release, urgent/cash purchase, rejected material handling. Process parameter standards table: schedule prep within 3 days, new supplier selection within 15 days, PO raising per kitting list, rejection replacement within 2 days, supplier rating done quarterly (target >90 for 80% of suppliers, >70 for 20%), bill passing within 3 days of GRN. Lists quality records maintained (approved supplier list, quotation comparison, PO, purchase control register, GRIR, stock register, etc.) and 4 quality objectives around supplier count, purchase cost reduction, supplier rating improvement, and supply schedule adherence.$q$, now()),
  ($q$Goods Receipt Inspection Report$q$, NULL, '{}', $q$ISO 9001$q$, $q$Goods Receipt Inspection Report.docx$q$, $q$https://drive.google.com/file/d/1PeoFbXC9SmUYgi6hlHMfqb1DNSGh3opX/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 737356, NULL, now()),
  ($q$01 MMDI_QUALITY MANUAL 1 (6)$q$, NULL, '{}', $q$ISO 9001$q$, $q$01 MMDI_QUALITY MANUAL 1 (6).docx$q$, $q$https://drive.google.com/file/d/1hB8eMQt3WooxhkT9sjzWAHIZnBKSlzeM/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 883147, NULL, now()),
  ($q$MMDI-QMS_FORMAT-RISK ASSESSMENT 1$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_FORMAT-RISK ASSESSMENT 1.doc$q$, $q$https://drive.google.com/file/d/1AGR_8i9_moQAWH57jQRtaIN6BTiR_25V/view?usp=drivesdk$q$, $q$application/msword$q$, 777216, NULL, now()),
  ($q$MMDI-Supplier - Vendor Rating$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-Supplier - Vendor Rating.xlsx$q$, $q$https://drive.google.com/file/d/1o3HvoqhemgxKMwvXjodTn5gaL0IGmtaN/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.spreadsheetml.sheet$q$, 11142, NULL, now()),
  ($q$MMDI QMS Format Supplier Rating$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI QMS Format Supplier Rating .xlsx$q$, $q$https://drive.google.com/file/d/1PCNZbaXo_vCIzbbZ7v50hHZ_UV8XeooD/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.spreadsheetml.sheet$q$, 22251, NULL, now()),
  ($q$MMDI-QMS-FORMAT_ANNUAL TRAINING CALENDAR$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS-FORMAT_ANNUAL TRAINING CALENDAR.docx$q$, $q$https://drive.google.com/file/d/1KfKkhyt5b1mCPB4Ip6cs-QH2V02IB1QO/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 40746, NULL, now()),
  ($q$MMDI QMS Format Approved Supplier List$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI QMS Format Approved Supplier List .xlsx$q$, $q$https://drive.google.com/file/d/1hztNfiPzWPW2afieT8Tt8BgtARNypQRs/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.spreadsheetml.sheet$q$, 18312, NULL, now()),
  ($q$MMDI-QMS_FORMAT- Maintenance$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_FORMAT- Maintenance.docx$q$, $q$https://drive.google.com/file/d/1oQYkaW-k75iobgouu2hCiO7x1itr-NHw/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 41774, NULL, now()),
  ($q$MMDI-QMS_FORMAT- Planning for Changes$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_FORMAT- Planning for Changes.docx$q$, $q$https://drive.google.com/file/d/12Zk1muq0F-ndLTUo8fKehTJbFEZpHcrE/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 42125, NULL, now()),
  ($q$Work instructions for machine operators$q$, NULL, '{}', $q$ISO 9001$q$, $q$Work instructions for machine operators.docx$q$, $q$https://drive.google.com/file/d/1ytH80h6x4gWKIf8V9TSP7698aiSX8n_m/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 41492, NULL, now()),
  ($q$MMDI-QMS_FORMAT-Workplace Risk Assessment$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_FORMAT-Workplace Risk Assessment.doc$q$, $q$https://drive.google.com/file/d/1v7eIboa5FMbh773Wg8rkQR0K3NyDEM7L/view?usp=drivesdk$q$, $q$application/msword$q$, 778752, NULL, now()),
  ($q$MMDI-TRAINING FEEDBACK FORMAT$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-TRAINING FEEDBACK FORMAT.docx$q$, $q$https://drive.google.com/file/d/1boZ_cOJHrPNYl01aW8xRzmKJnppzXAr0/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 37394, NULL, now()),
  ($q$MMDI-TRAINING ATTENDANCE SHEET FORMAT$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-TRAINING ATTENDANCE SHEET FORMAT.docx$q$, $q$https://drive.google.com/file/d/1RXsd3etpn0V4ohVPEcK6m2aLEFTbBpzS/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 39492, NULL, now()),
  ($q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Chemical Handling$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Chemical Handling.docx$q$, $q$https://drive.google.com/file/d/1VusKXTH401S8Z13gM5n2SXp0FpRaTcFu/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 40663, NULL, now()),
  ($q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Fire Safety$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Fire Safety.docx$q$, $q$https://drive.google.com/file/d/1o05aTEhAQ5gUXTdji8mKHASWer_4xGw9/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 40119, NULL, now()),
  ($q$MMDI-SOP-Stores Process$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-SOP-Stores Process.docx$q$, $q$https://drive.google.com/file/d/1a38M8BRO_TFmvFlZO1zYWpnVvPOzBfwc/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 39758, NULL, now()),
  ($q$MMDI-QSP3-SALES AND CUSTOMER SUPPORT$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QSP3-SALES AND CUSTOMER SUPPORT.docx$q$, $q$https://drive.google.com/file/d/1WiV6CNfp8Q4eGbtcrdOKr2me5J8-gCyp/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 42090, NULL, now()),
  ($q$MMDI-QSP2-PROCUREMENT$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QSP2-PROCUREMENT.docx$q$, $q$https://drive.google.com/file/d/1rFJu2poWBrBz4oGxAV-P2PJOmpZyuBRQ/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 42501, NULL, now()),
  ($q$MMDI-QSP1-PO AND REVIEW OF CUSTOMER REQUIREMENTS$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QSP1-PO AND REVIEW OF CUSTOMER REQUIREMENTS.docx$q$, $q$https://drive.google.com/file/d/1jU1h6qvkGhMs6kGSRq_MXoaOk7_1e_av/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 737098, $q$MMDI QSP1 - Procedure for Purchase Order and Customer Requirements Review (ISO 9001:2015 QMS, Doc No. MMDI-QMS-QSP NO 1, effective 1 April 2024). Purpose: standard procedure for receipt/review of customer POs. Scope: sales and pre-press teams. Responsibility: Sales Executive, Pre-press Operations Executive. Process steps: order receipt & entry (logged in order management/ERP with full details); document review for completeness/accuracy; customer requirements review (design files, color specs, print size, paper type, finishing) cross-referenced against equipment capability; customer communication for discrepancies; feasibility assessment; quote preparation if scope expands; order confirmation; production planning and resource allocation; quality control during/after production; packaging and shipping per PO delivery terms; documentation and record-keeping of the full order lifecycle; post-delivery customer feedback for continuous improvement.$q$, now()),
  ($q$MMDI-QSP-HR and training process$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QSP-HR and training process.docx$q$, $q$https://drive.google.com/file/d/1sUxrFAk3Lw95_vNzakaHGZh5jMkIAljR/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 736665, $q$MMDI HR & Training Process (ISO 9001:2015 QMS, Doc No. MMDI/QMS/QSP NO.3, effective 1 April 2024). Purpose: guidelines for hiring, appointment, training, rewards/recognition, attendance, and other HR activities, covering all employees including short-term contracts. Responsibility: HR Manager. Recruitment: online postings, CV screening, 3-round interview process (HR -> HR Head -> Director), reference checks, offer letter, background verification, joining formalities, Group Insurance. Induction: 2-day program, joining kit (HR Handbook, Diary, ID Card, SOPs, Brochures, RRA), department-head-led induction, post-induction assessment test, ESI/PF compliance, IT account creation, monthly probation review before confirmation. Attendance: office timings communication, late-coming/absence monitoring, geo-tagged attendance for site employees. Training: annual training plan/calendar prepared by HR with Director approval, competence/skill matrix, training records and feedback maintained. Exit Formalities: 1-month notice period, exit interview, asset/ID collection, NOC from all departments, handover documentation, IT access revocation, final settlement, termination procedures per management instruction.$q$, now()),
  ($q$MMDI-QMS-SWOT ANALYSIS$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS-SWOT ANALYSIS.docx$q$, $q$https://drive.google.com/file/d/1iQ7hUpAEG6w2aNUAWDDgx_hTS4hhNSfS/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 737672, NULL, now()),
  ($q$MMDI-QMS-PESTEL ANALYSIS$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS-PESTEL ANALYSIS.docx$q$, $q$https://drive.google.com/file/d/1gSuMliVZ6KwWJ1nA0ecQYpADndpCFQju/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 740674, NULL, now()),
  ($q$MMDI-QMS- OPPORTUNITIES ASSESSMENT 1$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS- OPPORTUNITIES ASSESSMENT 1.doc$q$, $q$https://drive.google.com/file/d/1XlXW993EwOi6V-Wa_q1SgVzb79HM4KtW/view?usp=drivesdk$q$, $q$application/msword$q$, 763904, NULL, now()),
  ($q$MMDI-QMS_NEEDS & EXPECTATIONS FORMAT$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-QMS_NEEDS & EXPECTATIONS FORMAT.docx$q$, $q$https://drive.google.com/file/d/1SMwMru6CTJhHW8jRTKUrQePjhgFCHBI2/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 736714, NULL, now()),
  ($q$List of Machines$q$, NULL, '{}', $q$ISO 9001$q$, $q$List of Machines.docx$q$, $q$https://drive.google.com/file/d/1yamTrveBy1IgQ9SB48eZNVXFtCzufbtQ/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 737542, NULL, now()),
  ($q$Vision & Mission Statement$q$, NULL, '{}', $q$ISO 9001$q$, $q$Vision & Mission Statement.docx$q$, $q$https://drive.google.com/file/d/1MAkWGMwEyxHdNSxOSOnq55zD9OOjAAEZ/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 38372, NULL, now()),
  ($q$MMDI ISO Trackers for Documents$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI ISO Trackers for Documents.xlsx$q$, $q$https://drive.google.com/file/d/16cTqlYVJnTLuagDczBSf5kB-uA0gbmC2/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.spreadsheetml.sheet$q$, 12194, $q$MMDI ISO Trackers for Documents -- master status index of the ISO 9001:2015 QMS documentation set. 23 tracked documents with status and responsibility (mostly 'Completed', owner Mr. Srinivas-MMDI or VSR): Quality Manual (ready, to be reviewed/approved), Risk Register, Opportunities Register, Needs and Expectations of Interested Parties, SWOT/PESTEL Analysis, Quality Objectives, SOPs for Sales & Customer Support / Production / Stores / Procurement / HR & Training / Nonconformity & Corrective Action / Planning for Changes / Maintenance (all completed) and Internal Audits / Control of Documents / Release of Products & Dispatch (still 'In process'), Work Instructions for Machine Operators, HR Competency Matrix, HR Training Records, List of Machines, List of Approved Suppliers, Supplier/Vendor Rating. Useful as a table of contents / gap-check for the QMS document set -- 3 SOPs (Internal Audits, Control of Documents, Release of Products & Dispatch) are flagged as still in process and were not found among the ingested Drive files.$q$, now()),
  ($q$MMDI-Vendor_Registration form$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-Vendor_Registration form.docx$q$, $q$https://drive.google.com/file/d/13VCuwVbwyRMB5Jhe9lYTlDwUceU9AU4Q/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 90121, NULL, now()),
  ($q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Waste Management$q$, NULL, '{}', $q$ISO 9001$q$, $q$MMDI-TRAINING ATTENDANCE SHEET FORMAT-Waste Management.docx$q$, $q$https://drive.google.com/file/d/1i5X4G8HmG1q64cgK_DfXQXSkFTXjwsPc/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 40668, NULL, now()),
  ($q$01 MMDI_QUALITY MANUAL 1 (5)$q$, NULL, '{}', $q$ISO 9001$q$, $q$01 MMDI_QUALITY MANUAL 1 (5).docx$q$, $q$https://drive.google.com/file/d/1l4ipK2mtJOqj1O-JCAYHNktvzPQcEhiV/view?usp=drivesdk$q$, $q$application/vnd.openxmlformats-officedocument.wordprocessingml.document$q$, 193023, NULL, now())
on conflict (source_url) do update set
  content_text = excluded.content_text,
  file_size_bytes = excluded.file_size_bytes,
  uploaded_at = excluded.uploaded_at;