-- Drawings (category within Documents) import (Drive-linked, source_url).
-- NOTE: this writes to public.documents with category='Drawings' -- per the user's earlier
-- clarification, 'Drawings' is just a category label within the Documents module, NOT a route
-- into the separate public.drawings / Drawings-CAD workspace table.
-- Mirrors import-ikea-iway-documents.sql / import-fsc-coc-documents.sql / import-iso9001-documents.sql
-- / import-statutory-documents.sql: idempotent, re-runnable.
-- 8 files from Drive folder 'Drawings' (flat, no subfolders): electrical single-line
-- diagrams and facility layouts across Mumbai, Noida, Cherlapally/Hyderabad, Bangalore, Chandanvelly.

insert into public.documents (title, summary, tags, category, file_name, source_url, mime_type, file_size_bytes, content_text, uploaded_at)
values
  ($q$Mumbai New Facility V6$q$, NULL, '{}', $q$Drawings$q$, $q$Mumbai New Facility V6.pdf$q$, $q$https://drive.google.com/file/d/1DQNKRaNWSS36tj-EwsI-iWwL50DDzpdF/view?usp=drivesdk$q$, $q$application/pdf$q$, 4322161, $q$Mumbai New Facility layout drawing (CDR-sourced, dated Jan'26), V6. Shows floor plan with compass orientation (N/W/E), a 10x2 panel power area (7KW, 'Challenger' branded), store, and toilets. Primarily a graphical floor-plan; limited machine-extractable text beyond these labels.$q$, now()),
  ($q$MMDI Mumbai Electrical SLD$q$, NULL, '{}', $q$Drawings$q$, $q$MMDI Mumbai Electrical SLD.pdf$q$, $q$https://drive.google.com/file/d/1fKKDRE-T3ESU0fnKFh8-gsFexZfhHl6D/view?usp=drivesdk$q$, $q$application/pdf$q$, 7626579, $q$MMDI Mumbai Electrical Single Line Diagram (SLD). Legend: ELR (Earth Leakage Relay), MFM (Multi Function Meter), TC (Temperature Controller), BZ (Buzzer), APFC (Automatic Power Factor Controller), DCA/DCV (DC Ampere/Volt Meter), CT (Current Transformer), CBCT (Core Balance CT), built-in fire extinguisher system. Circuit detail: EB incomer 11000/435V via 320A 50KA 4P MCCB with thermal magnetic O/C,S/C releases and ELR/CBCT protection; bus bar rated 400A,415V,50Hz,TP+N,ALU (50kA for 1 sec); multiple TPN MCCBs (160A/100A/63A) with microprocessor O/C,S/C releases feeding Compressor Panel, AC Panel, LDB, PDB, 40KVA UPS input, and spare feeders; APFC bank with capacitor duty contactors at 25/15/10/5 KVAR stages, 7% aluminium detuned reactors at 440V.$q$, now()),
  ($q$MMDI Noida Sector140 SLD V2$q$, NULL, '{}', $q$Drawings$q$, $q$MMDI Noida Sector140 SLD V2.pdf$q$, $q$https://drive.google.com/file/d/1z2fAlxDAXJZUfT5UxtcMnDiX_CDZnPdd/view?usp=drivesdk$q$, $q$application/pdf$q$, 4943060, $q$MMDI Noida Sector 140 Electrical Single Line Diagram (SLD), V2. Shows DG set 160KVA with 320A 50KA 4P MCCB (thermal magnetic), auto-start gen-set feature, hooter on grid power on/off; EB incomer 11000/435V via 400A 50KA 4P MCCB with O/C,S/C releases, emergency stop push button, voltage monitoring relay, built-in fire extinguisher system; CT for APFC (0.2 class, 300/5, thermal magnetic O/C,S/C); bus bar 400A,415V,50Hz,TP+N,ALU (50kA/1sec); in-built/external APFC with 7% aluminium detuned reactors at 440V, capacitor banks in steps: 5KVAC x2, 10KVAC x1, 15KVAC x2, 25KVAC x3.$q$, now()),
  ($q$MMDI Noida Sector 140 Plan v4$q$, NULL, '{}', $q$Drawings$q$, $q$MMDI Noida Sector 140 Plan v4.pdf$q$, $q$https://drive.google.com/file/d/1acRau7ioX244AP5W7tXv6PVwZh4LTWV-/view?usp=drivesdk$q$, $q$application/pdf$q$, 1418182, $q$MMDI Noida Sector 140 floor plan, V4. Shows machine/equipment layout with power ratings and dimensions: Plotter 10x10 (0.4KW), GS 3250 LX Pro (8KW), Vutek UV Printer (10KW), CNC Router 27x20 (20KW), Sheet Bending 14x14 (5.6KW), Sheet Cutting 13x14 (5.6KW), Profile Bending 25x10 (5KW), Laser Welding 10x12 (3.75KW), Laser 10x16 (4KW); areas labeled: Store (27x20, x2), Seaming Area (52x30), Pasting Table (12x4), Fabrication & Assembly Area, Dispatch Area, PDB, LDB, with compass orientation N/S/E/W.$q$, now()),
  ($q$MMDI Cherlapally _Power Room Floor Drawing$q$, NULL, '{}', $q$Drawings$q$, $q$MMDI Cherlapally _Power Room Floor Drawing.pdf$q$, $q$https://drive.google.com/file/d/1FMDjId5r7wi1z3G5Ha2uYyI-82PI8ew7/view?usp=drivesdk$q$, $q$application/pdf$q$, 14130, $q$MMDI Cherlapally Power Room floor drawing. Shows equipment layout and dimensions: Old Capacitor Panel, Old Changeover Panel, Gen Panel, Main PCC Panel, VCB Panel (existing placement 5400x1000x1875mm / 17.75x3.3x6.2ft), APFC Panel (1250x600x1800mm / 4x2x6ft), VCB Panel (1920x600x2000mm / 6.2x2x6.5ft).$q$, now()),
  ($q$Hyderabad Electrical Drawing V2$q$, NULL, '{}', $q$Drawings$q$, $q$Hyderabad Electrical Drawing V2.pdf$q$, $q$https://drive.google.com/file/d/1kfrrMDMHuBQrTSjIOi-FQ9lEiGL1e8Br/view?usp=drivesdk$q$, $q$application/pdf$q$, 1613071, $q$Hyderabad (Cherlapally) Single Line Electrical Drawing, V2, for Macromedia Digital Imaging Pvt. Ltd., 23B & 24, Phase 5, IDA-Cherlapally, Hyderabad-500051. Main Power Panel with 125KVA/160KVA transformers, 320A/250A 4P breakers, 630A 4P 36KA main breaker. Distribution across Ground Floor, Mezzanine Floor, First Floor, and Second Floor: separate Raw Power DBs and UPS Power DBs/VTPNs per floor, additional DBs near emergency exit, staircase, finishing room, and open store. Second Floor Power Panel also shown.$q$, now()),
  ($q$MMDI Bangalore Chemsandra Plant2 Layout v2$q$, NULL, '{}', $q$Drawings$q$, $q$MMDI Bangalore Chemsandra Plant2 Layout v2.pdf$q$, $q$https://drive.google.com/file/d/1W6F-IEA-vr5c_4cQFxzikrEZf8xdmKTr/view?usp=drivesdk$q$, $q$application/pdf$q$, 1490456, NULL, now()),
  ($q$MMDI Chnadanvelly-ELECTRICAL V8$q$, NULL, '{}', $q$Drawings$q$, $q$MMDI Chnadanvelly-ELECTRICAL V8.pdf$q$, $q$https://drive.google.com/file/d/1foiXYRTgknjR_nsFhV_bS4FxCd2P98Xp/view?usp=drivesdk$q$, $q$application/pdf$q$, 5027005, $q$MMDI Chandanvelly Electrical layout, V8. Shows transformer yard (10500x5000mm) with 630KVA transformer, VCB, CT/PT, concrete depth 300mm/700mm walls, board/material entry points on north side. Detailed shop-floor electrical distribution across Wood Working (WW DB1-5), Metal Working (MW DB1-6/VTPN DB3-6), LT Panel Room (7000x400), overhead crane, hot press/pressing DB5, stores (pipe/sheet section, board cutting), solid wood machines, welding section, carpentry, lathes, grinding section, powder coating, wood finishing areas -- with individual machine tags (M01-M24, W01-W19, E12-E50, R01-R09) and power ratings (e.g. M05 45KW/60KVA, W06 28KW/37.3KVA, W19 23KW/30KVA, W16 25KW/33KVA, M23 13KW/17.3KVA). Includes 400KVA generator, goods lift, emergency staircase (6600x3680mm), dust collector, toilets.$q$, now())
on conflict (source_url) do update set
  content_text = excluded.content_text,
  file_size_bytes = excluded.file_size_bytes,
  uploaded_at = excluded.uploaded_at;