-- Statutory Documents import (Drive-linked, source_url).
-- Mirrors import-ikea-iway-documents.sql / import-fsc-coc-documents.sql / import-iso9001-documents.sql:
-- idempotent, re-runnable.
-- 18 files from Drive folder 'Dun and Bradstreet IKEA Due Diligence' (root-level files only).
-- Excludes 2 subfolders: '5 & 13. PF ESI & employees data' (employee-level HR data) and
-- '6. GSTR-3B & GSTR-1 Returns Jan-25 to Jan-26' (bulk monthly transaction-level tax filings) --
-- same exclusion pattern as HR/Invoices in prior categories.
-- content_text backfilled progressively for AI Copilot grounding, same pattern as prior categories.

insert into public.documents (title, summary, tags, category, file_name, source_url, mime_type, file_size_bytes, content_text, uploaded_at)
values
  ($q$19. Management declaration letter$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$19. Management declaration letter.pdf$q$, $q$https://drive.google.com/file/d/1bUW5vnlL0tPj2ZyyAWP03fHJFA3--l7F/view?usp=drivesdk$q$, $q$application/pdf$q$, 111383, $q$Management Declaration Letter to Dun & Bradstreet Information Services India Pvt. Ltd. (Mumbai), dated 12-03-2026, part of the IKEA due diligence submission. Declares that neither the signatory nor any of their firms have defaulted on any statutory dues or been involved in any legal case, past or present. Signed by Ramakrishna P Musunuri, Wholetime Director, Macro Media Digital Imaging Pvt. Ltd. (CIN U01119AP1999PTC032909).$q$, now()),
  ($q$15,16,17. List Top 10 Cust & Suppl & Top 5 Contracts$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$15,16,17. List Top 10 Cust & Suppl & Top 5 Contracts.pdf$q$, $q$https://drive.google.com/file/d/1Jo_pE2R4DtKvBtx1DsASwpagW-n7a-d6/view?usp=drivesdk$q$, $q$application/pdf$q$, 170562, $q$Declaration letter to Dun & Bradstreet Information Services India Pvt. Ltd. (Mumbai), dated 12-03-2025, re: Non-Disclosure of Top 10 Customers & Suppliers and reference contacts. States MMDI has NDAs with several customers/suppliers and is therefore unable to disclose their identities or contact details for the due-diligence submission. Signed by Ramakrishna P Musunuri, Wholetime Director.$q$, now()),
  ($q$11. Bankers Confidentiality Report$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$11. Bankers Confidentiality Report.pdf$q$, $q$https://drive.google.com/file/d/1cTESzxHHy4IEwyAwIu7rrEibByFLxFu4/view?usp=drivesdk$q$, $q$application/pdf$q$, 509367, NULL, now()),
  ($q$12.1 Group Mediclaim Policy MMDI Sep26$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$12.1 Group Mediclaim Policy MMDI Sep26.pdf$q$, $q$https://drive.google.com/file/d/1GZxmjMDwlndQVatqXRgjPMO1CgJzI4t3/view?usp=drivesdk$q$, $q$application/pdf$q$, 206934, NULL, now()),
  ($q$20. Directors KYC$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$20. Directors KYC.pdf$q$, $q$https://drive.google.com/file/d/1bRwtlz7AHH-oSI_hfFb2xLWglTz75qwg/view?usp=drivesdk$q$, $q$application/pdf$q$, 343831, NULL, now()),
  ($q$1. Detailed Profile of the Company$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$1. Detailed Profile of the Company.pdf$q$, $q$https://drive.google.com/file/d/1NLneRAZ0iC5avTGkgRUV7fKadC3Rkoo-/view?usp=drivesdk$q$, $q$application/pdf$q$, 6908715, NULL, now()),
  ($q$18. Latest shareholding pattern FY24-25$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$18. Latest shareholding pattern FY24-25.pdf$q$, $q$https://drive.google.com/file/d/1Bpi-LABCwU78u2I5subBj6Cg6V8eUVFU/view?usp=drivesdk$q$, $q$application/pdf$q$, 185237, $q$Latest Shareholding Pattern / List of Members as on 31 March 2025, Macro Media Digital Imaging Private Limited (CIN U01119AP1999PTC032909). Certified by Dasari Naresh Kumar, Managing Director (DIN 01778737). 10 equity shareholders (Rs.10 face value each): Jasti Srinivasa Karunendra 9,01,500 shares; Musunuri Ramakrishna Prasad 18,01,500; Dasari Naresh Kumar 25,51,500; Nimmagadda Dharma Rao 5,10,300; Pinnamaneni Lenin 12,75,000; Musunuri Sirisha 7,50,000; Jasti Padmaja Rani 3,75,000; Nimmagadda Srikanth 10,20,600; Paruluri Sridevi 10,20,600. Total equity shares: 1,02,06,000.$q$, now()),
  ($q$7,8,9,10... - Reports of Auditors, Directors, ITR & Financial  2024-25$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$7,8,9,10... - Reports of Auditors, Directors, ITR & Financial  2024-25.pdf$q$, $q$https://drive.google.com/file/d/1mtwWZ8o0hiUq6copLubGk7wulVWSdoHZ/view?usp=drivesdk$q$, $q$application/pdf$q$, 13846403, NULL, now()),
  ($q$12. Insurance Policy Hyderabad$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$12. Insurance Policy Hyderabad.pdf$q$, $q$https://drive.google.com/file/d/16ea-LNG5jHYFiU8kW9ysZ019T7HHyE_8/view?usp=drivesdk$q$, $q$application/pdf$q$, 53812, $q$Standard Fire & Special Perils Policy, The New India Assurance Co. Ltd., for Macromedia Digital Imaging Pvt Ltd, Plot No.23B & 24, Phase-5, IDA Cherlapally, Hyderabad-500051. Policy No. 62110111250100000003, period 30/09/2025 to 29/09/2026. Total Sum Insured Rs.60,68,53,000 covering Building Superstructure (Rs.10 Cr), Plant/Machinery/Accessories (Rs.39.08 Cr), Furniture/Fittings/Fixtures (Rs.5.36 Cr), Stocks (Rs.6 Cr), Compound Wall (Rs.25 lakh). Add-on covers: Earthquake (Fire and Shock), Terrorism. Total premium including GST: Rs.11,52,899. Hypothecated to HDFC Bank Ltd, Secunderabad. PAN AABCM9451F, GSTIN 36AABCM9451F1ZF.$q$, now()),
  ($q$MSMED Certificate FY 25-26.$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$MSMED Certificate FY 25-26..pdf$q$, $q$https://drive.google.com/file/d/1NTKbapEmGHDyUQMk7i-QybEmgzu-WYVY/view?usp=drivesdk$q$, $q$application/pdf$q$, 375032, $q$Udyam (MSME) Registration Certificate. Udyam Registration Number: UDYAM-AP-10-0000987. Enterprise: Macro Media Digital Imaging Private Limited. Enterprise type classification by year: 2025-26 Small, 2024-25 Medium, 2023-24 Medium, 2022-23 Medium. Major activity: Manufacturing. Social category: General. Address: Plot No.44, Apparel Export Park, Autonagar, Visakhapatnam, Andhra Pradesh 530012. Date of incorporation 25/11/1999, commencement of business 23/12/2000. Lists ~17 NIC activity codes spanning fabricated metal products, plastics products, furniture manufacture, machinery repair/installation, architecture/engineering services, interior design/graphic design services, and printing (18115 - printing directly onto textiles, flexographic plastic, glass, metal, wood, ceramics). Date of Udyam registration: 31/08/2020.$q$, now()),
  ($q$4. GST RC Hyderabad$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$4. GST RC Hyderabad.pdf$q$, $q$https://drive.google.com/file/d/1QDxRxLaehLe8xKuv4DY59wwkaQ89Bk-J/view?usp=drivesdk$q$, $q$application/pdf$q$, 296516, $q$GST Registration Certificate (Form GST REG-06) for GSTIN 37AABCM9451F1ZD. Legal/Trade Name: Macro Media Digital Imaging Private Limited. Constitution: Private Limited Company. Principal place of business: 44, Apparel Export Park, Auto Nagar, Visakhapatnam, Andhra Pradesh 530012. Date of liability 01/07/2017, registration type Regular, valid from 01/07/2017 (no end date). Certificate issued 21/09/2017. One additional place of business: Survey No 49, CA4, CFC Area, Autonagar, Mangalagiri, Guntur, Andhra Pradesh 522503.$q$, now()),
  ($q$ISO 9001 - 2015 QMS new$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$ISO 9001 - 2015 QMS new.pdf$q$, $q$https://drive.google.com/file/d/1c7VSGkCgmbGXltuuODoFqQ-81im_bOBx/view?usp=drivesdk$q$, $q$application/pdf$q$, 242877, NULL, now()),
  ($q$7,8,9,10.. - Reports of Auditors, Directors, ITR & Financial  2023-24$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$7,8,9,10.. - Reports of Auditors, Directors, ITR & Financial  2023-24.pdf$q$, $q$https://drive.google.com/file/d/1PFoCMQnGxZFG__hpTLyX0LwywNbROloA/view?usp=drivesdk$q$, $q$application/pdf$q$, 10452482, NULL, now()),
  ($q$7,8,9,10. - Reports of Auditors, Directors, ITR & Financial  2022-23$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$7,8,9,10. - Reports of Auditors, Directors, ITR & Financial  2022-23.pdf$q$, $q$https://drive.google.com/file/d/1Rkem21UJVAXZByy1udynfGkXSiXBF-Pd/view?usp=drivesdk$q$, $q$application/pdf$q$, 10428467, NULL, now()),
  ($q$MoA & AoA 02 03 2018_MMDI$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$MoA & AoA 02 03 2018_MMDI.pdf$q$, $q$https://drive.google.com/file/d/146g8KrxoPuUfXP7m63PkW6jdWq0OhBZY/view?usp=drivesdk$q$, $q$application/pdf$q$, 562568, $q$Certificate of Incorporation, Memorandum of Association (MoA) and Articles of Association (AoA) of Macro Media Digital Imaging Private Limited. Incorporated 25 November 1999 at Hyderabad under the Companies Act 1956, Registration No. 32909 of 1999-2000, signed by Asst. Registrar of Companies K. Padmanabhan. MoA: registered office in Andhra Pradesh; main objects cover media digital printing for advertising, advertising agency services (media space/time buying), and manufacture/purchase/sale/import/export of equipment for the advertising business; extensive list of ancillary objects (R&D, technical consultancy, partnerships/JVs, property acquisition, borrowing, employee welfare funds, etc.). Authorized share capital: Rs.15,00,00,000 divided into 1,50,00,000 equity shares of Rs.10 each. Original subscribers (1999): Jasti Sreekrishna Murthy, Musunuri Ramakrishna Prasad, Dasari Naresh Kumar (100 shares each), witnessed by Pavuluri Achuta Ramaiah (Chartered Accountant); total 300 shares. AoA: private company under Companies Act 2013 Section 2(68), member cap 200, share transfer restrictions, min paid-up capital Rs.1,00,000; covers share capital/calls/lien/transfer provisions, general meetings (21-day notice, quorum 2 members), board composition (2-15 directors, first directors J.S.Krishna Murthy/M.Rama Krishna Prasad/D.Naresh Kumar, non-rotational), Managing Director/additional/alternate/nominee/special director provisions, board powers (borrowing, guarantees, director removal), accounts/audit/inspection/indemnity/secrecy clauses.$q$, now()),
  ($q$2. CIN Certificate$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$2. CIN Certificate.pdf$q$, $q$https://drive.google.com/file/d/18EfFgaq0FUuvKUPYT8MuzjYlnIwFVVph/view?usp=drivesdk$q$, $q$application/pdf$q$, 522067, $q$Certificate of Registration of Special Resolution (Section 13(1), Companies Act 2013), issued by Registrar of Companies, Hyderabad, Ministry of Corporate Affairs. Confirms shareholders of Macro Media Digital Imaging Private Limited passed a Special Resolution (AGM/EGM held 28-02-2018) altering the Memorandum of Association's object clause(s). Corporate Identity Number: U01119AP1999PTC032909. Registered 05-04-2018. Signed by Ramesh Chandra Mishra, RoC-Hyderabad. Registered mailing address: Plot No.44, Apparel Export Park, Autonagar, Gajuwaka, Visakhapatnam, Andhra Pradesh 530012.$q$, now()),
  ($q$3. PAN Card$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$3. PAN Card.pdf$q$, $q$https://drive.google.com/file/d/1Pvkk29wpmg7AouC4vV_onyVvYTknr4wh/view?usp=drivesdk$q$, $q$application/pdf$q$, 38304, $q$PAN Card, Income Tax Department, Govt. of India. Holder: Macro Media Digital Imaging Private Limited. PAN: AABCM9451F. Date of incorporation/registration on card: 25/11/1999.$q$, now()),
  ($q$4.1 GST RC Vizag ( Regd. Office)$q$, NULL, '{"Dun & Bradstreet IKEA Due Diligence"}', $q$Statutory Documents$q$, $q$4.1 GST RC Vizag ( Regd. Office).pdf$q$, $q$https://drive.google.com/file/d/1IF5CUDmvL7qSQoPEpY3zIibaWGMB__Is/view?usp=drivesdk$q$, $q$application/pdf$q$, 45276, $q$GST Registration Certificate (Form GST REG-06), Amended, for GSTIN 36AABCM9451F1ZF (Telangana). Legal/Trade Name: Macro Media Digital Imaging Private Limited. Constitution: Private Limited Company. Principal place: Plot No.23B & 24, Phase V, IDA Cherlapally, Medchal-Malkajgiri, Telangana 500051. Date of liability 01/07/2017, Regular registration, certificate issue date 06/10/2023 (amended/reissued). One additional place of business at Chandanvelly, Survey No 190, Rangareddy, Telangana 501503 (Welspun Flooring Ltd Plant).$q$, now())
on conflict (source_url) do update set
  content_text = excluded.content_text,
  file_size_bytes = excluded.file_size_bytes,
  uploaded_at = excluded.uploaded_at;