-- Real IWAY internal audit / training / license-renewal schedule, sourced
-- from 'G1_2 Internal IWAY Audit Checklist.xlsx' (uploaded 17 Jul 2026).
-- Replaces whatever placeholder rows are currently in compliance_findings.
-- Run supabase-compliance-schedule-migration.sql FIRST (adds the columns
-- this insert needs), then run this file.

delete from public.compliance_findings;

insert into public.compliance_findings
  (item, area, status, status_label, category, chapter, frequency, baseline_date, due_date, responsible)
values
  ('IWAY Organisation Chart', 'PERFORMANCE MANAGEMENT', 'neutral', 'Systemic', 'Compliance Document', 'G1.1', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Internal IWAY audit Record', 'PERFORMANCE MANAGEMENT', 'info', 'Due 09 Nov 2026', 'Internal Audit', 'G1.2', 'Annual', '2022-11-09', '2026-11-09', 'Asst. Manager / Manager - HR'),
  ('Written policies and routines covering IWAY are in place.', 'PERFORMANCE MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G1.3', null, null, null, 'AGM - Operations'),
  ('Indicators and plans are in place to measure and improve performance related to IWAY.', 'PERFORMANCE MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G1.4', null, null, null, 'AGM - Operations'),
  ('Supply Value Chain Report', 'SUPPLY CHAIN MANAGEMENT', 'info', 'Due 01 Mar 2027', 'Compliance Document', 'G1.5', 'Annual', '2024-03-01', '2027-03-01', 'AGM - Operations'),
  ('Security Services Agreement', 'SUPPLY CHAIN MANAGEMENT', 'neutral', 'Systemic', 'Compliance Document', 'G1.6', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Sub Suppliers Audit records', 'SUPPLY CHAIN MANAGEMENT', 'neutral', 'Systemic', 'Compliance Document', 'G1.6', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Social and environmental risks in the IKEA value chain are identified and actions are taken to mitigate them.', 'SUPPLY CHAIN MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G1.7', null, null, null, 'AGM - Operations'),
  ('IWAY Training Record', 'WORKER/MANAGEMENT DIALOGUE', 'neutral', 'No fixed schedule', 'Training', 'G1.8', null, null, null, 'Manager - Operations'),
  ('There is a structured dialogue with workers related to IWAY.', 'WORKER/MANAGEMENT DIALOGUE', 'neutral', 'No fixed schedule', 'Compliance Document', 'G1.9', null, null, null, 'Manager - Operations'),
  ('Business Ethics Policy', 'BUSINESS ETHICS', 'info', 'Due 31 Dec 2026', 'Compliance Document', 'G2.1', 'Annual', '2021-12-31', '2026-12-31', 'Asst. Manager / Manager - HR'),
  ('Standing orders', 'BUSINESS ETHICS', 'neutral', 'Systemic', 'Compliance Document', 'G2.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Approved plans', 'BUSINESS ETHICS', 'neutral', 'Systemic', 'Compliance Document', 'G2.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Stability Certificate', 'BUSINESS ETHICS', 'neutral', 'Systemic', 'License/Certificate', 'G2.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Labour Certificate', 'BUSINESS ETHICS', 'neutral', 'Systemic', 'License/Certificate', 'G2.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Electrical Permission and Inspectarate certificate', 'BUSINESS ETHICS', 'info', 'Due 30 Sep 2026', 'License/Certificate', 'G2.2', 'Annual', '2022-09-30', '2026-09-30', 'Asst. Manager / Manager - HR'),
  ('Employee DOB Records', 'PROTECTION OF CHILDREN', 'neutral', 'Permanent', 'Compliance Document', 'G3.1', 'Permanent', null, null, 'Asst. Manager / Manager - HR'),
  ('Employee DOB Records', 'PROTECTION OF CHILDREN', 'neutral', 'Systemic', 'Compliance Document', 'G3.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Young Workers Policy', 'PROTECTION OF CHILDREN', 'neutral', 'No fixed schedule', 'Compliance Document', 'G3.3', null, null, null, 'Manager - Operations'),
  ('Young Workers Working Areas', 'OPPORTUNITIES FOR WORK AND LEARNING', 'neutral', 'Systemic', 'Compliance Document', 'G3.4', 'Systemic', null, null, 'Manager - Operations'),
  ('Vocational training opportunities for children are identified and promoted.', 'OPPORTUNITIES FOR WORK AND LEARNING', 'neutral', 'Systemic', 'Training', 'G3.5', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Workers receive childcare support in addition to that defined by applicable legislation.', 'OPPORTUNITIES FOR FAMILY LIFE', 'neutral', 'No fixed schedule', 'Compliance Document', 'G3.6', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Service Rules Hand Book', 'WORKER FREEDOM', 'neutral', 'Systemic', 'Compliance Document', 'G4.1', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Minimum Wages act followed', 'WORKER FREEDOM', 'neutral', 'Annual -- baseline date needed', 'Compliance Document', 'G4.2', 'Annual', null, null, 'Asst. Manager / Manager - HR'),
  ('Hours of work', 'WORKER FREEDOM', 'neutral', 'As and when required', 'Compliance Document', 'G4.2', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Leave Policy', 'WORKER FREEDOM', 'neutral', 'Systemic', 'Compliance Document', 'G4.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Breaks', 'WORKER FREEDOM', 'neutral', 'Systemic', 'Compliance Document', 'G4.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('List of Holidays', 'WORKER FREEDOM', 'neutral', 'Systemic', 'Compliance Document', 'G4.2', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('In-Out Register', 'WORKER FREEDOM', 'neutral', 'As and when required', 'Compliance Document', 'G4.2', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Pay Slip', 'WORKER FREEDOM', 'neutral', 'As and when required', 'Compliance Document', 'G4.2', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Bank Statement', 'WORKER FREEDOM', 'neutral', 'As and when required', 'Compliance Document', 'G4.2', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Staff Advances Details', 'WORKER FREEDOM', 'neutral', 'As and when required', 'Compliance Document', 'G4.2', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Feedom of Association', 'FREEDOM OF ASSOCIATION AND GRIEVANCES', 'neutral', 'Quarterly -- baseline date needed', 'Compliance Document', 'G4.3', 'Quarterly', null, null, 'Asst. Manager / Manager - HR'),
  ('Anti-sexual Committee', 'FREEDOM OF ASSOCIATION AND GRIEVANCES', 'warning', 'Due 01 Sep 2026', 'Compliance Document', 'G4.3', 'Quarterly', '2022-03-01', '2026-09-01', 'Asst. Manager / Manager - HR'),
  ('Health & Safety Committee', 'FREEDOM OF ASSOCIATION AND GRIEVANCES', 'warning', 'Due 01 Aug 2026', 'Compliance Document', 'G4.3', 'Quarterly', '2022-02-01', '2026-08-01', 'Asst. Manager / Manager - HR'),
  ('Grievances Committee', 'FREEDOM OF ASSOCIATION AND GRIEVANCES', 'neutral', 'Quarterly -- baseline date needed', 'Compliance Document', 'G4.4', 'Quarterly', null, null, 'Asst. Manager / Manager - HR'),
  ('Service Rules Hand Book', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.5', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Recruitement policy', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.6', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Appointment Letters', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Permanent', 'Compliance Document', 'G4.7', 'Permanent', null, null, 'Asst. Manager / Manager - HR'),
  ('Zero-hours contracts are not used.', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.8', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Discrimination policy', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.9', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Anti-harassment Policy', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.9', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Business Ethics Policy', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.9', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Disciplinary Measures', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.9', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Alohol and drugs Policy', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'Systemic', 'Compliance Document', 'G4.9', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Disciplinary measures do not include the use of mental or physical coercion, including corporal punishment, threats of violence, public warnings or punishments, fines and the removal of contractual be', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'No fixed schedule', 'Compliance Document', 'G4.10', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Temporary work is only used, when work is not of a regular nature.', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'No fixed schedule', 'Compliance Document', 'G4.11', null, null, null, 'Asst. Manager / Manager - HR'),
  ('In case of dismissal, workers are offered a notice period of at least 10 working days prior to termination of employment.', 'RECRUITMENT AND EMPLOYMENT PRACTICES', 'neutral', 'No fixed schedule', 'Compliance Document', 'G4.12', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Workers are free from discrimination, violence or harassment, whether physical or psychological.', 'EQUALITY, DIVERSITY AND INCLUSION', 'neutral', 'No fixed schedule', 'Compliance Document', 'G4.13', null, null, null, 'Manager - Operations'),
  ('Actions to promote equality, diversity and inclusion are implemented and communicated internally.', 'EQUALITY, DIVERSITY AND INCLUSION', 'neutral', 'No fixed schedule', 'Compliance Document', 'G4.14', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Gender pay gaps are assessed and actions are taken to eliminate them.', 'EQUALITY, DIVERSITY AND INCLUSION', 'neutral', 'No fixed schedule', 'Compliance Document', 'G4.15', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Gender balance is achieved for managerial positions.', 'EQUALITY, DIVERSITY AND INCLUSION', 'neutral', 'No fixed schedule', 'Compliance Document', 'G4.16', null, null, null, 'Asst. Manager / Manager - HR'),
  ('In and Out Register', 'WORKING HOURS AND TIME OFF WORK', 'neutral', 'As and when required', 'Compliance Document', 'G5.1', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('In and Out Register', 'WORKING HOURS AND TIME OFF WORK', 'neutral', 'Weekly -- baseline date needed', 'Compliance Document', 'G5.2', 'Weekly', null, null, 'Asst. Manager / Manager - HR'),
  ('Lunch and tea break timings', 'WORKING HOURS AND TIME OFF WORK', 'neutral', 'Systemic', 'Compliance Document', 'G5.3', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('In and Out Register', 'WORKING HOURS AND TIME OFF WORK', 'neutral', 'Weekly -- baseline date needed', 'Compliance Document', 'G5.4', 'Weekly', null, null, 'Asst. Manager / Manager - HR'),
  ('Workers have the opportunity to take time off from work for exceptional personal circumstances, in addition to that defined by applicable legislation.', 'WORKING HOURS AND TIME OFF WORK', 'neutral', 'No fixed schedule', 'Compliance Document', 'G5.5', null, null, null, 'Asst. Manager / Manager - HR'),
  ('In and Out Register', 'WORKING HOURS AND TIME OFF WORK', 'neutral', 'No fixed schedule', 'Compliance Document', 'G5.6', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Work is planned in such a way that it does not rely on overtime.', 'WORKING HOURS AND TIME OFF WORK', 'neutral', 'No fixed schedule', 'Compliance Document', 'G5.7', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Wages Report', 'WAGES AND BENEFITS', 'info', 'Due 29 Apr 2027', 'Compliance Document', 'G5.8', 'Annual', '2023-04-29', '2027-04-29', 'Asst. Manager / Manager - HR'),
  ('Minimum Wages Act', 'WAGES AND BENEFITS', 'info', 'Due 29 Apr 2027', 'Compliance Document', 'G5.8', 'Annual', '2023-04-29', '2027-04-29', 'Asst. Manager / Manager - HR'),
  ('Employee outstation allowances policy', 'WAGES AND BENEFITS', 'neutral', 'Systemic', 'Compliance Document', 'G5.9', 'Systemic', null, null, 'Asst. Manager / Manager - HR'),
  ('Bank Statement', 'WAGES AND BENEFITS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G5.10', null, null, null, 'Asst. Manager / Manager - HR'),
  ('Pay Slips', 'WAGES AND BENEFITS', 'neutral', 'As and when required', 'Compliance Document', 'G5.11', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Uniforms, when required, are provided in sufficient quantity and free of charge. No deductions are made for cleaning and/or maintaining uniforms.', 'WAGES AND BENEFITS', 'neutral', 'Annual -- baseline date needed', 'Compliance Document', 'G5.12', 'Annual', null, null, 'Manager - Operations'),
  ('Overtime hours are compensated at premium rate or through the equivalent amount of time off.', 'WAGES AND BENEFITS', 'neutral', 'As and when required', 'Compliance Document', 'G5.13', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Emergency Action Plan', 'COMPETENCE DEVELOPMENT', 'neutral', 'Systemic', 'Compliance Document', 'G5.14', 'Systemic', null, null, 'AGM - Operations'),
  ('Operator training records', 'COMPETENCE DEVELOPMENT', 'neutral', 'Systemic', 'Training', 'G5.15', 'Systemic', null, null, 'AGM - Operations'),
  ('Color Management Training Records', 'COMPETENCE DEVELOPMENT', 'neutral', 'Systemic', 'Training', 'G5.15', 'Systemic', null, null, 'AGM - Operations'),
  ('Pre-press Training records', 'COMPETENCE DEVELOPMENT', 'neutral', 'Systemic', 'Training', 'G5.15', 'Systemic', null, null, 'AGM - Operations'),
  ('QC training record', 'COMPETENCE DEVELOPMENT', 'neutral', 'Systemic', 'Training', 'G5.15', 'Systemic', null, null, 'AGM - Operations'),
  ('Environmental Complaince Training record', 'COMPETENCE DEVELOPMENT', 'neutral', 'Systemic', 'Training', 'G5.15', 'Systemic', null, null, 'AGM - Operations'),
  ('Vocational trainees above 18 years of age receive compensation for work performed while training. Training is related to their education.', 'COMPETENCE DEVELOPMENT', 'neutral', 'No fixed schedule', 'Training', 'G5.16', null, null, null, 'AGM - Operations'),
  ('Vocational training opportunities are identified and promoted.', 'COMPETENCE DEVELOPMENT', 'neutral', 'No fixed schedule', 'Training', 'G5.17', null, null, null, 'AGM - Operations'),
  ('Workers have the opportunity to develop their competence, in areas related', 'COMPETENCE DEVELOPMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G5.18', null, null, null, 'AGM - Operations'),
  ('Work Place Risk Assessment Report', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.1', null, null, null, 'Asst. Manager / Manager - Production'),
  ('Incident and Accident Report', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.1', null, null, null, 'Asst. Manager / Manager - Production'),
  ('Near Miss Report', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.1', null, null, null, 'Asst. Manager / Manager - Production'),
  ('ESIC Records', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'As and when required', 'Compliance Document', 'G6.2', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('3rd Party Health Insurance', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'As and when required', 'Compliance Document', 'G6.2', 'As and when required', null, null, 'Asst. Manager / Manager - HR'),
  ('Workplace Risk Assessment Report', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'info', 'Due 19 Nov 2026', 'Compliance Document', 'G6.3', 'Half Yearly', '2021-11-19', '2026-11-19', 'AGM - Operations'),
  ('Occupational health and safety training Record', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'Half Yearly -- baseline date needed', 'Training', 'G6.3', 'Half Yearly', null, null, 'AGM - Operations'),
  ('Machinery operating training certificates', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'Permanent', 'Training', 'G6.4', 'Permanent', null, null, 'AGM - Operations'),
  ('Machinery Installation certificates', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'Permanent', 'License/Certificate', 'G6.5', 'Permanent', null, null, 'AGM - Operations'),
  ('Pressure Vessel test Reports.', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'Permanent', 'Compliance Document', 'G6.5', 'Permanent', null, null, 'AGM - Operations'),
  ('PPE Distribution Records', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'As and when required', 'Compliance Document', 'G6.6', 'As and when required', null, null, 'Manager - Operations'),
  ('Accident / Incident Record', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'As and when required', 'Compliance Document', 'G6.7', 'As and when required', null, null, 'Manager - Operations'),
  ('Near Miss Reports', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'As and when required', 'Compliance Document', 'G6.7', 'As and when required', null, null, 'Manager - Operations'),
  ('Accident / Incident Record', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'warning', 'Due 14 Sep 2026', 'Compliance Document', 'G6.8', 'Half Yearly', '2022-03-14', '2026-09-14', 'Manager - Operations'),
  ('Near Miss Reports', 'OCCUPATIONAL HEALTH AND SAFETY MANAGEMENT', 'neutral', 'Half Yearly -- baseline date needed', 'Compliance Document', 'G6.8', 'Half Yearly', null, null, 'Manager - Operations'),
  ('Emergency Action Plan Doc.', 'EMERGENCY MANAGEMENT', 'neutral', 'Systemic', 'Compliance Document', 'G6.9', 'Systemic', null, null, 'AGM - Operations'),
  ('Fire Alarm', 'EMERGENCY MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.10', null, null, null, 'Manager - Operations'),
  ('Emergency Route Maps and Signs', 'EMERGENCY MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.11', null, null, null, 'Manager - Operations'),
  ('FIRST AID Training Records', 'EMERGENCY MANAGEMENT', 'info', 'Due 12 Apr 2027', 'Training', 'G6.12', 'every 3 years', '2021-04-12', '2027-04-12', 'Manager - Operations'),
  ('FIRST AID Kits and Fire Fighting equipment record', 'EMERGENCY MANAGEMENT', 'neutral', 'As and when required', 'Compliance Document', 'G6.13', 'As and when required', null, null, 'Manager - Operations'),
  ('Evacuation Drill report', 'EMERGENCY MANAGEMENT', 'info', 'Due 15 Nov 2026', 'Compliance Document', 'G6.14', 'Half Yearly', '2022-05-15', '2026-11-15', 'Manager - Operations'),
  ('Emergency drills are performed to test the emergency routines and identify any need for improvement. Records of the emergency drills are kept.', 'EMERGENCY MANAGEMENT', 'warning', 'Due 01 Aug 2026', 'Compliance Document', 'G6.15', 'Yearly', '2023-08-01', '2026-08-01', 'AGM - Operations'),
  ('An emergency response team is appointed to take decisions in case of an emergency situation.', 'EMERGENCY MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.16', null, null, null, 'AGM - Operations'),
  ('The written emergency routines are aligned with neighbouring companies and local authorities.', 'EMERGENCY MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.17', null, null, null, 'AGM - Operations'),
  ('Chemical Management System', 'CHEMICAL MANAGEMENT', 'neutral', 'Systemic', 'Compliance Document', 'G6.18', 'Systemic', null, null, 'Manager - Operations'),
  ('Chemical Handling & Storage Training Record', 'CHEMICAL MANAGEMENT', 'neutral', 'Systemic', 'Training', 'G6.18', 'Systemic', null, null, 'Manager - Operations'),
  ('Chemical risks are assessed as per the UN Global Harmonising System and chemicals are labelled accordingly.', 'CHEMICAL MANAGEMENT', 'neutral', 'Systemic', 'Compliance Document', 'G6.19', 'Systemic', null, null, 'AGM - Operations'),
  ('Alternative chemicals with lower risks to the health and safety of workers and the environment are identified and used.', 'CHEMICAL MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.20', null, null, null, 'AGM - Operations'),
  ('Structure Stability Certificate', 'CHEMICAL MANAGEMENT', 'neutral', 'No fixed schedule', 'License/Certificate', 'G6.21', null, null, null, 'AGM - Operations'),
  ('Electrical wiring, lighting and gas fixtures are properly installed and maintained.', 'CHEMICAL MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.22', null, null, null, 'Manager - Operations'),
  ('Non-work related health testing, such as for pregnancy or HIV, is not used.', 'OCCUPATIONAL HEALTH CHECKS AND HEALTHCARE SUPPORT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.23', null, null, null, 'Manager - Operations'),
  ('Occupational health checks are offered regularly to workers to identify impacts on health resulting from work. Health checks are performed by a healthcare professional. Findings are kept confidential ', 'OCCUPATIONAL HEALTH CHECKS AND HEALTHCARE SUPPORT', 'neutral', 'Annual -- baseline date needed', 'Compliance Document', 'G6.24', 'Annual', null, null, 'AGM - Operations'),
  ('Workers receive healthcare support, in addition to that defined by applicable legislation.', 'OCCUPATIONAL HEALTH CHECKS AND HEALTHCARE SUPPORT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G6.25', null, null, null, 'AGM - Operations'),
  ('The working environment is clean, hygienic and well maintained and has adequate light, ventilation and, when necessary, heating.', 'WORKING CONDITIONS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G7.1', null, null, null, 'Manager - Operations'),
  ('Places where workers can eat and rest are available, are away from any hazards and are proportional to the number of workers.', 'WORKING CONDITIONS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G7.2', null, null, null, 'Manager - Operations'),
  ('Toilets are free of charge, hygienic, accessible during working hours, equipped with basic supplies and proportional to the number of workers.', 'WORKING CONDITIONS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G7.3', null, null, null, 'Manager - Operations'),
  ('Water Test Report', 'WORKING CONDITIONS', 'neutral', 'Quarterly -- baseline date needed', 'Compliance Document', 'G7.4', 'Quarterly', null, null, 'Manager - Operations'),
  ('There is no severe environmental pollution. Any case of severe environmental pollution is immediately reported to IKEA.', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.1', null, null, null, 'AGM - Operations'),
  ('Ambient Air Quality Test Report', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.2', null, null, null, 'AGM - Operations'),
  ('Noise Test', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.2', null, null, null, 'AGM - Operations'),
  ('Waste Disposal Area', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.2', null, null, null, 'AGM - Operations'),
  ('Chemical Disposal Storage Area', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.2', null, null, null, 'AGM - Operations'),
  ('Free from ground contamination', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.3', null, null, null, 'Manager - Operations'),
  ('Environmental risks and impacts are identified and assessed in order to find ways to improve environmental performance. Environmental improvement plans are implemented, reviewed and updated every 12 m', 'ENVIRONMENTAL IMPACTS', 'neutral', 'Annual -- baseline date needed', 'Compliance Document', 'G8.4', 'Annual', null, null, 'AGM - Operations'),
  ('Environmental impacts are assessed when evaluating operational and structural changes.', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.5', null, null, null, 'AGM - Operations'),
  ('Net Meterig Agreement', 'ENVIRONMENTAL IMPACTS', 'neutral', 'Systemic', 'Compliance Document', 'G8.6', 'Systemic', null, null, 'AGM - Operations'),
  ('All consumed electricity, generated or purchased, comes from renewable energy sources.', 'ENVIRONMENTAL IMPACTS', 'neutral', 'Annual -- baseline date needed', 'Compliance Document', 'G8.7', 'Annual', null, null, 'AGM - Operations'),
  ('No ozone depleting substances or hydrofluorocarbons are used.', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.8', null, null, null, 'AGM - Operations'),
  ('No fossil coal- or oil-based fuels are used on site as a primary source of', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.9', null, null, null, 'AGM - Operations'),
  ('Emissions of air pollutants and greenhouse gases are reduced in absolute terms, in line with limiting the global temperature increase to well below 2°C, aiming towards 1.5°C, by the end of the century', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.10', null, null, null, 'AGM - Operations'),
  ('All consumed energy, generated or purchased, comes from renewable energy sources.', 'ENVIRONMENTAL IMPACTS', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.11', null, null, null, 'AGM - Operations'),
  ('Business activities are not conducted in High Conservation Value Areas, unless the area is certified according to a system recognised by IKEA.', 'CONSERVATION AND BIODIVERSITY', 'neutral', 'No fixed schedule', 'License/Certificate', 'G8.12', null, null, null, 'AGM - Operations'),
  ('Initiatives to support biodiversity are implemented.', 'CONSERVATION AND BIODIVERSITY', 'neutral', 'No fixed schedule', 'Compliance Document', 'G8.13', null, null, null, 'AGM - Operations'),
  ('Information is available on what type of incoming water is used and how,', 'WATER', 'neutral', 'No fixed schedule', 'Compliance Document', 'G9.1', null, null, null, 'AGM - Operations'),
  ('If water is used in operations, opportunities to reduce use and discharge of', 'WATER', 'neutral', 'No fixed schedule', 'Compliance Document', 'G9.2', null, null, null, 'AGM - Operations'),
  ('If water is used in operations, possibilities to limit the use of high quality water are identified. Actions are taken to limit the usage of high quality water, resulting in improvements.', 'WATER', 'neutral', 'No fixed schedule', 'Compliance Document', 'G9.3', null, null, null, 'AGM - Operations'),
  ('PCB Consent', 'WASTE MANAGEMENT', 'neutral', 'Systemic', 'License/Certificate', 'G9.4', 'Systemic', null, null, 'Manager - Operations'),
  ('RE Enviro Engg. Agreement', 'WASTE MANAGEMENT', 'info', 'Due 06 Oct 2027', 'Compliance Document', 'G9.4', '3 Years', '2024-10-06', '2027-10-06', 'Manager - Operations'),
  ('Form 4', 'WASTE MANAGEMENT', 'info', 'Due 01 Dec 2026', 'Compliance Document', 'G9.4', '5 Years', '2021-12-01', '2026-12-01', 'Manager - Operations'),
  ('Form 5', 'WASTE MANAGEMENT', 'info', 'Due 01 Apr 2027', 'Compliance Document', 'G9.4', 'Annual', '2022-04-01', '2027-04-01', 'Manager - Operations'),
  ('Waste is not incinerated on site, unless for the purpose of recovering energy.', 'WASTE MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G9.5', null, null, null, 'Manager - Operations'),
  ('RE Enviro Engg. Waste Manifest Records', 'WASTE MANAGEMENT', 'warning', 'Due 01 Aug 2026', 'Compliance Document', 'G9.6', 'Half Yearly', '2022-02-01', '2026-08-01', 'Manager - Operations'),
  ('Non-Hazardous Watse Material Collection Report by Recycling Agents', 'WASTE MANAGEMENT', 'neutral', 'As and when required', 'Compliance Document', 'G9.7', 'As and when required', null, null, 'Manager - Operations'),
  ('No waste is sent to landfill.', 'WASTE MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G9.8', null, null, null, 'AGM - Operations'),
  ('All waste is reused or recycled.', 'WASTE MANAGEMENT', 'neutral', 'No fixed schedule', 'Compliance Document', 'G9.9', null, null, null, 'AGM - Operations');
