-- MMDI ONE -- Cost Sheet module seed data
-- Generated from FG Codes BOM Specs.xlsx + the Jan-Jun 2026 purchase register,
-- both provided by the user in this session (see the accompanying Excel
-- workbook, "FG Cost Sheet - Macro Media Digital Imaging.xlsx", built from the
-- same source data with the same assumptions -- this is that workbook's logic
-- ported into MMDI ONE's own schema instead of a spreadsheet).
--
-- Run supabase-cost-sheet-schema.sql BEFORE this file.
-- Idempotent: all INSERTs use ON CONFLICT DO NOTHING, safe to re-run.

-- Auto-generated from FG Codes BOM Specs.xlsx -- 33 BOM templates
insert into public.bom_templates (code, description, category, print_mode, substrate_type, work_centres)
values
  ('SLSD-Flex', 'Digital Solvent Frontlit Flex -  340 GSM ', 'Solvent Print Signage', 'Frontlit Print', 'Flex', ARRAY['WC1A Solvent Printing','WC7 Seaming','WC9 QC','WC12 Packing Section']::text[]),
  ('SLSD-Vinyl', 'Digital Solvent Frontlit Vinyl -  LG LD 1810 ', 'Solvent Print Signage', 'Frontlit Print', 'Vinyl', ARRAY['WC1A Solvent Printing','WC6A Manual Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('SLDD-Flex', 'Digital Solvent Backlit Flex -  MegaRich ', 'Solvent Print Signage', 'Backlit Print', 'Flex', ARRAY['WC1A Solvent Printing','WC6A Manual Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('SLSD-Fabric', 'Digital Solvent Frontlit Fabric -  POLY FAB ULTRA SATIN ', 'Solvent Print Signage (Fabric)', 'Frontlit Print', 'Fabric', ARRAY['WC1A Solvent Printing','WC7 Seaming','WC9 QC','WC12 Packing Section']::text[]),
  ('SLDD-Fabric', 'Digital Solvent Backlit Fabric -  POLY FAB BL-250 ', 'Solvent Print Signage (Fabric)', 'Backlit Print', 'Fabric', ARRAY['WC1A Solvent Printing','WC6A Manual Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVSD-Flex', 'Digital UV Frontlit Flex -  340 GSM', 'UV Print Signage', 'Frontlit Print', 'Flex', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVSD-Vinyl', 'Digital UV Frontlit Vinyl -  LG LD 1810 ', 'UV Print Signage', 'Frontlit Print', 'Vinyl', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVDD-Flex', 'Digital UV Backlit Flex -  MegaRich ', 'UV Print Signage', 'Backlit Print', 'Flex', ARRAY['WC1B UV Printing','WC6A Manual Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVDD-Vinyl', 'Digital UV Backlit Vinyl -  LG LD 4910 ', 'UV Print Signage', 'Backlit Print', 'Vinyl', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVDD-Fabric', 'Digital UV Backlit Fabric -  Soyang 610UT', 'UV Print Signage (Fabric)', 'Backlit Print', 'Fabric', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('LASD-Flex', 'Digital Latex Frontlit Flex -  340 GSM', 'Latex Print Signage', 'Frontlit Print', 'Flex', ARRAY['WC1C Latex Printing','WC6A Manual Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('LASD-Vinyl', 'Digital Latex Frontlit Vinyl -  LG LD 1810', 'Latex Print Signage', 'Frontlit Print', 'Vinyl', ARRAY['WC1C Latex Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('LADD-Flex', 'Digital Latex Backlit Flex -  Megarich', 'Latex Print Signage', 'Backlit Print', 'Flex', ARRAY['WC1C Latex Printing','WC6A Manual Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('LADD-Vinyl', 'Digital Latex Backlit Vinyl -  LG LD 4910', 'Latex Print Signage', 'Backlit Print', 'Vinyl', ARRAY['WC1C Latex Printing','WC6A Manual Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('DYSD-Fabric', 'Digital Dye Sublimation Fronlit Fabric -  Soyang 117D', 'Dye Sublimation Fabric Signage', 'Frontlit Print', 'Fabric', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('DYDD-Fabric', 'Digital Dye Sublimation Backlit Fabric -  Soyang 100D', 'Dye Sublimation Fabric Signage', 'Backlit Print', 'Fabric', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('DYCUR-Fabric', 'Digital Dye Sublimation Curtain Fabric -  Demoot', 'Dye Sublimation Fabric Signage (Curtain)', 'Direct Print', 'Fabric', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('ALSEGSD-Sign', 'SEG Fabric Frontlit Sign -  23MM Profile', 'SEG / Aluminium Frame Signage', 'Frontlit Print', 'Fabric', ARRAY['WC2 Aluminium Cut','WC9 QC','WC12 Packing Section']::text[]),
  ('AlSEGDD-Sign', 'SEG Fabric Backlit Sign -  63MM Profile', 'SEG / Aluminium Frame Signage', 'Backlit Print', 'Fabric', ARRAY['WC2 Aluminium Cut','WC9 QC','WC10 LED Section','WC11 Assembling','WC12 Packing Section']::text[]),
  ('ALSEGDD2S-Sign', 'SEG Fabric Backlit Double Side Sign -  100MM DS Profile', 'SEG / Aluminium Frame Signage (Double Side)', 'Double Side Print', 'Fabric', ARRAY['WC2 Aluminium Cut','WC9 QC','WC10 LED Section','WC11 Assembling','WC12 Packing Section']::text[]),
  ('ALOASDD-SIGN', 'Outdoor Fabric Backlit Sign -  100MM DS Profile', 'Outdoor Aluminium Frame Signage', 'Backlit Print', 'Fabric', ARRAY['WC2 Aluminium Cut','WC9 QC','WC10 LED Section','WC11 Assembling','WC12 Packing Section']::text[]),
  ('PFL-XLFalg', 'Promotional Flag DS - Xtra Large -  DS Blockout Polyester Fabric', 'Flags & Banners', 'Flag Print', 'Other', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('PFL-L Flag', 'Promotional Flag DS - Large -  DS Blockout Polyester Fabric', 'Flags & Banners', 'Flag Print', 'Other', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('PFL-M Flag', 'Promotional Flag DS - MEDIUM -  DS Blockout Polyester Fabric', 'Flags & Banners', 'Flag Print', 'Other', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('DFL-K Flag', 'Desktop Flag - Knife shape -  Polyester Flag Fabric', 'Flags & Banners (Desktop)', 'Flag Print', 'Other', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('DFL-H Flag', 'Desktop Flag - Heart shape -  Polyester Flag Fabric', 'Flags & Banners (Desktop)', 'Flag Print', 'Other', ARRAY['WC1D Dye Sub Printing','WC3 Dye Sub Transfer','WC6B Digital Cut Centre','WC8 Sewing','WC9 QC','WC12 Packing Section']::text[]),
  ('UVSD-R-COR Board', 'Digital UV  Paper Corrugated Board -  5ply', 'Rigid Board Signage (UV Print)', 'Rigid/Direct Print', 'Rigid Board', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVSD-R-FOA Board', 'Digital UV  Foam Board -  3MM Foam Board', 'Rigid Board Signage (UV Print)', 'Rigid/Direct Print', 'Rigid Board', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVSD-R-PP Board', 'Digital UV  PolyPropylene Board -  2MM Polypropylene Board', 'Rigid Board Signage (UV Print)', 'Rigid/Direct Print', 'Rigid Board', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('UVSD-R-PAC Board', 'Digital UV  Paper Card Board -  2MM Eco Pro Board', 'Rigid Board Signage (UV Print)', 'Rigid/Direct Print', 'Rigid Board', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[]),
  ('ALSLIM-LED Sign', 'Slim LED Sign -  LGP Slim Profile', 'LED Signage', 'N/A (No Print)', 'Aluminium/Profile', ARRAY['WC2 Aluminium Cut','WC9 QC','WC10 LED Section','WC11 Assembling','WC12 Packing Section']::text[]),
  ('WINBLD-Profile', 'Window Blinds Profile -  Window Blind Profile', 'Window Blinds', 'N/A (No Print)', 'Aluminium/Profile', ARRAY['WC2 Aluminium Cut','WC9 QC','WC11 Assembling','WC12 Packing Section']::text[]),
  ('UVSD - Paper', 'Digital UV Paper -  Magno Satin Paper', 'UV Print - Paper', 'Rigid/Direct Print', 'Paper', ARRAY['WC1B UV Printing','WC6B Digital Cut Centre','WC9 QC','WC12 Packing Section']::text[])
on conflict (code) do nothing;

-- BOM template lines -- 139 material lines across the 33 templates
-- raw_material_code is left NULL where the BOM shorthand name has no confident
-- match in raw_materials (see suggested_codes) -- map via the Cost Sheet UI.
insert into public.bom_template_lines
  (template_id, line_no, material_name, material_category, basis, consumption_qty, wastage_pct, suggested_codes)
select t.id, x.line_no, x.material_name, x.material_category, x.basis, x.consumption_qty, x.wastage_pct, x.suggested_codes
from (values
  ('SLSD-Flex', 1, 'RSD Flex 340GSM', 'Substrate', 'per_sqft', 1, 0.1, 'RM-11008 FRONTLIT BLACKOUT FLEX 340GSM | RM-11039 ULTRA BLACKOUT FLEX 340 GSM | RM-11029 340 GSM SRF BLACK OUT FLEX HOT LAM'),
  ('SLSD-Flex', 2, 'Solvent Ink Sericol', 'Ink', 'per_sqft', 0, 0, 'RM-17028 SERICOL KSM INKS | RM-17008 SERICOL MSF TRICHROMATIC INKS | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC)'),
  ('SLSD-Flex', 3, 'Solvent Ink Type 2', 'Ink', 'per_sqft', 0, 0, 'RM-41064 EFI WIDE FORMAT SOLVENT FLUSH | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC) (verify)'),
  ('SLSD-Vinyl', 1, 'RSD Vinyl LG LD 1810', 'Substrate', 'per_sqft', 1, 0.1, 'RM-13123 LG 1810 GREY SAV (verify colour/finish)'),
  ('SLSD-Vinyl', 2, 'Solvent Ink Sericol', 'Ink', 'per_sqft', 0, 0, 'RM-17028 SERICOL KSM INKS | RM-17008 SERICOL MSF TRICHROMATIC INKS | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC)'),
  ('SLSD-Vinyl', 3, 'Solvent Ink Type 2', 'Ink', 'per_sqft', 0, 0, 'RM-41064 EFI WIDE FORMAT SOLVENT FLUSH | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC) (verify)'),
  ('SLDD-Flex', 1, 'RDD Flex Megarich', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found in Jan-Jun 2026 purchases -- search item master for Megarich backlit flex'),
  ('SLDD-Flex', 2, 'Solvent Ink Sericol', 'Ink', 'per_sqft', 0, 0, 'RM-17028 SERICOL KSM INKS | RM-17008 SERICOL MSF TRICHROMATIC INKS | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC)'),
  ('SLDD-Flex', 3, 'Solvent Ink Type 2', 'Ink', 'per_sqft', 0, 0, 'RM-41064 EFI WIDE FORMAT SOLVENT FLUSH | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC) (verify)'),
  ('SLSD-Fabric', 1, 'RSD Fabric - POLY FAB ULTRA SATIN', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for Poly Fab / Ultra Satin fabric'),
  ('SLSD-Fabric', 2, 'Solvent Ink Sericol', 'Ink', 'per_sqft', 0, 0, 'RM-17028 SERICOL KSM INKS | RM-17008 SERICOL MSF TRICHROMATIC INKS | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC)'),
  ('SLSD-Fabric', 3, 'Solvent Ink Type 2', 'Ink', 'per_sqft', 0, 0, 'RM-41064 EFI WIDE FORMAT SOLVENT FLUSH | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC) (verify)'),
  ('SLDD-Fabric', 1, 'RSD Fabric - POLY FAB BL-250', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for BL-250 backlit fabric'),
  ('SLDD-Fabric', 2, 'Solvent Ink Sericol', 'Ink', 'per_sqft', 0, 0, 'RM-17028 SERICOL KSM INKS | RM-17008 SERICOL MSF TRICHROMATIC INKS | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC)'),
  ('SLDD-Fabric', 3, 'Solvent Ink Type 2', 'Ink', 'per_sqft', 0, 0, 'RM-41064 EFI WIDE FORMAT SOLVENT FLUSH | RM-41001 SOLVENT (SERICOL IH TRICHROMATIC) (verify)'),
  ('UVSD-Flex', 1, 'RSD Flex 340GSM', 'Substrate', 'per_sqft', 1, 0.1, 'RM-11008 FRONTLIT BLACKOUT FLEX 340GSM | RM-11039 ULTRA BLACKOUT FLEX 340 GSM | RM-11029 340 GSM SRF BLACK OUT FLEX HOT LAM'),
  ('UVSD-Flex', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVSD-Flex', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVSD-Flex', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('UVSD-Vinyl', 1, 'RSD Vinyl LG LD 1810', 'Substrate', 'per_sqft', 1, 0.1, 'RM-13123 LG 1810 GREY SAV (verify colour/finish)'),
  ('UVSD-Vinyl', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVSD-Vinyl', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVSD-Vinyl', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('UVDD-Flex', 1, 'RDD Flex Megarich', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found in Jan-Jun 2026 purchases -- search item master for Megarich backlit flex'),
  ('UVDD-Flex', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVDD-Flex', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVDD-Flex', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('UVDD-Vinyl', 1, 'RDD Vinyl LG LD 4910', 'Substrate', 'per_sqft', 1, 0.1, 'RM-13006 LG LD 4910 SAV'),
  ('UVDD-Vinyl', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVDD-Vinyl', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVDD-Vinyl', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('UVDD-Fabric', 1, 'RDD Fabric Soyang 610 UT', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for Soyang 610'),
  ('UVDD-Fabric', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVDD-Fabric', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVDD-Fabric', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('LASD-Flex', 1, 'RSD Flex 340 GSM', 'Substrate', 'per_sqft', 1, 0.1, 'RM-11008 FRONTLIT BLACKOUT FLEX 340GSM | RM-11039 ULTRA BLACKOUT FLEX 340 GSM | RM-11029 340 GSM SRF BLACK OUT FLEX HOT LAM'),
  ('LASD-Flex', 2, 'Latex Ink', 'Ink', 'per_sqft', 0, 0, 'No consumable ink match found -- search item master for Latex ink cartridge code'),
  ('LASD-Vinyl', 1, 'RSD Vinyl LG LD 1810', 'Substrate', 'per_sqft', 1, 0.1, 'RM-13123 LG 1810 GREY SAV (verify colour/finish)'),
  ('LASD-Vinyl', 2, 'Latex Ink', 'Ink', 'per_sqft', 0, 0, 'No consumable ink match found -- search item master for Latex ink cartridge code'),
  ('LADD-Flex', 1, 'RDD Flex Megarich', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found in Jan-Jun 2026 purchases -- search item master for Megarich backlit flex'),
  ('LADD-Flex', 2, 'Latex Ink', 'Ink', 'per_sqft', 0, 0, 'No consumable ink match found -- search item master for Latex ink cartridge code'),
  ('LADD-Vinyl', 1, 'RDD Vinyl LG LD 4910', 'Substrate', 'per_sqft', 1, 0.1, 'RM-13006 LG LD 4910 SAV'),
  ('LADD-Vinyl', 2, 'Latex Ink', 'Ink', 'per_sqft', 0, 0, 'No consumable ink match found -- search item master for Latex ink cartridge code'),
  ('DYSD-Fabric', 1, 'RSD Fabric Soyang 117D', 'Substrate', 'per_sqft', 1, 0.1, 'RM-14068 SOYANG STARLIGHT BACKLIT FABRIC | RM-12025 SOYANG BACKLIT FLEX (verify grade)'),
  ('DYSD-Fabric', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('DYSD-Fabric', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('DYSD-Fabric', 4, 'Silicon Keder', 'Keder/Trim', 'per_sqft', 0, 0, 'RM-41171 KEDER | RM-41198 SRK FLAT KEDER (verify silicone type)'),
  ('DYDD-Fabric', 1, 'RDD Fabric Soyang 100D', 'Substrate', 'per_sqft', 1, 0.1, 'RM-14068 SOYANG STARLIGHT BACKLIT FABRIC | RM-12025 SOYANG BACKLIT FLEX (verify grade)'),
  ('DYDD-Fabric', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('DYDD-Fabric', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('DYDD-Fabric', 4, 'Silicon Keder', 'Keder/Trim', 'per_sqft', 0, 0, 'RM-41171 KEDER | RM-41198 SRK FLAT KEDER (verify silicone type)'),
  ('DYCUR-Fabric', 1, 'RSD Fabric Demoot', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for Demoot curtain fabric'),
  ('DYCUR-Fabric', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('DYCUR-Fabric', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('ALSEGSD-Sign', 1, '23MM Aluminium Frontlit Profile', 'Aluminium/Profile', 'per_piece', 1, 0.1, 'RM-32058 FABRIC FRAME NONLIT 23MM (verify)'),
  ('ALSEGSD-Sign', 2, 'Corner Angles', 'Hardware/Fastener', 'per_piece', 0, 0, 'RM-32340 CORNER FOR BASE PROFILES | GE-24459 CORNER CLAMP | RM-30006 CORNER BOARD - 50 X 50 X 3 MM'),
  ('ALSEGSD-Sign', 3, 'Screws', 'Hardware/Fastener', 'per_piece', 0, 0, 'GE-22146 SCREW | GE-24419 M6 SCREW | GE-22714 SELF TAPPING SCREW (pick correct size)'),
  ('AlSEGDD-Sign', 1, '63MM Aluminium Backlit Profile', 'Aluminium/Profile', 'per_piece', 1, 0.1, 'RM-32259 FABRIC FRAME 63MM SINGLE SIDED MILL FINISH | RM-32708 FABRIC FRAME 63MM WPC RAL 9010'),
  ('AlSEGDD-Sign', 2, 'Corner Angles', 'Hardware/Fastener', 'per_piece', 0, 0, 'RM-32340 CORNER FOR BASE PROFILES | GE-24459 CORNER CLAMP | RM-30006 CORNER BOARD - 50 X 50 X 3 MM'),
  ('AlSEGDD-Sign', 3, 'LED Bars', 'LED/Electrical', 'per_piece', 0, 0, 'No close match found -- search item master for LED bar module'),
  ('AlSEGDD-Sign', 4, 'ACP Sheet', 'Rigid Substrate', 'per_sqft', 0, 0, 'RM-15052 ACP SHEET | RM-15067 ACP SHEET - 3MM | RM-15105 3MM ACP SHEET'),
  ('AlSEGDD-Sign', 5, 'Screws', 'Hardware/Fastener', 'per_piece', 0, 0, 'GE-22146 SCREW | GE-24419 M6 SCREW | GE-22714 SELF TAPPING SCREW (pick correct size)'),
  ('AlSEGDD-Sign', 6, 'Electrical Accessories', 'LED/Electrical', 'per_piece', 0, 0, 'GE-22557/22558/22829/23025 cable & wire items | GE-22993 MCB (pick actual accessory)'),
  ('ALSEGDD2S-Sign', 1, '100MM DS Aluminium Backlit Profile', 'Aluminium/Profile', 'per_piece', 1, 0.1, 'No close match found -- search item master for 100MM double-side SEG profile'),
  ('ALSEGDD2S-Sign', 2, 'Corner Angles', 'Hardware/Fastener', 'per_piece', 0, 0, 'RM-32340 CORNER FOR BASE PROFILES | GE-24459 CORNER CLAMP | RM-30006 CORNER BOARD - 50 X 50 X 3 MM'),
  ('ALSEGDD2S-Sign', 3, 'Edge LED', 'LED/Electrical', 'per_piece', 0, 0, 'RM-32251 EDGE LED RIGID BAR 10000K- ADS'),
  ('ALSEGDD2S-Sign', 4, 'Screws', 'Hardware/Fastener', 'per_piece', 0, 0, 'GE-22146 SCREW | GE-24419 M6 SCREW | GE-22714 SELF TAPPING SCREW (pick correct size)'),
  ('ALSEGDD2S-Sign', 5, 'Electrical Accessories', 'LED/Electrical', 'per_piece', 0, 0, 'GE-22557/22558/22829/23025 cable & wire items | GE-22993 MCB (pick actual accessory)'),
  ('ALOASDD-SIGN', 1, '130MM Outdoor Aluminium Backlit Profile', 'Aluminium/Profile', 'per_piece', 1, 0.1, 'No close match found -- search item master for 130MM outdoor profile'),
  ('ALOASDD-SIGN', 2, 'Corner Angles', 'Hardware/Fastener', 'per_piece', 0, 0, 'RM-32340 CORNER FOR BASE PROFILES | GE-24459 CORNER CLAMP | RM-30006 CORNER BOARD - 50 X 50 X 3 MM'),
  ('ALOASDD-SIGN', 3, 'Outdoor LED', 'LED/Electrical', 'per_piece', 0, 0, 'No close match found -- search item master for outdoor-rated LED module'),
  ('ALOASDD-SIGN', 4, 'ACP Sheet', 'Rigid Substrate', 'per_sqft', 0, 0, 'RM-15052 ACP SHEET | RM-15067 ACP SHEET - 3MM | RM-15105 3MM ACP SHEET'),
  ('ALOASDD-SIGN', 5, 'Screws', 'Hardware/Fastener', 'per_piece', 0, 0, 'GE-22146 SCREW | GE-24419 M6 SCREW | GE-22714 SELF TAPPING SCREW (pick correct size)'),
  ('ALOASDD-SIGN', 6, 'Electrical Accessories', 'LED/Electrical', 'per_piece', 0, 0, 'GE-22557/22558/22829/23025 cable & wire items | GE-22993 MCB (pick actual accessory)'),
  ('PFL-XLFalg', 1, 'RSD Blockout DS Polyester Fabric', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for blockout polyester flag fabric'),
  ('PFL-XLFalg', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('PFL-XLFalg', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('PFL-XLFalg', 4, 'Flag Poles', 'Flag Accessory', 'per_piece', 0, 0, 'RM-32657 FLAG POLE | RM-32673/32674 PORTABLE FLAG POLE EPE280/EPE371 | RM-32683 PORTABLE FLAG POLES'),
  ('PFL-XLFalg', 5, 'Base', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag base'),
  ('PFL-XLFalg', 6, 'Bag', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag carry bag'),
  ('PFL-L Flag', 1, 'RSD Blockout DS Polyester Fabric', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for blockout polyester flag fabric'),
  ('PFL-L Flag', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('PFL-L Flag', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('PFL-L Flag', 4, 'Flag Poles', 'Flag Accessory', 'per_piece', 0, 0, 'RM-32657 FLAG POLE | RM-32673/32674 PORTABLE FLAG POLE EPE280/EPE371 | RM-32683 PORTABLE FLAG POLES'),
  ('PFL-L Flag', 5, 'Base', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag base'),
  ('PFL-L Flag', 6, 'Bag', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag carry bag'),
  ('PFL-M Flag', 1, 'RSD Blockout DS Polyester Fabric', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for blockout polyester flag fabric'),
  ('PFL-M Flag', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('PFL-M Flag', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('PFL-M Flag', 4, 'Flag Poles', 'Flag Accessory', 'per_piece', 0, 0, 'RM-32657 FLAG POLE | RM-32673/32674 PORTABLE FLAG POLE EPE280/EPE371 | RM-32683 PORTABLE FLAG POLES'),
  ('PFL-M Flag', 5, 'Base', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag base'),
  ('PFL-M Flag', 6, 'Bag', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag carry bag'),
  ('DFL-K Flag', 1, 'RSD Blockout DS Polyester Fabric', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for blockout polyester flag fabric'),
  ('DFL-K Flag', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('DFL-K Flag', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('DFL-K Flag', 4, 'Flag Poles', 'Flag Accessory', 'per_piece', 0, 0, 'RM-32657 FLAG POLE | RM-32673/32674 PORTABLE FLAG POLE EPE280/EPE371 | RM-32683 PORTABLE FLAG POLES'),
  ('DFL-K Flag', 5, 'Base', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag base'),
  ('DFL-K Flag', 6, 'Bag', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag carry bag'),
  ('DFL-H Flag', 1, 'RSD Blockout DS Polyester Fabric', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for blockout polyester flag fabric'),
  ('DFL-H Flag', 2, 'Dye Sublimation Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for dye-sub ink cartridge code'),
  ('DFL-H Flag', 3, 'Transfer Paper', 'Transfer Paper', 'per_sqft', 0, 0, 'RM-18022 DYE SUB 95 GSM HANSOL TRANSFER PAPER | RM-18026 DYE SUB 60 GSM HANSOL TRANSFER PAPER | RM-18025 SUBLIMATION TRANSFER PAPER SCHOELLER'),
  ('DFL-H Flag', 4, 'Flag Poles', 'Flag Accessory', 'per_piece', 0, 0, 'RM-32657 FLAG POLE | RM-32673/32674 PORTABLE FLAG POLE EPE280/EPE371 | RM-32683 PORTABLE FLAG POLES'),
  ('DFL-H Flag', 5, 'Base', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag base'),
  ('DFL-H Flag', 6, 'Bag', 'Flag Accessory', 'per_piece', 0, 0, 'No close match found -- search item master for flag carry bag'),
  ('UVSD-R-COR Board', 1, '5ply Corrugated Paper Board', 'Rigid Substrate', 'per_sqft', 1, 0.1, 'RM-15008 5PLY PAPER CORRUGATED SHEET | RM-30024 5 PLY PAPER CORRUGATED BOXES | RM-15215 5 PLY CORRUGATED SHEET'),
  ('UVSD-R-COR Board', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVSD-R-COR Board', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVSD-R-COR Board', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('UVSD-R-FOA Board', 1, '5MM Foam Board', 'Rigid Substrate', 'per_sqft', 1, 0.1, 'RM-15021 FOAM BOARD - 5MM'),
  ('UVSD-R-FOA Board', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVSD-R-FOA Board', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVSD-R-FOA Board', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('UVSD-R-PP Board', 1, '2MM Polypropylene Board', 'Rigid Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for Polypropylene/Corriflute board'),
  ('UVSD-R-PP Board', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVSD-R-PP Board', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVSD-R-PP Board', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('UVSD-R-PAC Board', 1, '2MM ITC Eco Pro Board', 'Rigid Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for Eco Pro board'),
  ('UVSD-R-PAC Board', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVSD-R-PAC Board', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVSD-R-PAC Board', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK'),
  ('ALSLIM-LED Sign', 1, 'Aluminium Slim Profile', 'Aluminium/Profile', 'per_piece', 1, 0.1, 'No close match found -- search item master for LGP slim profile'),
  ('ALSLIM-LED Sign', 2, 'Corner Angles', 'Hardware/Fastener', 'per_piece', 0, 0, 'RM-32340 CORNER FOR BASE PROFILES | GE-24459 CORNER CLAMP | RM-30006 CORNER BOARD - 50 X 50 X 3 MM'),
  ('ALSLIM-LED Sign', 3, 'Edge LED', 'LED/Electrical', 'per_piece', 0, 0, 'RM-32251 EDGE LED RIGID BAR 10000K- ADS'),
  ('ALSLIM-LED Sign', 4, 'LGP Sheet', 'LED/Electrical', 'per_piece', 0, 0, 'No close match found -- search item master for Light Guide Plate sheet'),
  ('ALSLIM-LED Sign', 5, 'Screws', 'Hardware/Fastener', 'per_piece', 0, 0, 'GE-22146 SCREW | GE-24419 M6 SCREW | GE-22714 SELF TAPPING SCREW (pick correct size)'),
  ('ALSLIM-LED Sign', 6, 'Electrical Accessories', 'LED/Electrical', 'per_piece', 0, 0, 'GE-22557/22558/22829/23025 cable & wire items | GE-22993 MCB (pick actual accessory)'),
  ('WINBLD-Profile', 1, 'Track Clutch With Chain', 'Blind Hardware', 'per_piece', 1, 0.1, 'No close match found -- search item master for clutch/chain mechanism'),
  ('WINBLD-Profile', 2, 'Roller Bracket', 'Blind Hardware', 'per_piece', 0, 0, 'No close match found -- search item master for roller blind bracket'),
  ('WINBLD-Profile', 3, 'Roller Mechanism Hang Type & Endcap', 'Blind Hardware', 'per_piece', 0, 0, 'No close match found -- search item master for roller mechanism/endcap'),
  ('WINBLD-Profile', 4, 'Alum Tube', 'Aluminium/Profile', 'per_piece', 0, 0, 'No close match found -- search item master for aluminium tube (blind component)'),
  ('WINBLD-Profile', 5, 'Bottom Bar', 'Blind Hardware', 'per_piece', 0, 0, 'No close match found -- search item master for blind bottom bar'),
  ('WINBLD-Profile', 6, 'Bottom Rail', 'Blind Hardware', 'per_piece', 0, 0, 'No close match found -- search item master for blind bottom rail'),
  ('WINBLD-Profile', 7, 'Chain Stopper', 'Blind Hardware', 'per_piece', 0, 0, 'No close match found -- search item master for chain stopper'),
  ('WINBLD-Profile', 8, 'Cover', 'Blind Hardware', 'per_piece', 0, 0, 'GE-24471 FRP PIT COVER | GE-24472 PIT COVER (verify -- likely not the blind cover)'),
  ('WINBLD-Profile', 9, 'Cassette System', 'Blind Hardware', 'per_piece', 0, 0, 'No close match found -- search item master for cassette head-box system'),
  ('UVSD - Paper', 1, '350GSM Magno Satin Paper', 'Substrate', 'per_sqft', 1, 0.1, 'No close match found -- search item master for Magno Satin paper'),
  ('UVSD - Paper', 2, 'Hybrid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-41215/41207/41188/41216 HYBRID-* colour inks (pick correct colour/batch)'),
  ('UVSD - Paper', 3, '3r/5r UV Ink', 'Ink', 'per_sqft', 0, 0, 'No close match found -- search item master for 3R/5R UV ink range'),
  ('UVSD - Paper', 4, 'Rigid UV Ink', 'Ink', 'per_sqft', 0, 0, 'RM-17026 EFI 24F PRO UV RIGID INKS | RM-17029 EFI 24F PRO UV RIGID WHITE INK')
) as x(fg_code, line_no, material_name, material_category, basis, consumption_qty, wastage_pct, suggested_codes)
join public.bom_templates t on t.code = x.fg_code
on conflict do nothing;

-- Work centre rate card -- 57 rows. 'confirmed' = derived directly from the
-- user's own sample Costing sheet; 'extrapolated' = same flat rate applied to a
-- substrate/category the sample didn't cover, needs verification; 'missing' =
-- no reference data at all, rate is NULL, must be entered by the user.
insert into public.work_centre_rates (work_centre, print_mode, substrate, rate_basis, rate, confidence, note)
values
  ('WC1A Solvent Printing', 'Backlit Print', 'Fabric', 'per_sqft', 3.0, 'confirmed', 'Derived from sample Costing sheet rows for: SLDD-Fabric'),
  ('WC1A Solvent Printing', 'Frontlit Print', 'Fabric', 'per_sqft', 1.5, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Fabric'),
  ('WC1A Solvent Printing', 'Backlit Print', 'Flex', 'per_sqft', 2.0, 'confirmed', 'Derived from sample Costing sheet rows for: SLDD-Flex'),
  ('WC1A Solvent Printing', 'Frontlit Print', 'Flex', 'per_sqft', 1.0, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Flex'),
  ('WC1A Solvent Printing', 'Frontlit Print', 'Vinyl', 'per_sqft', 1.0, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Vinyl'),
  ('WC1B UV Printing', 'Backlit Print', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1B UV Printing', 'Backlit Print', 'Flex', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1B UV Printing', 'Frontlit Print', 'Flex', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1B UV Printing', 'Rigid/Direct Print', 'Paper', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1B UV Printing', 'Rigid/Direct Print', 'Rigid Board', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1B UV Printing', 'Backlit Print', 'Vinyl', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1B UV Printing', 'Frontlit Print', 'Vinyl', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1C Latex Printing', 'Backlit Print', 'Flex', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1C Latex Printing', 'Frontlit Print', 'Flex', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1C Latex Printing', 'Backlit Print', 'Vinyl', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1C Latex Printing', 'Frontlit Print', 'Vinyl', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1D Dye Sub Printing', 'Backlit Print', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1D Dye Sub Printing', 'Direct Print', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1D Dye Sub Printing', 'Frontlit Print', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC1D Dye Sub Printing', 'Flag Print', 'Other', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC2 Aluminium Cut', '-', 'Aluminium/Profile', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC2 Aluminium Cut', '-', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC3 Dye Sub Transfer', 'Backlit Print', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC3 Dye Sub Transfer', 'Direct Print', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC3 Dye Sub Transfer', 'Frontlit Print', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC3 Dye Sub Transfer', 'Flag Print', 'Other', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC6A Manual Cut Centre', '-', 'Fabric', 'per_sqft', 0.25, 'confirmed', 'Derived from sample Costing sheet rows for: SLDD-Fabric'),
  ('WC6A Manual Cut Centre', '-', 'Flex', 'per_sqft', 0.25, 'confirmed', 'Derived from sample Costing sheet rows for: SLDD-Flex, UVDD-Flex, LASD-Flex'),
  ('WC6A Manual Cut Centre', '-', 'Vinyl', 'per_sqft', 0.25, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Vinyl, LADD-Vinyl'),
  ('WC6B Digital Cut Centre', '-', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC6B Digital Cut Centre', '-', 'Flex', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC6B Digital Cut Centre', '-', 'Other', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC6B Digital Cut Centre', '-', 'Paper', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC6B Digital Cut Centre', '-', 'Rigid Board', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC6B Digital Cut Centre', '-', 'Vinyl', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC7 Seaming', '-', 'Fabric', 'per_sqft', 0.75, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Fabric'),
  ('WC7 Seaming', '-', 'Flex', 'per_sqft', 0.5, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Flex'),
  ('WC8 Sewing', '-', 'Fabric', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC8 Sewing', '-', 'Other', 'per_sqft', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC9 QC', '-', 'Aluminium/Profile', 'per_sqft', 0.15, 'extrapolated', 'WC9 QC confirmed flat at 0.15/sqft for Flex/Vinyl/Fabric; extrapolated to Aluminium/Profile -- verify.'),
  ('WC9 QC', '-', 'Fabric', 'per_sqft', 0.15, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Fabric, SLDD-Fabric, UVDD-Fabric'),
  ('WC9 QC', '-', 'Flex', 'per_sqft', 0.15, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Flex, SLDD-Flex, UVSD-Flex'),
  ('WC9 QC', '-', 'Other', 'per_sqft', 0.15, 'extrapolated', 'WC9 QC confirmed flat at 0.15/sqft for Flex/Vinyl/Fabric; extrapolated to Other -- verify.'),
  ('WC9 QC', '-', 'Paper', 'per_sqft', 0.15, 'extrapolated', 'WC9 QC confirmed flat at 0.15/sqft for Flex/Vinyl/Fabric; extrapolated to Paper -- verify.'),
  ('WC9 QC', '-', 'Rigid Board', 'per_sqft', 0.15, 'extrapolated', 'WC9 QC confirmed flat at 0.15/sqft for Flex/Vinyl/Fabric; extrapolated to Rigid Board -- verify.'),
  ('WC9 QC', '-', 'Vinyl', 'per_sqft', 0.15, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Vinyl, UVSD-Vinyl, UVDD-Vinyl'),
  ('WC10 LED Section', '-', 'Aluminium/Profile', 'per_piece', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC10 LED Section', '-', 'Fabric', 'per_piece', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC11 Assembling', '-', 'Aluminium/Profile', 'per_piece', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC11 Assembling', '-', 'Fabric', 'per_piece', NULL, 'missing', 'Not covered by the sample Costing sheet -- no reference data.'),
  ('WC12 Packing Section', '-', 'Aluminium/Profile', 'per_sqft', 0.1, 'extrapolated', 'WC12 Packing Section confirmed flat at 0.10/sqft for Flex/Vinyl/Fabric; extrapolated to Aluminium/Profile -- verify.'),
  ('WC12 Packing Section', '-', 'Fabric', 'per_sqft', 0.1, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Fabric, SLDD-Fabric, UVDD-Fabric'),
  ('WC12 Packing Section', '-', 'Flex', 'per_sqft', 0.1, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Flex, SLDD-Flex, UVSD-Flex'),
  ('WC12 Packing Section', '-', 'Other', 'per_sqft', 0.1, 'extrapolated', 'WC12 Packing Section confirmed flat at 0.10/sqft for Flex/Vinyl/Fabric; extrapolated to Other -- verify.'),
  ('WC12 Packing Section', '-', 'Paper', 'per_sqft', 0.1, 'extrapolated', 'WC12 Packing Section confirmed flat at 0.10/sqft for Flex/Vinyl/Fabric; extrapolated to Paper -- verify.'),
  ('WC12 Packing Section', '-', 'Rigid Board', 'per_sqft', 0.1, 'extrapolated', 'WC12 Packing Section confirmed flat at 0.10/sqft for Flex/Vinyl/Fabric; extrapolated to Rigid Board -- verify.'),
  ('WC12 Packing Section', '-', 'Vinyl', 'per_sqft', 0.1, 'confirmed', 'Derived from sample Costing sheet rows for: SLSD-Vinyl, UVSD-Vinyl, UVDD-Vinyl')
on conflict (work_centre, print_mode, substrate) do nothing;
