"use client";

import { useEffect, useMemo, useState } from "react";
import { FileSpreadsheet, Plus, Trash2 } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, StatCard } from "@/components/ui/Card";
import { Dropdown } from "@/components/ui/Dropdown";
import { useToast } from "@/components/ui/Notifications";
import { supabase } from "@/lib/supabase";
import type { CustomerRow, CustomerSiteRow, ContractRow, IkeaRateCardRow, EstimateRow } from "@mmdi/shared/rows";

// MMDI ONE Estimate Builder — first cut, scoped to IKEA per the user's
// request to "start with it." Pulls real products/pricing straight from
// ikea_rate_card (the contract's actual rate card, already used by AI
// Copilot's search_ikea_rate_card tool) so line items aren't hand-typed
// against a real contract, while still allowing a "non-contract / unlisted
// product" line for anything genuinely outside the rate card. One customer
// + one contract can have many billing sites (IKEA's stores below all
// share ONE contract, only the ship-to/bill-to address differs) — see
// supabase-estimate-builder-schema.sql for the schema and the IKEA site
// seed data.
//
// Design decisions locked in with the user before writing this:
// - GST is one flat % applied to (subtotal + transportation + installation)
//   -- no CGST/SGST/IGST split, even though IKEA's sites span several GST
//   states -- that split was explicitly declined in favor of simplicity.
// - Transportation/installation are entered PER LINE ITEM, as a flat
//   amount for that line (not multiplied by quantity) -- "per site/job",
//   matching how a signage installation job is actually costed.
// - quote_number is generated by public.generate_quote_number() (Postgres
//   side) -- a placeholder `<CODE>-EST-0001` scheme. The user said they'd
//   supply MMDI's real per-customer numbering series separately; that
//   function is the only place to change once it arrives.

type DraftSource = "contract" | "custom";

interface DraftLine {
  key: string;
  isContractItem: boolean;
  productName: string;
  description: string;
  additionalDescription: string;
  uom: string;
  unitRate: number;
  quantity: number;
  transportationRate: number;
  installationRate: number;
}

function emptyDraft(): Omit<DraftLine, "key"> {
  return {
    isContractItem: false,
    productName: "",
    description: "",
    additionalDescription: "",
    uom: "",
    unitRate: 0,
    quantity: 1,
    transportationRate: 0,
    installationRate: 0,
  };
}

function lineTotal(l: DraftLine) {
  return l.unitRate * l.quantity + l.transportationRate + l.installationRate;
}

function rupee(n: number) {
  return `₹${n.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
}

export default function EstimateBuilderPage() {
  const { toast } = useToast();

  const [customers, setCustomers] = useState<CustomerRow[] | null>(null);
  const [selectedCustomerId, setSelectedCustomerId] = useState("");

  const [contracts, setContracts] = useState<ContractRow[] | null>(null);
  const [selectedContractId, setSelectedContractId] = useState("");

  const [sites, setSites] = useState<CustomerSiteRow[] | null>(null);
  const [selectedSiteId, setSelectedSiteId] = useState("");

  const [rateCard, setRateCard] = useState<IkeaRateCardRow[] | null>(null);

  const [source, setSource] = useState<DraftSource>("contract");
  const [rateCardPick, setRateCardPick] = useState("");
  const [draft, setDraft] = useState<Omit<DraftLine, "key">>(emptyDraft());
  const [lines, setLines] = useState<DraftLine[]>([]);

  const [gstPercent, setGstPercent] = useState(18);
  const [notes, setNotes] = useState("");
  const [saving, setSaving] = useState(false);
  const [recent, setRecent] = useState<(EstimateRow & { customers: { name: string } | null; customer_sites: { site_name: string } | null })[] | null>(null);

  // Customers + contracts loaded once — small enough tables to fetch
  // whole, same pattern as Sales by Rep's sales-person dropdown.
  useEffect(() => {
    supabase
      .from("customers")
      .select("*")
      .order("name")
      .then(({ data }) => setCustomers((data as CustomerRow[]) ?? []));
    supabase
      .from("contracts")
      .select("*")
      .then(({ data }) => setContracts((data as ContractRow[]) ?? []));
    loadRecent();
  }, []);

  function loadRecent() {
    supabase
      .from("estimates")
      .select("*, customers(name), customer_sites(site_name)")
      .order("created_at", { ascending: false })
      .limit(10)
      .then(({ data }) => setRecent((data as never) ?? []));
  }

  const selectedCustomer = customers?.find((c) => c.id === selectedCustomerId) ?? null;
  const isIkea = !!selectedCustomer?.name?.toLowerCase().includes("ikea");

  // Contracts have no customer_id FK yet (just a free-text customer name —
  // see contracts/page.tsx) — matched here the same loose way the rest of
  // the app already treats that field.
  const matchingContracts = useMemo(
    () => (selectedCustomer && contracts ? contracts.filter((c) => c.customer.toLowerCase().includes(selectedCustomer.name.toLowerCase().split(" ")[0])) : []),
    [selectedCustomer, contracts]
  );
  // Auto-pick when there's exactly one candidate, but a manual pick (once
  // the user has one) always wins -- derived at render time, not via an
  // effect, so there's nothing to synchronize/cascade.
  const effectiveContractId = selectedContractId || (matchingContracts.length === 1 ? matchingContracts[0].id : "");

  // Selecting a different customer invalidates the previously-picked
  // contract/site/rate-card selections -- handled directly in this
  // onChange (an event, not an effect) so there's no synchronous setState
  // inside a useEffect body.
  function onCustomerChange(id: string) {
    setSelectedCustomerId(id);
    setSelectedContractId("");
    setSelectedSiteId("");
    setSites(null);
    setRateCard(null);
    setRateCardPick("");
  }

  useEffect(() => {
    if (!selectedCustomerId) return;
    supabase
      .from("customer_sites")
      .select("*")
      .eq("customer_id", selectedCustomerId)
      .order("site_name")
      .then(({ data }) => setSites((data as CustomerSiteRow[]) ?? []));
  }, [selectedCustomerId]);

  useEffect(() => {
    if (!isIkea) return;
    supabase
      .from("ikea_rate_card")
      .select("scope, material_category, product, description, uom, revised_rate, remarks")
      .order("product")
      .then(({ data }) => setRateCard((data as IkeaRateCardRow[]) ?? []));
  }, [isIkea]);

  function pickRateCardRow(idx: string) {
    setRateCardPick(idx);
    const row = rateCard?.[Number(idx)];
    if (!row) return;
    setDraft((d) => ({
      ...d,
      isContractItem: true,
      productName: row.product,
      description: row.description ?? "",
      uom: row.uom ?? "",
      unitRate: row.revised_rate,
    }));
  }

  function addLine() {
    if (!draft.productName.trim()) {
      toast("danger", "Enter or select a product first");
      return;
    }
    setLines((ls) => [...ls, { ...draft, isContractItem: source === "contract", key: crypto.randomUUID() }]);
    setDraft(emptyDraft());
    setRateCardPick("");
  }

  function removeLine(key: string) {
    setLines((ls) => ls.filter((l) => l.key !== key));
  }

  const subtotal = lines.reduce((s, l) => s + l.unitRate * l.quantity, 0);
  const transportationTotal = lines.reduce((s, l) => s + l.transportationRate, 0);
  const installationTotal = lines.reduce((s, l) => s + l.installationRate, 0);
  const taxableTotal = subtotal + transportationTotal + installationTotal;
  const gstAmount = (taxableTotal * gstPercent) / 100;
  const grandTotal = taxableTotal + gstAmount;

  async function saveEstimate() {
    if (!selectedCustomer) {
      toast("danger", "Select a customer first");
      return;
    }
    if (lines.length === 0) {
      toast("danger", "Add at least one line item");
      return;
    }
    setSaving(true);
    try {
      const { data: userData } = await supabase.auth.getUser();
      const { data: quoteNumberData, error: quoteNumberError } = await supabase.rpc("generate_quote_number", {
        p_customer_code: selectedCustomer.code,
      });
      if (quoteNumberError) throw quoteNumberError;

      const { data: estimate, error: estimateError } = await supabase
        .from("estimates")
        .insert({
          quote_number: quoteNumberData,
          customer_id: selectedCustomer.id,
          contract_id: effectiveContractId || null,
          site_id: selectedSiteId || null,
          gst_percent: gstPercent,
          subtotal,
          transportation_total: transportationTotal,
          installation_total: installationTotal,
          taxable_total: taxableTotal,
          gst_amount: gstAmount,
          grand_total: grandTotal,
          notes: notes || null,
          created_by: userData.user?.id ?? null,
        })
        .select()
        .single();
      if (estimateError) throw estimateError;

      const { error: linesError } = await supabase.from("estimate_line_items").insert(
        lines.map((l, i) => ({
          estimate_id: estimate.id,
          sort_order: i,
          is_contract_item: l.isContractItem,
          rate_card_source: l.isContractItem ? "ikea_rate_card" : null,
          product_name: l.productName,
          description: l.description || null,
          additional_description: l.additionalDescription || null,
          uom: l.uom || null,
          unit_rate: l.unitRate,
          quantity: l.quantity,
          transportation_rate: l.transportationRate,
          installation_rate: l.installationRate,
          line_subtotal: l.unitRate * l.quantity,
          line_total: lineTotal(l),
        }))
      );
      if (linesError) throw linesError;

      toast("success", `Saved ${quoteNumberData}`);
      setLines([]);
      setNotes("");
      loadRecent();
    } catch (err) {
      const message = err instanceof Error ? err.message : "Couldn't save this estimate";
      toast("danger", message);
    } finally {
      setSaving(false);
    }
  }

  return (
    <div>
      <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Tools" }, { label: "Estimate Builder" }]} />

      <div className="mt-4 flex items-start gap-4 border-b border-line pb-6">
        <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-primary-tint text-primary">
          <FileSpreadsheet size={22} />
        </span>
        <div>
          <h1 className="text-xl font-semibold text-ink">Estimate Builder</h1>
          <p className="mt-0.5 text-sm text-ink-secondary">
            Tools — build a customer estimate from their contract&rsquo;s real pricing, pick a billing site, add anything not on
            the contract as an unlisted line, and get GST-ready totals
          </p>
        </div>
      </div>

      {/* Customer / contract / site */}
      <Card interactive={false} className="my-6 flex flex-col gap-4 sm:flex-row sm:flex-wrap sm:items-end">
        <Dropdown
          label="Customer"
          placeholder={customers === null ? "Loading…" : "Select a customer"}
          options={(customers ?? []).map((c) => ({ value: c.id, label: c.name }))}
          value={selectedCustomerId}
          onChange={(v) => onCustomerChange(v as string)}
        />
        <Dropdown
          label="Contract"
          placeholder={!selectedCustomer ? "Select a customer first" : matchingContracts.length === 0 ? "No matching contract found" : "Select a contract"}
          options={matchingContracts.map((c) => ({ value: c.id, label: `${c.type ?? "Contract"} — ${c.value ?? ""}` }))}
          value={effectiveContractId}
          onChange={(v) => setSelectedContractId(v as string)}
        />
        <Dropdown
          label="Billing site"
          placeholder={!selectedCustomerId ? "Select a customer first" : sites && sites.length === 0 ? "No sites on file" : "Select a site"}
          options={(sites ?? []).map((s) => ({ value: s.id, label: s.site_name }))}
          value={selectedSiteId}
          onChange={(v) => setSelectedSiteId(v as string)}
        />
      </Card>

      {selectedSiteId && sites && (
        <p className="-mt-4 mb-6 rounded-md bg-surface-sunken px-3 py-2 text-xs text-ink-secondary">
          {(() => {
            const s = sites.find((x) => x.id === selectedSiteId);
            if (!s) return null;
            return (
              <>
                <span className="font-medium text-ink">{s.legal_entity_name ?? selectedCustomer?.name}</span> — {s.address}
                {s.gstin && <> · GSTIN {s.gstin}</>}
              </>
            );
          })()}
        </p>
      )}

      {/* Add a line */}
      <Card interactive={false} className="mb-6 flex flex-col gap-4">
        <div className="flex items-center gap-1 border-b border-line pb-3">
          <button
            type="button"
            onClick={() => setSource("contract")}
            className={`rounded-md px-3 py-1.5 text-xs font-medium ${source === "contract" ? "bg-primary-tint text-primary" : "text-ink-secondary hover:bg-surface-sunken"}`}
          >
            From contract catalog
          </button>
          <button
            type="button"
            onClick={() => {
              setSource("custom");
              setDraft((d) => ({ ...d, isContractItem: false }));
            }}
            className={`rounded-md px-3 py-1.5 text-xs font-medium ${source === "custom" ? "bg-warning-tint text-warning" : "text-ink-secondary hover:bg-surface-sunken"}`}
          >
            Non-contract / unlisted product
          </button>
        </div>

        {source === "contract" && (
          <>
            {!isIkea ? (
              <p className="text-sm text-ink-muted">
                {selectedCustomerId ? "No rate card is wired up for this customer yet — use “Non-contract / unlisted product” for now." : "Select a customer to search their contract catalog."}
              </p>
            ) : (
              <Dropdown
                label="Product (IKEA rate card)"
                placeholder={rateCard === null ? "Loading…" : "Search products"}
                options={(rateCard ?? []).map((r, i) => ({
                  value: String(i),
                  label: `${r.product} — ${rupee(r.revised_rate)}/${r.uom ?? "unit"} (${r.scope ?? "—"})`,
                }))}
                value={rateCardPick}
                onChange={(v) => pickRateCardRow(v as string)}
              />
            )}
          </>
        )}

        {(source === "custom" || draft.productName) && (
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {source === "custom" && (
              <>
                <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                  Product name
                  <input
                    value={draft.productName}
                    onChange={(e) => setDraft((d) => ({ ...d, productName: e.target.value }))}
                    className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                  />
                </label>
                <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                  Description
                  <input
                    value={draft.description}
                    onChange={(e) => setDraft((d) => ({ ...d, description: e.target.value }))}
                    className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                  />
                </label>
                <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                  UOM
                  <input
                    value={draft.uom}
                    onChange={(e) => setDraft((d) => ({ ...d, uom: e.target.value }))}
                    className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                  />
                </label>
                <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                  Unit rate (₹)
                  <input
                    type="number"
                    value={draft.unitRate}
                    onChange={(e) => setDraft((d) => ({ ...d, unitRate: Number(e.target.value) }))}
                    className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                  />
                </label>
              </>
            )}
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Additional description
              <input
                value={draft.additionalDescription}
                onChange={(e) => setDraft((d) => ({ ...d, additionalDescription: e.target.value }))}
                placeholder="Optional — size, finish, site notes…"
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Quantity
              <input
                type="number"
                min={0}
                value={draft.quantity}
                onChange={(e) => setDraft((d) => ({ ...d, quantity: Number(e.target.value) }))}
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Transportation (₹, this line)
              <input
                type="number"
                value={draft.transportationRate}
                onChange={(e) => setDraft((d) => ({ ...d, transportationRate: Number(e.target.value) }))}
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Installation (₹, this line)
              <input
                type="number"
                value={draft.installationRate}
                onChange={(e) => setDraft((d) => ({ ...d, installationRate: Number(e.target.value) }))}
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <div className="flex items-end">
              <Button variant="secondary" size="md" onClick={addLine}>
                <Plus size={16} />
                Add line
              </Button>
            </div>
          </div>
        )}
      </Card>

      {/* Line items */}
      <Card interactive={false} padding="sm" className="mb-6">
        <div className="overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="text-xs font-semibold uppercase tracking-wide text-ink-secondary">
              <tr>
                <th className="px-3 py-2">Product</th>
                <th className="px-3 py-2">Qty</th>
                <th className="px-3 py-2">Rate</th>
                <th className="px-3 py-2">Transport</th>
                <th className="px-3 py-2">Install</th>
                <th className="px-3 py-2">Line total</th>
                <th className="px-3 py-2" />
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {lines.map((l) => (
                <tr key={l.key}>
                  <td className="px-3 py-2.5">
                    <div className="flex items-center gap-2">
                      <Badge status={l.isContractItem ? "info" : "warning"}>{l.isContractItem ? "Contract" : "Unlisted"}</Badge>
                      <div>
                        <p className="font-medium text-ink">{l.productName}</p>
                        {(l.description || l.additionalDescription) && (
                          <p className="text-xs text-ink-muted">{[l.description, l.additionalDescription].filter(Boolean).join(" — ")}</p>
                        )}
                      </div>
                    </div>
                  </td>
                  <td className="px-3 py-2.5">
                    {l.quantity} {l.uom}
                  </td>
                  <td className="px-3 py-2.5">{rupee(l.unitRate)}</td>
                  <td className="px-3 py-2.5">{rupee(l.transportationRate)}</td>
                  <td className="px-3 py-2.5">{rupee(l.installationRate)}</td>
                  <td className="px-3 py-2.5 font-medium text-ink">{rupee(lineTotal(l))}</td>
                  <td className="px-3 py-2.5">
                    <Button variant="icon" size="sm" aria-label="Remove line" onClick={() => removeLine(l.key)}>
                      <Trash2 size={14} />
                    </Button>
                  </td>
                </tr>
              ))}
              {lines.length === 0 && (
                <tr>
                  <td colSpan={7} className="px-3 py-8 text-center text-ink-muted">
                    No line items yet — add one above.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Totals */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3 lg:grid-cols-5">
        <StatCard label="Subtotal" value={rupee(subtotal)} />
        <StatCard label="Transportation" value={rupee(transportationTotal)} />
        <StatCard label="Installation" value={rupee(installationTotal)} />
        <div className="rounded-lg border border-line bg-surface p-4">
          <label className="mb-1 block text-xs font-medium uppercase tracking-wide text-ink-secondary">GST %</label>
          <input
            type="number"
            value={gstPercent}
            onChange={(e) => setGstPercent(Number(e.target.value))}
            className="h-9 w-full rounded-md border border-line-strong bg-surface px-2 text-lg font-bold text-ink outline-none"
          />
        </div>
        <StatCard label="Grand total" value={rupee(grandTotal)} />
      </div>

      <div className="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
        <label className="flex w-full flex-col gap-1 text-xs font-medium text-ink-secondary sm:max-w-md">
          Notes (optional)
          <input
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <Button variant="primary" size="lg" loading={saving} onClick={saveEstimate}>
          Save estimate
        </Button>
      </div>

      {/* Recent estimates */}
      <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-ink-muted">Recent estimates</h3>
      <Card interactive={false} padding="sm">
        <div className="overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="text-xs font-semibold uppercase tracking-wide text-ink-secondary">
              <tr>
                <th className="px-3 py-2">Quote #</th>
                <th className="px-3 py-2">Customer</th>
                <th className="px-3 py-2">Site</th>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2">Grand total</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {(recent ?? []).map((e) => (
                <tr key={e.id}>
                  <td className="px-3 py-2.5 font-medium text-ink">{e.quote_number}</td>
                  <td className="px-3 py-2.5">{e.customers?.name ?? "—"}</td>
                  <td className="px-3 py-2.5">{e.customer_sites?.site_name ?? "—"}</td>
                  <td className="px-3 py-2.5">
                    <Badge status="neutral">{e.status}</Badge>
                  </td>
                  <td className="px-3 py-2.5">{rupee(e.grand_total)}</td>
                </tr>
              ))}
              {recent !== null && recent.length === 0 && (
                <tr>
                  <td colSpan={5} className="px-3 py-8 text-center text-ink-muted">
                    No estimates saved yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
