"use client";

import { useEffect, useMemo, useState } from "react";
import { Download, FileSpreadsheet, Pencil, Plus, Trash2, X } from "lucide-react";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { Badge } from "@/components/ui/Badge";
import { Button } from "@/components/ui/Button";
import { Card, StatCard } from "@/components/ui/Card";
import { Dropdown } from "@/components/ui/Dropdown";
import { useToast } from "@/components/ui/Notifications";
import { supabase } from "@/lib/supabase";
import type { CustomerRow, CustomerContactRow, ContractRow, IkeaRateCardRow, AppleRateCardRow, EstimatePoolItemRow, EstimateRow, EstimateCalcMode, EstimateLineItemRow, EstimatePaymentTermsType, EmployeeRow } from "@mmdi/shared/rows";
import { generateEstimatePdf, downloadBlob, getSizeUnit, type EstimatePdfLine } from "@/lib/estimateBuilder/pdf";
import { fetchAllRows } from "@/lib/dashboard-queries";
import { ToolAccessGuard } from "@/components/ToolAccessGuard";

// MMDI ONE Estimate Builder — scoped to IKEA first per the user's request
// to "start with it," then extended to Apple (apple_rate_card, 117 SKUs
// already used by AI Copilot's search_apple_rate_card tool). Pulls real
// products/pricing straight from the customer's own rate card so line
// items aren't hand-typed against a real contract, while still allowing a
// "non-contract / unlisted product" line for anything genuinely outside
// it. Address/GSTIN/attention person are ONE default per customer (see
// customers.address/gstin/default_attention_person) — there is no more
// per-site picker; Job No. (user-typed, permanent, searchable) is what
// now identifies which specific store/job an estimate is for. See
// supabase-estimate-builder-schema.sql + supabase-estimate-builder-jobno-
// productno-migration.sql.
//
// The header fields (Attention person, Quote subject, Job completion time,
// Delivery commitment, Payment terms) and the line-item shape (Design,
// Width/Height in cm with SQFT auto-calculated) were added to match two
// real sample quotes the user shared (IKEA Worli and an Apple Q4
// estimate) — see supabase-estimate-builder-fields-migration.sql.
//
// Design decisions locked in with the user along the way:
// - GST is one flat % applied to (subtotal + transportation + installation)
//   -- no CGST/SGST/IGST split -- that split was explicitly declined in
//   favor of simplicity.
// - Transportation/installation are entered PER LINE ITEM, as a flat
//   amount for that line (not multiplied by quantity) -- "per site/job",
//   matching how a signage installation job is actually costed.
// - Each line is priced either "nos" (quantity * rate -- e.g. Apple's A0
//   Posters/PIM lines, sold per piece) or "sqft" (total sqft * rate --
//   every vinyl/LFG line in both sample quotes): total sqft = (width_in *
//   height_in / 144) * quantity, matching exactly how both samples'
//   SQFT/Amount columns compute (verified against the real numbers in the
//   IKEA sample row by row before building this).
// - Payment terms default to 30 days for IKEA / 45 for Apple (per the
//   user's stated policy) the moment that customer is picked, but stay
//   editable — some estimates will legitimately need a different term.
// - quote_number is generated by public.generate_quote_number() (Postgres
//   side) -- a placeholder `<CODE>-EST-0001` scheme, since the real sample
//   quotes use a location/series-based number (e.g. "Worli-MUM/25-26/
//   IEPL/39") that the user said they'd supply separately.

// "pool" added per "connect Sign Estimator, Cost Sheet, and Estimate
// Builder together -- create a pool where all sign estimates and cost
// sheet products [go], then it is moved to estimate module and there
// select the customer and create estimates." Picking a pool item pre-fills
// the draft below same as "history" does, but from estimate_pool_items
// (supabase-estimate-pool-migration.sql) instead of past sales.
type DraftSource = "contract" | "custom" | "history" | "pool";

// One distinct product previously sold to this customer, per
// sales_transactions -- for customers with no contract/rate card wired up
// (which is most of them; only IKEA/Apple have one so far), this is the
// only source of "what did we actually charge them last time" short of
// digging through old invoices by hand. latestRate/latestDate come from
// whichever of that customer's transactions for this item_code has the
// most recent invoice_date -- exactly "the latest price against whatever
// we sold them," not an average across their whole history (an average
// would blend in old, stale pricing).
interface SalesHistoryProduct {
  itemCode: string | null;
  itemDescription: string | null;
  productCategory: string | null;
  latestRate: number | null;
  latestDate: string | null;
  timesPurchased: number;
}

// SQFT-priced lines can be entered two ways: real Width × Height
// dimensions (the default), or a bulk total SQFT typed directly when
// there's no width/height to multiply -- e.g. quoting "500 sqft of vinyl"
// as one lump area rather than a specific panel size. Purely a UI-side
// toggle: bulkSqft has no DB column of its own, since sqft_total (already
// a stored column either way) carries the final number regardless of
// which entry method produced it.
type SizeEntryMode = "dimensions" | "bulk";

interface DraftLine {
  key: string;
  isContractItem: boolean;
  productNo: string;
  productName: string;
  designName: string;
  description: string;
  additionalDescription: string;
  uom: string;
  calcMode: EstimateCalcMode;
  sizeEntryMode: SizeEntryMode;
  widthCm: number;
  heightCm: number;
  bulkSqft: number;
  unitRate: number;
  quantity: number;
  transportationRate: number;
  installationRate: number;
  // Set when this line came from the estimate pool (Sign Estimator/Cost
  // Sheet) -- lets saveEstimate mark that pool item 'used' once the
  // estimate is actually saved, so it doesn't accidentally get quoted to
  // a second customer too. Undefined for every other source.
  poolItemId?: string;
}

function emptyDraft(): Omit<DraftLine, "key"> {
  return {
    isContractItem: false,
    productNo: "",
    productName: "",
    designName: "",
    description: "",
    additionalDescription: "",
    uom: "",
    calcMode: "sqft",
    sizeEntryMode: "dimensions",
    widthCm: 0,
    heightCm: 0,
    bulkSqft: 0,
    unitRate: 0,
    quantity: 1,
    transportationRate: 0,
    installationRate: 0,
  };
}

// A rate-card row's own UOM text tells us whether it's normally sold per
// piece ("Nos"/"Qty"/"Each") or by area ("SQFT"/"SQM") -- inferred once
// when a product is picked, then always editable/overridable per line.
function inferCalcMode(uom: string | null | undefined): EstimateCalcMode {
  const u = (uom ?? "").toLowerCase();
  return /nos|qty|each|pc|piece/.test(u) ? "nos" : "sqft";
}

const CM_PER_IN = 2.54;
// Width/Height default to cm, but the UOM dropdown (see getSizeUnit in
// pdf.ts) can switch them to feet or inches instead -- e.g. a 10x5 signage
// job can be typed as 10/5 with UOM "Feet" rather than hand-converting to
// 304.8/152.4 cm first. widthCm/heightCm keep their field names for
// minimal disruption to the DB columns/save-load code they map to, but
// hold whichever unit the line's UOM specifies.
function widthIn(l: Pick<DraftLine, "widthCm" | "uom">) {
  const unit = getSizeUnit(l.uom);
  if (unit === "ft") return l.widthCm * 12;
  if (unit === "in") return l.widthCm;
  return l.widthCm / CM_PER_IN;
}
function heightIn(l: Pick<DraftLine, "heightCm" | "uom">) {
  const unit = getSizeUnit(l.uom);
  if (unit === "ft") return l.heightCm * 12;
  if (unit === "in") return l.heightCm;
  return l.heightCm / CM_PER_IN;
}
function sqftTotal(l: Pick<DraftLine, "calcMode" | "sizeEntryMode" | "widthCm" | "heightCm" | "bulkSqft" | "quantity" | "uom">) {
  if (l.calcMode !== "sqft") return 0;
  if (l.sizeEntryMode === "bulk") return l.bulkSqft * l.quantity;
  return (widthIn(l) * heightIn(l)) / 144 * l.quantity;
}
function lineSubtotal(l: Pick<DraftLine, "calcMode" | "sizeEntryMode" | "widthCm" | "heightCm" | "bulkSqft" | "quantity" | "unitRate" | "uom">) {
  return l.calcMode === "sqft" ? sqftTotal(l) * l.unitRate : l.quantity * l.unitRate;
}
function lineTotal(l: DraftLine) {
  return lineSubtotal(l) + l.transportationRate + l.installationRate;
}

function rupee(n: number) {
  return `₹${n.toLocaleString("en-IN", { maximumFractionDigits: 2 })}`;
}

export default function EstimateBuilderPage() {
  const { toast } = useToast();

  const [customers, setCustomers] = useState<CustomerRow[] | null>(null);
  const [selectedCustomerId, setSelectedCustomerId] = useState("");

  const [contracts, setContracts] = useState<ContractRow[] | null>(null);
  const [selectedContractId, setSelectedContractId] = useState("");

  const [rateCard, setRateCard] = useState<IkeaRateCardRow[] | null>(null);
  const [appleRateCard, setAppleRateCard] = useState<AppleRateCardRow[] | null>(null);
  const [salesHistory, setSalesHistory] = useState<SalesHistoryProduct[] | null>(null);

  const [source, setSource] = useState<DraftSource>("contract");
  const [rateCardPick, setRateCardPick] = useState("");
  const [historyPick, setHistoryPick] = useState("");
  const [poolItems, setPoolItems] = useState<EstimatePoolItemRow[] | null>(null);
  const [poolPick, setPoolPick] = useState("");
  // The pool item id backing the current draft, if source === "pool" --
  // kept separate from `draft` (a DraftLine doesn't exist as such until
  // addLine() pushes it) so addLine can stamp DraftLine.poolItemId.
  const [pendingPoolItemId, setPendingPoolItemId] = useState<string | null>(null);
  // Print/Shipping/Installation get pulled out into their own separate line
  // items (customers ask for these itemized, not folded into one combined
  // Signage row/amount) -- pickPoolRow precomputes them fully formed here,
  // and addLine() appends them alongside the (still-editable) primary draft
  // line when a Sign Estimator pool pick provides any of them.
  const [pendingPoolExtraLines, setPendingPoolExtraLines] = useState<Omit<DraftLine, "key">[]>([]);
  const [draft, setDraft] = useState<Omit<DraftLine, "key">>(emptyDraft());
  const [lines, setLines] = useState<DraftLine[]>([]);

  const [gstPercent, setGstPercent] = useState(18);
  const [notes, setNotes] = useState("");
  const [jobNumber, setJobNumber] = useState("");
  const [attentionPerson, setAttentionPerson] = useState("");
  // Active contacts on file for the selected customer (see the Customer
  // workspace's contact management) -- the quick-pick list next to
  // Attention person below. Deliberately NOT read from customers.
  // default_attention_person: that flat field goes stale the moment
  // someone's deactivated/added in the real contacts table, which is
  // exactly the bug this replaces (an estimate kept showing a contact who
  // had already been marked as having left).
  const [customerContacts, setCustomerContacts] = useState<CustomerContactRow[] | null>(null);
  // Defaults to the standard subject line so it doesn't need retyping on
  // every new estimate -- still fully editable, and loadEstimateForEdit
  // below overwrites this with whatever was actually saved when reopening
  // an existing estimate.
  const [quoteSubject, setQuoteSubject] = useState("Quote for - Digital Printing Graphics");
  const [customerAddress, setCustomerAddress] = useState("");
  const [customerGstin, setCustomerGstin] = useState("");
  const [jobCompletionTime, setJobCompletionTime] = useState("");
  const [deliveryCommitment, setDeliveryCommitment] = useState("");
  const [paymentTermsType, setPaymentTermsType] = useState<EstimatePaymentTermsType>("net_days");
  const [paymentTermsDays, setPaymentTermsDays] = useState<number | "">("");
  // Sales person for the PDF's sign-off block -- replaces the old
  // hardcoded "Naresh Kumar D" default. No default person here either:
  // every estimate starts blank and picks (or types) whoever actually
  // built it, same "snapshot at save time, stays editable" pattern as
  // Attention person.
  const [employees, setEmployees] = useState<EmployeeRow[] | null>(null);
  const [salespersonPick, setSalespersonPick] = useState("");
  const [salespersonName, setSalespersonName] = useState("");
  const [salespersonDesignation, setSalespersonDesignation] = useState("");
  const [salespersonPhone, setSalespersonPhone] = useState("");
  const [salespersonEmail, setSalespersonEmail] = useState("");
  const [saving, setSaving] = useState(false);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  // Editing an existing estimate never overwrites it -- Save always
  // inserts a new row (see supabase-estimate-builder-versions-migration.sql)
  // linked back to this lineage via root_estimate_id, with an incremented
  // version + "-Vn" suffix on the quote number. `editingRootId` is the
  // very first version's id (itself, if you're editing V1); `editingBase
  // QuoteNumber` is that first version's quote number with any existing
  // "-Vn" suffix stripped back off, so V3 built from editing V2 still gets
  // "<base>-V3", not "<base>-V2-V3".
  const [editingEstimateId, setEditingEstimateId] = useState<string | null>(null);
  const [editingRootId, setEditingRootId] = useState<string | null>(null);
  const [editingBaseQuoteNumber, setEditingBaseQuoteNumber] = useState<string | null>(null);
  const [editingVersion, setEditingVersion] = useState(1);

  type RecentEstimate = EstimateRow & {
    customers: { name: string } | null;
    customer_sites: { site_name: string } | null;
  };
  const [recent, setRecent] = useState<RecentEstimate[] | null>(null);

  // Customers + contracts loaded once. Supabase/PostgREST caps any
  // unpaginated select at 1000 rows — with 1500+ customers now on file,
  // a plain .select("*") silently cut off everything alphabetically past
  // "T" or so (e.g. "Unicorn Infosolutions" never made it into this
  // dropdown). fetchAllRows (src/lib/dashboard-queries.ts) pages through
  // with .range() until a fetch comes back short of a full page, so the
  // dropdown always has the complete list no matter how large the table
  // grows.
  useEffect(() => {
    fetchAllRows<CustomerRow>((from, to) => supabase.from("customers").select("*").order("name").range(from, to)).then(setCustomers);
    supabase
      .from("contracts")
      .select("*")
      .then(({ data }) => setContracts((data as ContractRow[]) ?? []));
    fetchAllRows<EmployeeRow>((from, to) => supabase.from("employees").select("*").order("name").range(from, to)).then(setEmployees);
    loadRecent();
    loadPoolItems();
  }, []);

  // Estimate pool -- Sign Estimator/Cost Sheet items still waiting to be
  // pulled into a quote. Customer-less by design (see the migration's
  // header), so this loads once up front rather than per-customer.
  function loadPoolItems() {
    supabase
      .from("estimate_pool_items")
      .select("*")
      .eq("status", "available")
      .order("created_at", { ascending: false })
      .then(({ data, error }) => {
        if (error) return;
        setPoolItems((data as EstimatePoolItemRow[]) ?? []);
      });
  }

  function loadRecent() {
    supabase
      .from("estimates")
      .select("*, customers(name), customer_sites(site_name)")
      .order("created_at", { ascending: false })
      .limit(10)
      .then(({ data }) => setRecent((data as never) ?? []));
  }

  function pdfLinesFrom(items: EstimateLineItemRow[]): EstimatePdfLine[] {
    return items.map((i) => ({
      productNo: i.product_no,
      productName: i.product_name,
      designName: i.design_name,
      description: i.description,
      additionalDescription: i.additional_description,
      uom: i.uom,
      calcMode: i.calc_mode,
      widthCm: i.width_cm,
      heightCm: i.height_cm,
      quantity: i.quantity,
      sqftTotal: i.sqft_total,
      unitRate: i.unit_rate,
      transportationRate: i.transportation_rate,
      installationRate: i.installation_rate,
    }));
  }

  async function downloadRecentPdf(estimate: RecentEstimate) {
    setDownloadingId(estimate.id);
    try {
      const { data: items, error } = await supabase
        .from("estimate_line_items")
        .select("*")
        .eq("estimate_id", estimate.id)
        .order("sort_order");
      if (error) throw error;
      const blob = await generateEstimatePdf({
        quoteNumber: estimate.quote_number ?? estimate.id,
        version: estimate.version,
        createdAt: estimate.created_at,
        customerName: estimate.customers?.name ?? "Customer",
        siteLegalEntityName: estimate.customer_sites?.site_name ?? null,
        jobNumber: estimate.job_number,
        customerAddress: estimate.customer_address,
        customerGstin: estimate.customer_gstin,
        attentionPerson: estimate.attention_person,
        quoteSubject: estimate.quote_subject,
        gstPercent: estimate.gst_percent,
        jobCompletionTime: estimate.job_completion_time,
        deliveryCommitment: estimate.delivery_commitment,
        paymentTermsType: estimate.payment_terms_type ?? "net_days",
        paymentTermsDays: estimate.payment_terms_days,
        notes: estimate.notes,
        salespersonName: estimate.salesperson_name,
        salespersonDesignation: estimate.salesperson_designation,
        salespersonPhone: estimate.salesperson_phone,
        salespersonEmail: estimate.salesperson_email,
        lines: pdfLinesFrom((items as EstimateLineItemRow[]) ?? []),
      });
      downloadBlob(blob, `${estimate.quote_number ?? "estimate"}.pdf`);
    } catch (err) {
      const message = err instanceof Error ? err.message : "Couldn't build this PDF";
      toast("danger", message);
    } finally {
      setDownloadingId(null);
    }
  }

  async function loadEstimateForEdit(estimate: RecentEstimate) {
    try {
      const { data: items, error } = await supabase
        .from("estimate_line_items")
        .select("*")
        .eq("estimate_id", estimate.id)
        .order("sort_order");
      if (error) throw error;

      setSelectedCustomerId(estimate.customer_id);
      setSelectedContractId(estimate.contract_id ?? "");
      setGstPercent(estimate.gst_percent);
      setNotes(estimate.notes ?? "");
      setJobNumber(estimate.job_number ?? "");
      setAttentionPerson(estimate.attention_person ?? "");
      void loadCustomerContacts(estimate.customer_id, { autofill: false });
      void loadSalesHistory(estimate.customer_id);
      setQuoteSubject(estimate.quote_subject ?? "");
      setCustomerAddress(estimate.customer_address ?? "");
      setCustomerGstin(estimate.customer_gstin ?? "");
      setJobCompletionTime(estimate.job_completion_time ?? "");
      setDeliveryCommitment(estimate.delivery_commitment ?? "");
      setPaymentTermsType(estimate.payment_terms_type ?? "net_days");
      setPaymentTermsDays(estimate.payment_terms_days ?? "");
      setSalespersonName(estimate.salesperson_name ?? "");
      setSalespersonDesignation(estimate.salesperson_designation ?? "");
      setSalespersonPhone(estimate.salesperson_phone ?? "");
      setSalespersonEmail(estimate.salesperson_email ?? "");
      setLines(
        ((items as EstimateLineItemRow[]) ?? []).map((i) => {
          // A bulk-entered line has no width_cm/height_cm on file (they
          // were never asked for) but does have a stored sqft_total --
          // reverse out the per-qty bulk figure so editing this estimate
          // shows the same "Total SQFT" entry the line was originally
          // built with, instead of blank Width/Height boxes.
          const wasBulk = i.calc_mode === "sqft" && !i.width_cm && !i.height_cm && !!i.sqft_total;
          return {
            key: crypto.randomUUID(),
            isContractItem: i.is_contract_item,
            productNo: i.product_no ?? "",
            productName: i.product_name,
            designName: i.design_name ?? "",
            description: i.description ?? "",
            additionalDescription: i.additional_description ?? "",
            uom: i.uom ?? "",
            calcMode: i.calc_mode,
            sizeEntryMode: wasBulk ? ("bulk" as const) : ("dimensions" as const),
            widthCm: i.width_cm ?? 0,
            heightCm: i.height_cm ?? 0,
            bulkSqft: wasBulk ? (i.sqft_total as number) / (i.quantity || 1) : 0,
            unitRate: i.unit_rate,
            quantity: i.quantity,
            transportationRate: i.transportation_rate,
            installationRate: i.installation_rate,
          };
        })
      );

      const rootId = estimate.root_estimate_id ?? estimate.id;
      setEditingEstimateId(estimate.id);
      setEditingRootId(rootId);
      setEditingVersion(estimate.version);
      setEditingBaseQuoteNumber((estimate.quote_number ?? "").replace(/-V\d+$/, ""));
      toast("info", `Loaded ${estimate.quote_number} for editing — saving will create the next version`);
      window.scrollTo({ top: 0, behavior: "smooth" });
    } catch (err) {
      const message = err instanceof Error ? err.message : "Couldn't load this estimate for editing";
      toast("danger", message);
    }
  }

  // Full reset back to a blank form -- used both by "Cancel edit" (leaving
  // an in-progress edit without saving a new version) and the "New
  // Estimate" button (the user no longer has to hand-clear every field
  // themselves before starting the next quote). Anything not explicitly
  // reset here keeps its default useState() initializer in sync -- see
  // those declarations above if a new field gets added later.
  function resetForm() {
    setEditingEstimateId(null);
    setEditingRootId(null);
    setEditingBaseQuoteNumber(null);
    setEditingVersion(1);
    setSelectedCustomerId("");
    setSelectedContractId("");
    setRateCardPick("");
    setHistoryPick("");
    setCustomerContacts(null);
    setSalesHistory(null);
    setSource("contract");
    setDraft(emptyDraft());
    setLines([]);
    setGstPercent(18);
    setNotes("");
    setJobNumber("");
    setAttentionPerson("");
    setQuoteSubject("Quote for - Digital Printing Graphics");
    setCustomerAddress("");
    setCustomerGstin("");
    setJobCompletionTime("");
    setDeliveryCommitment("");
    setPaymentTermsType("net_days");
    setPaymentTermsDays("");
    setSalespersonPick("");
    setSalespersonName("");
    setSalespersonDesignation("");
    setSalespersonPhone("");
    setSalespersonEmail("");
  }

  function cancelEdit() {
    resetForm();
  }

  function startNewEstimate() {
    const hasContent = !!selectedCustomerId || lines.length > 0 || !!editingEstimateId;
    if (hasContent && !window.confirm("Start a new estimate? This clears everything currently filled in on this form.")) {
      return;
    }
    resetForm();
    toast("info", "Started a new estimate — form cleared");
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  const selectedCustomer = customers?.find((c) => c.id === selectedCustomerId) ?? null;
  const isIkea = !!selectedCustomer?.name?.toLowerCase().includes("ikea");
  const isApple = !!selectedCustomer?.name?.toLowerCase().includes("apple");

  // Contracts have no customer_id FK yet (just a free-text customer name —
  // see contracts/page.tsx) — matched here the same loose way the rest of
  // the app already treats that field.
  const matchingContracts = useMemo(
    () => (selectedCustomer && contracts ? contracts.filter((c) => c.customer.toLowerCase().includes(selectedCustomer.name.toLowerCase().split(" ")[0])) : []),
    [selectedCustomer, contracts]
  );
  // Auto-pick when there's exactly one candidate, but a manual pick (once
  // the user has one) always wins -- derived at render time, not via an
  // effect, so there's nothing to synchronize/cascade.
  const effectiveContractId = selectedContractId || (matchingContracts.length === 1 ? matchingContracts[0].id : "");

  // Selecting a different customer invalidates the previously-picked
  // contract/rate-card selections, and resets payment terms to that
  // customer's default (IKEA 30 / Apple 45 / anyone else blank -- fill in
  // manually) -- handled directly in this onChange (an event, not an
  // effect) so there's no synchronous setState inside a useEffect body.
  //
  // Address/GSTIN/attention person now come from the customer record
  // ONLY -- there's no more Billing Site picker (removed per the user's
  // request: one default address/contact per customer, not one per
  // store). Job No. below is what now identifies which specific job/site
  // this estimate is for.
  // Fetches this customer's ACTIVE contacts (never the deactivated ones --
  // see supabase-customer-contacts-mobile-active-migration.sql) for the
  // quick-pick list. `autofill` only runs when a person is actively
  // changing the customer in the dropdown -- NOT when loading an existing
  // estimate for editing, where the saved attentionPerson must win as-is
  // regardless of who's active today.
  async function loadCustomerContacts(customerId: string, opts: { autofill: boolean }) {
    const { data } = await supabase
      .from("customer_contacts")
      .select("*")
      .eq("customer_id", customerId)
      .eq("is_active", true)
      .order("name");
    const list = (data as CustomerContactRow[]) ?? [];
    setCustomerContacts(list);
    if (opts.autofill) {
      setAttentionPerson(list.length === 1 ? list[0].name : "");
    }
  }

  // Collapses every past sale to this customer down to one row per distinct
  // product (item_code, falling back to item_description when a row has no
  // code) carrying only that product's MOST RECENT rate -- sorted
  // client-side by invoice_date descending first, so "first row seen per
  // key wins" always means "the latest one," never an average blended with
  // old pricing. Paginated via fetchAllRows since a long-standing customer
  // can easily have more than 1000 line items on file (see that helper's
  // comment in dashboard-queries.ts for why a bare .select() can't be
  // trusted here).
  async function loadSalesHistory(customerId: string) {
    const rows = await fetchAllRows<{
      item_code: string | null;
      item_description: string | null;
      product_category: string | null;
      rate: number | null;
      invoice_date: string | null;
    }>((from, to) =>
      supabase
        .from("sales_transactions")
        .select("item_code, item_description, product_category, rate, invoice_date")
        .eq("customer_id", customerId)
        .range(from, to)
    );
    rows.sort((a, b) => (b.invoice_date ?? "").localeCompare(a.invoice_date ?? ""));

    const byKey = new Map<string, SalesHistoryProduct>();
    for (const r of rows) {
      const key = r.item_code || r.item_description;
      if (!key) continue;
      const existing = byKey.get(key);
      if (existing) {
        existing.timesPurchased += 1;
        continue;
      }
      byKey.set(key, {
        itemCode: r.item_code,
        itemDescription: r.item_description,
        productCategory: r.product_category,
        latestRate: r.rate,
        latestDate: r.invoice_date,
        timesPurchased: 1,
      });
    }
    // Most-recently-purchased product first -- surfaces "what they've
    // actually been buying lately" at the top of the picker.
    setSalesHistory([...byKey.values()].sort((a, b) => (b.latestDate ?? "").localeCompare(a.latestDate ?? "")));
  }

  function onCustomerChange(id: string) {
    setSelectedCustomerId(id);
    setSelectedContractId("");
    setRateCard(null);
    setAppleRateCard(null);
    setRateCardPick("");
    setSalesHistory(null);
    setHistoryPick("");
    setCustomerContacts(null);
    const customer = customers?.find((c) => c.id === id);
    setCustomerAddress(customer?.address ?? "");
    setCustomerGstin(customer?.gstin ?? "");
    void loadCustomerContacts(id, { autofill: true });
    void loadSalesHistory(id);
    const name = customer?.name?.toLowerCase() ?? "";
    setPaymentTermsType("net_days");
    if (name.includes("ikea")) setPaymentTermsDays(30);
    else if (name.includes("apple")) setPaymentTermsDays(45);
    else setPaymentTermsDays("");
  }

  useEffect(() => {
    if (!isIkea) return;
    supabase
      .from("ikea_rate_card")
      .select("sl_no, scope, material_category, product, description, uom, revised_rate, remarks")
      .order("product")
      .then(({ data }) => setRateCard((data as IkeaRateCardRow[]) ?? []));
  }, [isIkea]);

  useEffect(() => {
    if (!isApple) return;
    supabase
      .from("apple_rate_card")
      .select("sku_id, sku_description, category, program, substrate, unit, bill_rate, rate_inr_each, start_date, end_date, sqft")
      .order("sku_id")
      .then(({ data }) => setAppleRateCard((data as AppleRateCardRow[]) ?? []));
  }, [isApple]);

  // IKEA's rate card DOES have a real serial number (sl_no, backfilled from
  // the master contract sheet's "Sl. No." column) -- use it as-is, same as
  // Apple's sku_id below. Only falls back to list position for any row that
  // somehow has no sl_no set (e.g. a brand-new row added directly in
  // Supabase before the sheet's numbering catches up), still editable
  // afterwards to match the real contract document if it differs.
  function pickIkeaRateCardRow(idx: string) {
    setRateCardPick(idx);
    const row = rateCard?.[Number(idx)];
    if (!row) return;
    setDraft((d) => ({
      ...d,
      isContractItem: true,
      productNo: row.sl_no != null ? String(row.sl_no) : String(Number(idx) + 1),
      productName: row.product,
      description: row.description ?? "",
      uom: row.uom ?? "",
      calcMode: inferCalcMode(row.uom),
      unitRate: row.revised_rate,
    }));
  }

  // Apple's rate card DOES have a real per-item identifier (sku_id) --
  // that's the contract's own "product number", used as-is.
  function pickAppleRateCardRow(idx: string) {
    setRateCardPick(idx);
    const row = appleRateCard?.[Number(idx)];
    if (!row) return;
    setDraft((d) => ({
      ...d,
      isContractItem: true,
      productNo: row.sku_id,
      productName: row.sku_description || row.sku_id,
      description: [row.category, row.program, row.substrate].filter(Boolean).join(" / "),
      uom: row.unit ?? (row.sqft ? "SQFT" : "Nos"),
      calcMode: inferCalcMode(row.unit),
      unitRate: row.rate_inr_each ?? row.bill_rate,
    }));
  }

  // Sales history isn't a signed contract -- picking a previously-sold
  // product only pre-fills a starting point (name/description/last rate),
  // all of it still freely editable below, unlike a contract pick which is
  // treated as locked/authoritative. isContractItem stays false so these
  // lines are correctly tagged "Unlisted" in the line-items table, same as
  // a fully custom line.
  function pickHistoryRow(idx: string) {
    setHistoryPick(idx);
    const row = salesHistory?.[Number(idx)];
    if (!row) return;
    setDraft((d) => ({
      ...d,
      isContractItem: false,
      productNo: row.itemCode ?? "",
      productName: row.itemDescription || row.itemCode || "",
      description: row.productCategory ?? "",
      unitRate: row.latestRate ?? 0,
    }));
  }

  // Small human-readable line built from a pool item's denormalized
  // summary -- for Cost Sheet this is the real physical materials used
  // (substrate, lamination, trims, hardware -- never ink, which is priced
  // in as a service, see CostSheetCalcTab's addToPool), for Sign Estimator
  // it's the category + dims, since that tool doesn't track a materials
  // list the same way.
  // includePrint=false is used when Print is being split out into its own
  // dedicated line item (see pickPoolRow's sign_estimator branch below) --
  // the Signage line's own description shouldn't repeat the print spec that
  // now has its own row.
  function poolItemDescription(item: EstimatePoolItemRow, opts?: { includePrint?: boolean }): string {
    const includePrint = opts?.includePrint ?? true;
    const s = item.summary as {
      description?: string;
      materials?: { name: string; mappedTo: string | null }[];
      categoryLabel?: string;
      dimW?: number;
      dimH?: number;
      dimUnit?: string;
      qty?: number;
      profileName?: string | null;
      printMediaName?: string | null;
      printSqFt?: number | null;
      printRatePerSqft?: number | null;
    };
    if (item.source === "cost_sheet") {
      const materialsLine = (s.materials ?? []).map((m) => (m.mappedTo ? `${m.name}: ${m.mappedTo}` : m.name)).join("; ");
      return [s.description, materialsLine].filter(Boolean).join(" — ") || "Cost Sheet job";
    }
    // Profile and print detail are shown as their own segments (not folded
    // into a single generic line) so the profile spec (e.g. "70mm SEG
    // Profile") and the print media's own sq.ft + ₹/sq.ft rate are each
    // clearly visible on the quote, instead of only the combined total.
    const profileLine = s.profileName ? `Profile: ${s.profileName}` : null;
    const printLine =
      s.printMediaName && s.printSqFt != null && s.printRatePerSqft != null
        ? `Print: ${s.printMediaName} — ${s.printSqFt} sq.ft @ ₹${s.printRatePerSqft}/sq.ft`
        : s.printMediaName ?? null;
    const parts = [
      s.categoryLabel,
      s.dimW && s.dimH ? `${s.dimW}×${s.dimH} ${s.dimUnit ?? ""}`.trim() : null,
      s.qty ? `qty ${s.qty}` : null,
      profileLine,
      includePrint ? printLine : null,
    ];
    return parts.filter(Boolean).join(" — ") || "Sign Estimator job";
  }

  // Picking a pool item pre-fills the draft as a real SQFT line for Cost
  // Sheet items (width x height x qty at the same ₹/sqft rate the job was
  // costed at -- NOT the whole-job total treated as a per-sqft rate, which
  // would massively overprice the line the moment someone entered real
  // dimensions) since that's exactly how Cost Sheet itself prices; Sign
  // Estimator items come in as a "nos" line (LED/profile/print costs don't
  // divide evenly across area the way a BOM's per-sqft material+process
  // cost does, so there's no single clean ₹/sqft rate for the whole job)
  // but still carry the sign's real Width×Height -- "Width height to be
  // mentioned irrespective of price method" -- plus Shipping/Installation
  // split out into their own dedicated columns instead of being buried in
  // one lump sell_amount, same as every other line already does.
  function pickPoolRow(idx: string) {
    setPoolPick(idx);
    const row = poolItems?.[Number(idx)];
    if (!row) return;
    const s = row.summary as {
      width?: number | null;
      height?: number | null;
      uom?: string;
      qty?: number | null;
      unitRatePerSqft?: number | null;
      dimW?: number | null;
      dimH?: number | null;
      dimUnit?: string | null;
      signageSell?: number | null;
      printSell?: number | null;
      printMediaName?: string | null;
      printSqFt?: number | null;
      printRatePerSqft?: number | null;
      shipping?: number | null;
      installSell?: number | null;
    };
    if (row.source === "cost_sheet" && s.width && s.height && s.unitRatePerSqft != null) {
      setDraft((d) => ({
        ...d,
        isContractItem: false,
        productNo: "",
        productName: row.label,
        description: poolItemDescription(row),
        calcMode: "sqft",
        sizeEntryMode: "dimensions",
        // Cost Sheet's own UOM is "FT"/"INC" -- getSizeUnit (shared with
        // the PDF) only recognizes "ft"/"feet" and "in"/"inch", so this
        // maps to what it actually expects rather than passing "INC"
        // through and silently falling back to centimeters.
        uom: s.uom === "INC" ? "in" : "ft",
        widthCm: s.width ?? 0,
        heightCm: s.height ?? 0,
        quantity: s.qty || 1,
        unitRate: s.unitRatePerSqft ?? 0,
      }));
      setPendingPoolExtraLines([]);
    } else if (row.source === "sign_estimator") {
      // Sign Estimator's own dims are in mm/feet/inches, not cm/ft/in --
      // convert mm to cm (getSizeUnit has no "mm" case), pass feet/inches
      // straight through since those units already match.
      const dimUnit = s.dimUnit ?? "mm";
      const uom = dimUnit === "feet" ? "ft" : dimUnit === "inches" ? "in" : "cm";
      const rawW = s.dimW ?? 0;
      const rawH = s.dimH ?? 0;
      const widthCm = dimUnit === "mm" ? rawW / 10 : rawW;
      const heightCm = dimUnit === "mm" ? rawH / 10 : rawH;
      const qty = s.qty || 1;
      const signageSell = s.signageSell ?? 0;
      // Only Print gets split into its own dedicated line item (see
      // pendingPoolExtraLines below) -- Shipping/Installation go right back
      // onto the Signage line's own transportationRate/installationRate
      // fields, using the columns this table already has for exactly that,
      // rather than becoming separate rows too.
      setDraft((d) => ({
        ...d,
        isContractItem: false,
        productNo: "",
        productName: `${row.label} — Signage`,
        description: poolItemDescription(row, { includePrint: false }),
        calcMode: "nos",
        sizeEntryMode: "dimensions",
        uom,
        widthCm,
        heightCm,
        quantity: qty,
        unitRate: qty > 0 ? Math.round(signageSell / qty) : Math.round(signageSell),
        transportationRate: s.shipping ?? 0,
        installationRate: s.installSell ?? 0,
      }));

      const extras: Omit<DraftLine, "key">[] = [];
      if (s.printSell) {
        // Reconstructs the print line at the exact same ₹/sq.ft rate (and
        // total sq.ft) the job was priced at in Sign Estimator, when that
        // detail is available -- quantity × bulkSqft × unitRate then
        // reproduces printSell exactly. Falls back to a plain "nos" line
        // (no real sq.ft/rate to show) when the job was priced at a flat
        // lumpsum instead.
        const havePrintRate = s.printSqFt != null && s.printRatePerSqft != null;
        extras.push({
          ...emptyDraft(),
          productName: `${row.label} — Printing`,
          description: s.printMediaName ?? "Printing",
          calcMode: havePrintRate ? "sqft" : "nos",
          sizeEntryMode: "bulk",
          uom,
          widthCm,
          heightCm,
          bulkSqft: havePrintRate ? s.printSqFt ?? 0 : 0,
          quantity: havePrintRate ? qty : 1,
          unitRate: havePrintRate ? s.printRatePerSqft ?? 0 : s.printSell ?? 0,
        });
      }
      setPendingPoolExtraLines(extras);
    } else {
      setDraft((d) => ({
        ...d,
        isContractItem: false,
        productNo: "",
        productName: row.label,
        description: poolItemDescription(row),
        calcMode: "nos",
        sizeEntryMode: "dimensions",
        widthCm: 0,
        heightCm: 0,
        quantity: 1,
        unitRate: row.sell_amount ?? 0,
      }));
      setPendingPoolExtraLines([]);
    }
    setPendingPoolItemId(row.id);
  }

  function addLine() {
    if (!draft.productName.trim()) {
      toast("danger", "Enter or select a product first");
      return;
    }
    if (draft.calcMode === "sqft" && draft.sizeEntryMode === "dimensions" && (draft.widthCm <= 0 || draft.heightCm <= 0)) {
      toast("danger", "Enter width and height for an area-priced line");
      return;
    }
    if (draft.calcMode === "sqft" && draft.sizeEntryMode === "bulk" && draft.bulkSqft <= 0) {
      toast("danger", "Enter the total SQFT for this line");
      return;
    }
    const poolItemId = source === "pool" ? pendingPoolItemId ?? undefined : undefined;
    setLines((ls) => [
      ...ls,
      {
        ...draft,
        isContractItem: source === "contract",
        key: crypto.randomUUID(),
        poolItemId,
      },
      // Print/Shipping/Installation, precomputed by pickPoolRow -- appended
      // as their own separate line items right alongside the (editable)
      // primary line, all tagged with the same poolItemId so the pool item
      // still gets marked 'used' as one unit on save. Gated on
      // source === "pool" so switching away to another source without
      // clicking a new pool item never re-injects stale leftover extras.
      ...(source === "pool" ? pendingPoolExtraLines.map((l) => ({ ...l, isContractItem: false, key: crypto.randomUUID(), poolItemId })) : []),
    ]);
    setDraft(emptyDraft());
    setPendingPoolExtraLines([]);
    setRateCardPick("");
    setHistoryPick("");
    setPoolPick("");
    setPendingPoolItemId(null);
  }

  function removeLine(key: string) {
    setLines((ls) => ls.filter((l) => l.key !== key));
  }

  const subtotal = lines.reduce((s, l) => s + lineSubtotal(l), 0);
  const transportationTotal = lines.reduce((s, l) => s + l.transportationRate, 0);
  const installationTotal = lines.reduce((s, l) => s + l.installationRate, 0);
  const taxableTotal = subtotal + transportationTotal + installationTotal;
  const gstAmount = (taxableTotal * gstPercent) / 100;
  const grandTotal = taxableTotal + gstAmount;

  async function saveEstimate() {
    if (!selectedCustomer) {
      toast("danger", "Select a customer first");
      return;
    }
    if (!jobNumber.trim()) {
      toast("danger", "Enter a Campaign/Job#/Program — every estimate needs one so it can be searched later");
      return;
    }
    if (lines.length === 0) {
      toast("danger", "Add at least one line item");
      return;
    }
    setSaving(true);
    try {
      const { data: userData } = await supabase.auth.getUser();

      // Editing an existing estimate never updates that row -- it always
      // inserts the NEXT version, linked back via root_estimate_id, so
      // every version ever generated stays in the database untouched.
      let quoteNumberData: string;
      let version = 1;
      let rootEstimateId: string | null = null;
      if (editingEstimateId && editingRootId && editingBaseQuoteNumber) {
        const { data: latest, error: latestError } = await supabase
          .from("estimates")
          .select("version")
          .or(`id.eq.${editingRootId},root_estimate_id.eq.${editingRootId}`)
          .order("version", { ascending: false })
          .limit(1)
          .maybeSingle();
        if (latestError) throw latestError;
        version = (latest?.version ?? editingVersion) + 1;
        rootEstimateId = editingRootId;
        quoteNumberData = `${editingBaseQuoteNumber}-V${version}`;
      } else {
        const { data: generated, error: quoteNumberError } = await supabase.rpc("generate_quote_number", {
          p_customer_code: selectedCustomer.code,
        });
        if (quoteNumberError) throw quoteNumberError;
        quoteNumberData = generated;
      }

      const { data: estimate, error: estimateError } = await supabase
        .from("estimates")
        .insert({
          quote_number: quoteNumberData,
          job_number: jobNumber.trim(),
          version,
          root_estimate_id: rootEstimateId,
          customer_id: selectedCustomer.id,
          contract_id: effectiveContractId || null,
          gst_percent: gstPercent,
          subtotal,
          transportation_total: transportationTotal,
          installation_total: installationTotal,
          taxable_total: taxableTotal,
          gst_amount: gstAmount,
          grand_total: grandTotal,
          notes: notes || null,
          attention_person: attentionPerson || null,
          quote_subject: quoteSubject || null,
          customer_address: customerAddress || null,
          customer_gstin: customerGstin || null,
          job_completion_time: jobCompletionTime || null,
          delivery_commitment: deliveryCommitment || null,
          payment_terms_type: paymentTermsType,
          // Only 'net_days' ever carries a day count -- 'advance'/'against_delivery'
          // are fixed terms with nothing to count (see the migration's check
          // constraint invariant).
          payment_terms_days: paymentTermsType === "net_days" && paymentTermsDays !== "" ? paymentTermsDays : null,
          salesperson_name: salespersonName || null,
          salesperson_designation: salespersonDesignation || null,
          salesperson_phone: salespersonPhone || null,
          salesperson_email: salespersonEmail || null,
          created_by: userData.user?.id ?? null,
        })
        .select()
        .single();
      if (estimateError) throw estimateError;

      const { error: linesError } = await supabase.from("estimate_line_items").insert(
        lines.map((l, i) => ({
          estimate_id: estimate.id,
          sort_order: i,
          is_contract_item: l.isContractItem,
          rate_card_source: l.isContractItem ? (isApple ? "apple_rate_card" : "ikea_rate_card") : null,
          product_no: l.productNo || null,
          product_name: l.productName,
          design_name: l.designName || null,
          description: l.description || null,
          additional_description: l.additionalDescription || null,
          uom: l.uom || null,
          calc_mode: l.calcMode,
          width_cm: l.widthCm || null,
          height_cm: l.heightCm || null,
          width_in: l.widthCm ? widthIn(l) : null,
          height_in: l.heightCm ? heightIn(l) : null,
          sqft_total: l.calcMode === "sqft" ? sqftTotal(l) : null,
          unit_rate: l.unitRate,
          quantity: l.quantity,
          transportation_rate: l.transportationRate,
          installation_rate: l.installationRate,
          line_subtotal: lineSubtotal(l),
          line_total: lineTotal(l),
        }))
      );
      if (linesError) throw linesError;

      // Mark any pool items this estimate drew from as 'used' -- best
      // effort, isolated from the outer try/catch so a hiccup here (e.g. a
      // pool item already claimed by someone else in the meantime) never
      // makes the already-saved estimate look like it failed.
      const usedPoolItemIds = lines.map((l) => l.poolItemId).filter((id): id is string => !!id);
      if (usedPoolItemIds.length > 0) {
        const { error: poolUpdateError } = await supabase
          .from("estimate_pool_items")
          .update({ status: "used", used_in_estimate_id: estimate.id })
          .in("id", usedPoolItemIds);
        if (poolUpdateError) {
          toast("warning", `Estimate saved, but couldn't mark ${usedPoolItemIds.length} pool item(s) as used: ${poolUpdateError.message}`);
        } else {
          loadPoolItems();
        }
      }

      const blob = await generateEstimatePdf({
        quoteNumber: quoteNumberData,
        version,
        createdAt: estimate.created_at,
        customerName: selectedCustomer.name,
        siteLegalEntityName: null,
        jobNumber: jobNumber.trim() || null,
        customerAddress: customerAddress || null,
        customerGstin: customerGstin || null,
        attentionPerson: attentionPerson || null,
        quoteSubject: quoteSubject || null,
        gstPercent,
        jobCompletionTime: jobCompletionTime || null,
        deliveryCommitment: deliveryCommitment || null,
        paymentTermsType,
        paymentTermsDays: paymentTermsType === "net_days" && paymentTermsDays !== "" ? paymentTermsDays : null,
        notes: notes || null,
        salespersonName: salespersonName || null,
        salespersonDesignation: salespersonDesignation || null,
        salespersonPhone: salespersonPhone || null,
        salespersonEmail: salespersonEmail || null,
        lines: lines.map((l) => ({
          productNo: l.productNo || null,
          productName: l.productName,
          designName: l.designName || null,
          description: l.description || null,
          additionalDescription: l.additionalDescription || null,
          uom: l.uom || null,
          calcMode: l.calcMode,
          widthCm: l.widthCm || null,
          heightCm: l.heightCm || null,
          quantity: l.quantity,
          sqftTotal: l.calcMode === "sqft" ? sqftTotal(l) : null,
          unitRate: l.unitRate,
          transportationRate: l.transportationRate,
          installationRate: l.installationRate,
        })),
      });
      downloadBlob(blob, `${quoteNumberData}.pdf`);

      toast("success", `Saved ${quoteNumberData} — PDF downloaded`);
      setLines([]);
      setNotes("");
      setEditingEstimateId(null);
      setEditingRootId(null);
      setEditingBaseQuoteNumber(null);
      setEditingVersion(1);
      loadRecent();
    } catch (err) {
      const message = err instanceof Error ? err.message : "Couldn't save this estimate";
      toast("danger", message);
    } finally {
      setSaving(false);
    }
  }

  return (
    <ToolAccessGuard toolId="estimate-builder" toolLabel="Estimate Builder">
    <div>
      <Breadcrumbs items={[{ label: "Home", href: "/" }, { label: "Tools" }, { label: "Estimate Builder" }]} />

      <div className="mt-4 flex items-start justify-between gap-4 border-b border-line pb-6">
        <div className="flex items-start gap-4">
          <span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-primary-tint text-primary">
            <FileSpreadsheet size={22} />
          </span>
          <div>
            <h1 className="text-xl font-semibold text-ink">Estimate Builder</h1>
            <p className="mt-0.5 text-sm text-ink-secondary">
              Tools — build a customer estimate from their contract&rsquo;s real pricing, add anything not on the contract as an
              unlisted line, and get GST-ready totals
            </p>
          </div>
        </div>
        <Button variant="secondary" size="sm" onClick={startNewEstimate} className="shrink-0">
          <Plus size={16} />
          New Estimate
        </Button>
      </div>

      {editingEstimateId && (
        <div className="mt-4 flex items-center justify-between gap-3 rounded-lg border border-warning/30 bg-warning-tint px-4 py-3 text-sm text-warning">
          <span className="flex items-center gap-2">
            <Pencil size={15} />
            Editing {editingBaseQuoteNumber} — saving will create <strong>Version {editingVersion + 1}</strong> as a new row; nothing gets overwritten.
          </span>
          <Button variant="ghost" size="sm" onClick={cancelEdit}>
            <X size={14} />
            Cancel edit
          </Button>
        </div>
      )}

      {/* Customer / contract */}
      <Card interactive={false} className="my-6 flex flex-col gap-4 sm:flex-row sm:flex-wrap sm:items-end">
        <Dropdown
          label="Customer"
          placeholder={customers === null ? "Loading…" : "Select a customer"}
          options={(customers ?? []).map((c) => ({ value: c.id, label: c.name }))}
          value={selectedCustomerId}
          onChange={(v) => onCustomerChange(v as string)}
        />
        <Dropdown
          label="Contract"
          placeholder={!selectedCustomer ? "Select a customer first" : matchingContracts.length === 0 ? "No matching contract found" : "Select a contract"}
          options={matchingContracts.map((c) => ({ value: c.id, label: `${c.type ?? "Contract"} — ${c.value ?? ""}` }))}
          value={effectiveContractId}
          onChange={(v) => setSelectedContractId(v as string)}
        />
      </Card>

      {/* Quote header — matches the "To, / Attn / SUB / Quote No." block on
          the real sample quotes. Job No. is user-typed and permanent —
          the primary way estimates get searched later (see the
          Quotations page). Address/GST/attention person auto-fill from
          the customer's own record the moment it's picked, and stay
          editable so they're never silently blank. */}
      <Card interactive={false} className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Campaign/Job#/Program <span className="text-danger">*</span>
          <input
            value={jobNumber}
            onChange={(e) => setJobNumber(e.target.value)}
            placeholder="e.g. JOB-2026-0143"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary sm:col-span-2">
          Customer address (for the &ldquo;To,&rdquo; block)
          <input
            value={customerAddress}
            onChange={(e) => setCustomerAddress(e.target.value)}
            placeholder="Registered/billing address"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary sm:col-span-2">
          Customer GSTIN
          <input
            value={customerGstin}
            onChange={(e) => setCustomerGstin(e.target.value)}
            placeholder="e.g. 07AADCI3006N1ZM"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Attention person
          {customerContacts && customerContacts.length > 0 && (
            <select
              value=""
              onChange={(e) => {
                const c = customerContacts.find((x) => x.id === e.target.value);
                if (c) setAttentionPerson(c.name);
              }}
              className="h-8 rounded-md border border-line-strong bg-surface px-2 text-xs text-ink outline-none"
            >
              <option value="">Pick from contacts on file ({customerContacts.length})…</option>
              {customerContacts.map((c) => (
                <option key={c.id} value={c.id}>
                  {c.name}
                  {c.role ? ` — ${c.role}` : ""}
                </option>
              ))}
            </select>
          )}
          <input
            value={attentionPerson}
            onChange={(e) => setAttentionPerson(e.target.value)}
            placeholder="e.g. Ms. Riya Patil"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary sm:col-span-1 lg:col-span-3">
          Quote subject
          <input
            value={quoteSubject}
            onChange={(e) => setQuoteSubject(e.target.value)}
            placeholder="e.g. SUB: Quote for — Digital UV Printing"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
      </Card>

      {/* Add a line */}
      <Card interactive={false} className="mb-6 flex flex-col gap-4">
        <div className="flex items-center gap-1 border-b border-line pb-3">
          <button
            type="button"
            onClick={() => setSource("contract")}
            className={`rounded-md px-3 py-1.5 text-xs font-medium ${source === "contract" ? "bg-primary-tint text-primary" : "text-ink-secondary hover:bg-surface-sunken"}`}
          >
            From contract catalog
          </button>
          <button
            type="button"
            onClick={() => {
              setSource("history");
              setDraft((d) => ({ ...d, isContractItem: false }));
            }}
            className={`rounded-md px-3 py-1.5 text-xs font-medium ${source === "history" ? "bg-success-tint text-success" : "text-ink-secondary hover:bg-surface-sunken"}`}
          >
            From recent purchases
          </button>
          <button
            type="button"
            onClick={() => {
              setSource("custom");
              setDraft((d) => ({ ...d, isContractItem: false }));
            }}
            className={`rounded-md px-3 py-1.5 text-xs font-medium ${source === "custom" ? "bg-warning-tint text-warning" : "text-ink-secondary hover:bg-surface-sunken"}`}
          >
            Non-contract / unlisted product
          </button>
          <button
            type="button"
            onClick={() => {
              setSource("pool");
              setDraft((d) => ({ ...d, isContractItem: false }));
            }}
            className={`rounded-md px-3 py-1.5 text-xs font-medium ${source === "pool" ? "bg-primary-tint text-primary" : "text-ink-secondary hover:bg-surface-sunken"}`}
          >
            From estimate pool{poolItems && poolItems.length > 0 ? ` (${poolItems.length})` : ""}
          </button>
        </div>

        {source === "pool" && (
          <>
            {poolItems === null ? (
              <p className="text-sm text-ink-muted">Loading the estimate pool…</p>
            ) : poolItems.length === 0 ? (
              <p className="text-sm text-ink-muted">
                Nothing waiting in the pool yet — save a job from Sign Estimator or Cost Sheet with &ldquo;Add to Estimate
                Pool&rdquo; and it&apos;ll show up here.
              </p>
            ) : (
              <Dropdown
                label={`Waiting in the pool (${poolItems.length})`}
                placeholder="Search Sign Estimator / Cost Sheet jobs saved to the pool"
                options={poolItems.map((item, i) => ({
                  value: String(i),
                  label: `${item.source === "cost_sheet" ? "Cost Sheet" : "Sign Estimator"} — ${item.label}${item.sell_amount != null ? ` — ${rupee(item.sell_amount)}` : ""}`,
                }))}
                value={poolPick}
                onChange={(v) => pickPoolRow(v as string)}
              />
            )}
          </>
        )}

        {source === "history" && (
          <>
            {!selectedCustomerId ? (
              <p className="text-sm text-ink-muted">Select a customer to see what&apos;s been sold to them before.</p>
            ) : salesHistory === null ? (
              <p className="text-sm text-ink-muted">Loading past sales…</p>
            ) : salesHistory.length === 0 ? (
              <p className="text-sm text-ink-muted">No past sales on file for this customer yet — use “Non-contract / unlisted product” instead.</p>
            ) : (
              <Dropdown
                label={`Previously sold to ${selectedCustomer?.name ?? "this customer"} (${salesHistory.length} distinct products)`}
                placeholder="Search products they've bought before"
                options={salesHistory.map((r, i) => ({
                  value: String(i),
                  label: `${r.itemCode ? `${r.itemCode} — ` : ""}${r.itemDescription ?? "Unknown item"} — ${r.latestRate != null ? rupee(r.latestRate) : "rate n/a"}${r.latestDate ? ` (last bought ${r.latestDate})` : ""}${r.timesPurchased > 1 ? `, bought ${r.timesPurchased}×` : ""}`,
                }))}
                value={historyPick}
                onChange={(v) => pickHistoryRow(v as string)}
              />
            )}
          </>
        )}

        {source === "contract" && (
          <>
            {isIkea ? (
              <Dropdown
                label="Product (IKEA rate card)"
                placeholder={rateCard === null ? "Loading…" : "Search products"}
                options={(rateCard ?? []).map((r, i) => ({
                  value: String(i),
                  label: `${r.product} — ${rupee(r.revised_rate)}/${r.uom ?? "unit"} (${r.scope ?? "—"})`,
                }))}
                value={rateCardPick}
                onChange={(v) => pickIkeaRateCardRow(v as string)}
              />
            ) : isApple ? (
              <Dropdown
                label="Product (Apple rate card)"
                placeholder={appleRateCard === null ? "Loading…" : "Search SKUs"}
                options={(appleRateCard ?? []).map((r, i) => ({
                  value: String(i),
                  label: `${r.sku_id} — ${r.sku_description ?? ""} — ${rupee(r.rate_inr_each ?? r.bill_rate)}/${r.unit ?? "unit"}`,
                }))}
                value={rateCardPick}
                onChange={(v) => pickAppleRateCardRow(v as string)}
              />
            ) : (
              <p className="text-sm text-ink-muted">
                {selectedCustomerId ? "No rate card is wired up for this customer yet — use “Non-contract / unlisted product” for now." : "Select a customer to search their contract catalog."}
              </p>
            )}
          </>
        )}

        {(source === "custom" || draft.productName) && (
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {(source === "custom" || source === "history") && (
              <>
                <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                  Product name
                  <input
                    value={draft.productName}
                    onChange={(e) => setDraft((d) => ({ ...d, productName: e.target.value }))}
                    className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                  />
                </label>
                <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                  Description
                  <input
                    value={draft.description}
                    onChange={(e) => setDraft((d) => ({ ...d, description: e.target.value }))}
                    className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                  />
                </label>
              </>
            )}

            {/* Product No. — the contract's own item/serial number for
                this line (auto-filled from the picked rate-card row, but
                always editable to match the real contract paperwork). */}
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Product No.
              <input
                value={draft.productNo}
                onChange={(e) => setDraft((d) => ({ ...d, productNo: e.target.value }))}
                placeholder="Contract's item/serial no."
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>

            {/* Design, Pricing basis, UOM, Width/Height, Qty — UOM sits
                right before Width/Height because, for SQFT-priced lines,
                it IS the unit selector for them: pick "Feet" and Width/
                Height are read directly in feet, pick "CM" (the default)
                and they're read in centimeters -- no separate hand
                conversion needed either way. For Nos-priced lines, UOM
                goes back to being a free-text label for whatever's being
                counted (e.g. "Boxes"), since there's no Width/Height to
                interpret there. Either way it's the same underlying uom
                field/DB column, so it round-trips through edit/PDF
                regeneration without a schema change. */}
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Design
              <input
                value={draft.designName}
                onChange={(e) => setDraft((d) => ({ ...d, designName: e.target.value }))}
                placeholder="Campaign / creative name"
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Pricing basis
              <select
                value={draft.calcMode}
                onChange={(e) => {
                  const mode = e.target.value as EstimateCalcMode;
                  setDraft((d) => {
                    if (mode === d.calcMode) return d;
                    // Switching Pricing basis used to leave `unitRate`
                    // untouched, so a Nos rate meant as "total cost for this
                    // line" (e.g. ₹25,440 for qty 1) got silently
                    // reinterpreted as a ₹/sq.ft rate the moment SQFT was
                    // selected -- multiplying by the sign's real area and
                    // massively inflating the Amount (₹25,440 × 32 sq.ft =
                    // ₹8,14,080 instead of the intended ₹25,440). Back-solve
                    // a fresh unitRate from the CURRENT total instead, so
                    // toggling the basis keeps the line's Amount the same
                    // right up until the user actually changes something --
                    // it only re-expresses the same total as a different
                    // rate, it never re-derives a new total from the old
                    // rate under the new formula.
                    const currentTotal = lineSubtotal(d);
                    let unitRate = d.unitRate;
                    if (mode === "sqft") {
                      const sqft = sqftTotal({ ...d, calcMode: "sqft" });
                      if (sqft > 0) unitRate = Math.round((currentTotal / sqft) * 100) / 100;
                    } else {
                      if (d.quantity > 0) unitRate = Math.round((currentTotal / d.quantity) * 100) / 100;
                    }
                    return {
                      ...d,
                      calcMode: mode,
                      unitRate,
                      // Switching to SQFT always normalizes uom to a valid
                      // cm/ft/in selection (defaulting to cm) so the dropdown
                      // below has a real value to show; switching to Nos
                      // clears a leftover cm/ft/in value so there's a blank
                      // field ready for a real counting-unit label instead.
                      uom: mode === "sqft" ? getSizeUnit(d.uom) : ["cm", "ft", "in"].includes(d.uom.toLowerCase()) ? "" : d.uom,
                    };
                  });
                }}
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              >
                <option value="sqft">SQFT (width × height × qty)</option>
                <option value="nos">Nos (qty only)</option>
              </select>
            </label>
            {/* Shown for every source, including a contract-catalog pick --
                a rate card's own uom text (e.g. IKEA's "SQFT") still just
                means "cm entry" here (getSizeUnit treats anything with
                "sq" in it as cm), so this is a safe, non-breaking default
                for contract lines too, with Feet/Inches available as an
                override. */}
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              UOM
              {draft.calcMode === "sqft" ? (
                <select
                  value={getSizeUnit(draft.uom)}
                  onChange={(e) => setDraft((d) => ({ ...d, uom: e.target.value }))}
                  className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                >
                  <option value="cm">CM — enter Width/Height in centimeters</option>
                  <option value="ft">Feet — enter Width/Height in feet</option>
                  <option value="in">Inches — enter Width/Height in inches</option>
                </select>
              ) : (
                <input
                  value={draft.uom}
                  onChange={(e) => setDraft((d) => ({ ...d, uom: e.target.value }))}
                  placeholder="e.g. Boxes, Rolls, Each"
                  className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                />
              )}
            </label>
            {draft.calcMode === "sqft" && (
              <>
                <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                  Size entry
                  <select
                    value={draft.sizeEntryMode}
                    onChange={(e) => setDraft((d) => ({ ...d, sizeEntryMode: e.target.value as SizeEntryMode }))}
                    className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                  >
                    <option value="dimensions">Width × Height</option>
                    <option value="bulk">Total SQFT (no width/height)</option>
                  </select>
                </label>
                {draft.sizeEntryMode === "dimensions" ? (
                  <>
                    <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                      Width ({getSizeUnit(draft.uom)})
                      <input
                        type="number"
                        value={draft.widthCm || ""}
                        onChange={(e) => setDraft((d) => ({ ...d, widthCm: Number(e.target.value) }))}
                        className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                      />
                    </label>
                    <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                      Height ({getSizeUnit(draft.uom)})
                      <input
                        type="number"
                        value={draft.heightCm || ""}
                        onChange={(e) => setDraft((d) => ({ ...d, heightCm: Number(e.target.value) }))}
                        className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                      />
                    </label>
                  </>
                ) : (
                  // Bulk entry: no width/height to multiply -- just the
                  // total SQFT for one unit of Quantity below (e.g. 500
                  // sqft x Quantity 2 rooms = 1000 sqft total), for
                  // quoting a lump area rather than a specific panel size.
                  <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                    Total SQFT (per qty)
                    <input
                      type="number"
                      value={draft.bulkSqft || ""}
                      onChange={(e) => setDraft((d) => ({ ...d, bulkSqft: Number(e.target.value) }))}
                      placeholder="e.g. 500"
                      className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                    />
                  </label>
                )}
              </>
            )}
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Quantity
              <input
                type="number"
                min={0}
                value={draft.quantity}
                onChange={(e) => setDraft((d) => ({ ...d, quantity: Number(e.target.value) }))}
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            {draft.calcMode === "sqft" && draft.sizeEntryMode === "dimensions" && draft.widthCm > 0 && draft.heightCm > 0 && (
              <div className="flex flex-col justify-end rounded-md bg-surface-sunken px-3 py-2 text-xs text-ink-secondary">
                {widthIn(draft).toFixed(2)}in × {heightIn(draft).toFixed(2)}in — total {sqftTotal(draft).toFixed(2)} sqft
              </div>
            )}
            {draft.calcMode === "sqft" && draft.sizeEntryMode === "bulk" && draft.bulkSqft > 0 && (
              <div className="flex flex-col justify-end rounded-md bg-surface-sunken px-3 py-2 text-xs text-ink-secondary">
                {draft.bulkSqft} sqft × qty {draft.quantity} — total {sqftTotal(draft).toFixed(2)} sqft
              </div>
            )}

            {(source === "custom" || source === "history") && (
              <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
                Unit rate (₹){source === "history" && <span className="ml-1 font-normal normal-case text-ink-muted">— last price charged; adjust as needed</span>}
                <input
                  type="number"
                  value={draft.unitRate}
                  onChange={(e) => setDraft((d) => ({ ...d, unitRate: Number(e.target.value) }))}
                  className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
                />
              </label>
            )}
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Additional description
              <input
                value={draft.additionalDescription}
                onChange={(e) => setDraft((d) => ({ ...d, additionalDescription: e.target.value }))}
                placeholder="Optional — finish, site notes…"
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Transportation (₹, this line)
              <input
                type="number"
                value={draft.transportationRate}
                onChange={(e) => setDraft((d) => ({ ...d, transportationRate: Number(e.target.value) }))}
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
              Installation (₹, this line)
              <input
                type="number"
                value={draft.installationRate}
                onChange={(e) => setDraft((d) => ({ ...d, installationRate: Number(e.target.value) }))}
                className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
              />
            </label>
            <div className="flex items-end">
              <Button variant="secondary" size="md" onClick={addLine}>
                <Plus size={16} />
                Add line
              </Button>
            </div>
          </div>
        )}
      </Card>

      {/* Line items */}
      <Card interactive={false} padding="sm" className="mb-6">
        <div className="overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="text-xs font-semibold uppercase tracking-wide text-ink-secondary">
              <tr>
                <th className="px-3 py-2">Product No.</th>
                <th className="px-3 py-2">Product / Design</th>
                <th className="px-3 py-2">Width × Height</th>
                <th className="px-3 py-2">Qty</th>
                <th className="px-3 py-2">SQFT</th>
                <th className="px-3 py-2">Rate</th>
                <th className="px-3 py-2">Amount</th>
                <th className="px-3 py-2">Shipping</th>
                <th className="px-3 py-2">Installation</th>
                <th className="px-3 py-2">Tax</th>
                <th className="px-3 py-2">Line grand total</th>
                <th className="px-3 py-2" />
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {lines.map((l) => {
                const base = lineSubtotal(l);
                const amount = base + l.transportationRate + l.installationRate;
                const tax = (amount * gstPercent) / 100;
                const sizeUnit = getSizeUnit(l.uom);
                return (
                  <tr key={l.key}>
                    <td className="px-3 py-2.5 text-ink-secondary">{l.productNo || "—"}</td>
                    <td className="px-3 py-2.5">
                      <div className="flex items-center gap-2">
                        <Badge status={l.isContractItem ? "info" : "warning"}>{l.isContractItem ? "Contract" : "Unlisted"}</Badge>
                        <div>
                          <p className="font-medium text-ink">{l.productName}</p>
                          {(l.designName || l.description || l.additionalDescription) && (
                            <p className="text-xs text-ink-muted">{[l.designName, l.description, l.additionalDescription].filter(Boolean).join(" — ")}</p>
                          )}
                        </div>
                      </div>
                    </td>
                    <td className="px-3 py-2.5">
                      {/* Width×Height shows whenever the line actually has
                          dimensions, regardless of pricing basis -- a "nos"
                          line (e.g. a Sign Estimator pool pull priced as a
                          flat lumpsum) still carries a real sign size and
                          the customer should still see it, not just SQFT-
                          priced lines. */}
                      {l.calcMode === "sqft" && l.sizeEntryMode === "bulk"
                        ? `${l.bulkSqft} sqft (bulk)`
                        : l.widthCm && l.heightCm
                        ? `${l.widthCm}${sizeUnit} × ${l.heightCm}${sizeUnit}`
                        : "—"}
                    </td>
                    <td className="px-3 py-2.5">
                      {/* UOM is repurposed as the cm/ft/in size-entry unit
                          for Width×Height on ANY line that carries real
                          dimensions -- including "nos" lines pulled from the
                          Sign Estimator pool, which still show a real sign
                          size even though they're not priced by area (see
                          the Width×Height cell above). That's not a real
                          per-piece counting unit, so it's excluded here too
                          (was showing e.g. "1 ft" instead of just "1").
                          Only genuine "nos" lines with a real counting unit
                          (Boxes, Rolls, Each, ...) show it appended. */}
                      {l.calcMode === "sqft" || ["cm", "ft", "in"].includes(l.uom.toLowerCase())
                        ? l.quantity
                        : `${l.quantity} ${l.uom}`.trim()}
                    </td>
                    <td className="px-3 py-2.5">{l.calcMode === "sqft" ? sqftTotal(l).toFixed(2) : "—"}</td>
                    <td className="px-3 py-2.5">{rupee(l.unitRate)}</td>
                    <td className="px-3 py-2.5">{rupee(base)}</td>
                    <td className="px-3 py-2.5">{l.transportationRate ? rupee(l.transportationRate) : "—"}</td>
                    <td className="px-3 py-2.5">{l.installationRate ? rupee(l.installationRate) : "—"}</td>
                    <td className="px-3 py-2.5">{rupee(tax)}</td>
                    <td className="px-3 py-2.5 font-medium text-ink">{rupee(amount + tax)}</td>
                    <td className="px-3 py-2.5">
                      <Button variant="icon" size="sm" aria-label="Remove line" onClick={() => removeLine(l.key)}>
                        <Trash2 size={14} />
                      </Button>
                    </td>
                  </tr>
                );
              })}
              {lines.length === 0 && (
                <tr>
                  <td colSpan={12} className="px-3 py-8 text-center text-ink-muted">
                    No line items yet — add one above.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>

      {/* Totals */}
      <div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3 lg:grid-cols-5">
        <StatCard label="Subtotal" value={rupee(subtotal)} />
        <StatCard label="Transportation" value={rupee(transportationTotal)} />
        <StatCard label="Installation" value={rupee(installationTotal)} />
        <div className="rounded-lg border border-line bg-surface p-4">
          <label className="mb-1 block text-xs font-medium uppercase tracking-wide text-ink-secondary">GST %</label>
          <input
            type="number"
            value={gstPercent}
            onChange={(e) => setGstPercent(Number(e.target.value))}
            className="h-9 w-full rounded-md border border-line-strong bg-surface px-2 text-lg font-bold text-ink outline-none"
          />
        </div>
        <StatCard label="Grand total" value={rupee(grandTotal)} />
      </div>

      {/* Job completion / delivery / payment terms — matches the sample
          quotes' closing sections. Left blank, the PDF prints the user's
          standard wording (DEFAULT_JOB_COMPLETION_TIME / DEFAULT_DELIVERY_
          COMMITMENT in pdf.ts) -- typing something here overrides it for
          this estimate only. */}
      <Card interactive={false} className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary sm:col-span-1 lg:col-span-2">
          Job completion time
          <input
            value={jobCompletionTime}
            onChange={(e) => setJobCompletionTime(e.target.value)}
            placeholder="Default: The overall job is expected to be completed according to the given Schedule."
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary sm:col-span-1 lg:col-span-2">
          Delivery commitment
          <input
            value={deliveryCommitment}
            onChange={(e) => setDeliveryCommitment(e.target.value)}
            placeholder="Default: Same day delivery within Hyderabad city, out station deliveries based on logistics…"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Payment terms
          {isIkea && paymentTermsType === "net_days" && <span className="font-normal normal-case text-ink-muted"> — defaults to 30 for IKEA</span>}
          {isApple && paymentTermsType === "net_days" && <span className="font-normal normal-case text-ink-muted"> — defaults to 45 for Apple</span>}
          <select
            value={paymentTermsType}
            onChange={(e) => setPaymentTermsType(e.target.value as EstimatePaymentTermsType)}
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          >
            <option value="net_days">Net terms (days from date of supply)</option>
            <option value="advance">Advance Payment</option>
            <option value="against_delivery">Against Delivery</option>
          </select>
          {paymentTermsType === "net_days" && (
            <input
              type="number"
              value={paymentTermsDays}
              onChange={(e) => setPaymentTermsDays(e.target.value === "" ? "" : Number(e.target.value))}
              placeholder="Number of days"
              className="mt-1 h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
            />
          )}
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Notes (optional)
          <input
            value={notes}
            onChange={(e) => setNotes(e.target.value)}
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
      </Card>

      {/* Sales person — prints in the PDF's sign-off block ("For MACROMEDIA
          DIGITAL IMAGING PVT. LTD." followed by whoever's picked here). No
          default person: every estimate starts blank, same "pick from a
          list, then freely edit" pattern as Attention person above. */}
      <Card interactive={false} className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
        <div className="flex flex-col gap-1 sm:col-span-2 lg:col-span-4">
          {employees && employees.length > 0 ? (
            // Searchable instead of a plain <select> -- with ~500 employees
            // on file, scrolling a native dropdown to find one by eye was
            // impractical. Same Dropdown component already used to search
            // the rate card / sales history product lists above.
            <Dropdown
              label="Sales person (for the sign-off block)"
              placeholder={`Search ${employees.length} employees by name, code, or designation…`}
              options={employees.map((p) => ({
                value: p.id,
                label: `${p.name}${p.role ? ` — ${p.role}` : ""}${p.employee_code ? ` · ${p.employee_code}` : ""}`,
              }))}
              value={salespersonPick}
              onChange={(v) => {
                const id = v as string;
                setSalespersonPick(id);
                const p = employees.find((x) => x.id === id);
                if (!p) return;
                setSalespersonName(p.name);
                setSalespersonDesignation(p.role ?? "");
                setSalespersonPhone(p.off_phone || p.personal_phone || "");
                setSalespersonEmail(p.off_email || p.personal_email || "");
              }}
            />
          ) : (
            <span className="text-xs font-medium text-ink-secondary">Sales person (for the sign-off block)</span>
          )}
        </div>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Name
          <input
            value={salespersonName}
            onChange={(e) => setSalespersonName(e.target.value)}
            placeholder="e.g. Priya Sharma"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Designation
          <input
            value={salespersonDesignation}
            onChange={(e) => setSalespersonDesignation(e.target.value)}
            placeholder="e.g. Sales Manager"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Mobile number
          <input
            value={salespersonPhone}
            onChange={(e) => setSalespersonPhone(e.target.value)}
            placeholder="e.g. +91 90000 00000"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
        <label className="flex flex-col gap-1 text-xs font-medium text-ink-secondary">
          Email ID
          <input
            value={salespersonEmail}
            onChange={(e) => setSalespersonEmail(e.target.value)}
            placeholder="e.g. priya@mmdi.in"
            className="h-10 rounded-md border border-line-strong bg-surface px-3 text-sm text-ink outline-none"
          />
        </label>
      </Card>

      <div className="mb-8 flex justify-end">
        <Button variant="primary" size="lg" loading={saving} onClick={saveEstimate}>
          {editingEstimateId ? `Save as Version ${editingVersion + 1}` : "Save estimate"}
        </Button>
      </div>

      {/* Recent estimates */}
      <h3 className="mb-3 text-xs font-semibold uppercase tracking-wide text-ink-muted">Recent estimates</h3>
      <Card interactive={false} padding="sm">
        <div className="overflow-auto">
          <table className="w-full text-left text-sm">
            <thead className="text-xs font-semibold uppercase tracking-wide text-ink-secondary">
              <tr>
                <th className="px-3 py-2">Quote #</th>
                <th className="px-3 py-2">Campaign/Job#/Program</th>
                <th className="px-3 py-2">Version</th>
                <th className="px-3 py-2">Customer</th>
                <th className="px-3 py-2">Status</th>
                <th className="px-3 py-2">Grand total</th>
                <th className="px-3 py-2" />
              </tr>
            </thead>
            <tbody className="divide-y divide-line">
              {(recent ?? []).map((e) => (
                <tr key={e.id}>
                  <td className="px-3 py-2.5 font-medium text-ink">{e.quote_number}</td>
                  <td className="px-3 py-2.5">{e.job_number ?? "—"}</td>
                  <td className="px-3 py-2.5">
                    <Badge status={e.version > 1 ? "info" : "neutral"}>{`V${e.version}`}</Badge>
                  </td>
                  <td className="px-3 py-2.5">{e.customers?.name ?? "—"}</td>
                  <td className="px-3 py-2.5">
                    <Badge status="neutral">{e.status}</Badge>
                  </td>
                  <td className="px-3 py-2.5">{rupee(e.grand_total)}</td>
                  <td className="px-3 py-2.5">
                    <div className="flex items-center gap-2">
                      <Button variant="secondary" size="sm" onClick={() => loadEstimateForEdit(e)}>
                        <Pencil size={14} />
                        Edit
                      </Button>
                      <Button variant="secondary" size="sm" loading={downloadingId === e.id} onClick={() => downloadRecentPdf(e)}>
                        <Download size={14} />
                        PDF
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
              {recent !== null && recent.length === 0 && (
                <tr>
                  <td colSpan={8} className="px-3 py-8 text-center text-ink-muted">
                    No estimates saved yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
    </ToolAccessGuard>
  );
}
