// All PDF parsing/rendering (pdfjs-dist) and PDF generation (pdf-lib)
// happens here, and entirely client-side — a File object never leaves the
// browser. Nothing in this module makes a network request.
"use client";

import * as pdfjsLib from "pdfjs-dist";
import {
  PDFDocument,
  type PDFPage,
  type Color,
  degrees,
  rgb,
  pushGraphicsState,
  popGraphicsState,
  moveTo,
  lineTo,
  closePath,
  stroke,
  fill,
  setLineWidth,
  setLineJoin,
  LineJoinStyle,
  setStrokingColor,
  setFillingColor,
  setDashPattern,
} from "pdf-lib";
import { mmToPt, ptToMm, rotatePolygon, type Point, type DotSpec } from "./geometry";
import type { NestPlacement } from "./nesting";

export interface RgbColor {
  r: number;
  g: number;
  b: number;
}

/**
 * Draws a closed polygon as a thin stroked vector line — the actual cut
 * path a machine like a Zund table follows, as opposed to the rasterized
 * artwork underneath it. Uses pdf-lib's raw content-stream operators
 * (rather than drawSvgPath, which expects SVG's y-down convention and
 * would need every point flipped) so the incoming points can be handed
 * over directly in the same y-up mm space used everywhere else in this
 * tool. Bright magenta by default — a common stand-in for a dedicated
 * "CutContour" spot color, which pdf-lib can't create directly.
 */
function drawCutPath(page: PDFPage, outlineMm: Point[], color = rgb(1, 0, 1), lineWidthMm = 0.25) {
  if (outlineMm.length < 2) return;
  page.pushOperators(
    pushGraphicsState(),
    setStrokingColor(color),
    setLineWidth(mmToPt(lineWidthMm)),
    setDashPattern([], 0),
    moveTo(mmToPt(outlineMm[0].x), mmToPt(outlineMm[0].y)),
    ...outlineMm.slice(1).map((p) => lineTo(mmToPt(p.x), mmToPt(p.y))),
    closePath(),
    stroke(),
    popGraphicsState()
  );
}

/**
 * Draws a thick colored stroke straddling the cut path, matching the
 * traced shape's own sampled fill color — a "choke/trap" so that if the
 * physical cutter wanders a fraction of a mm off the vector line, what's
 * exposed at the edge is still that same color, not a sliver of the
 * background or bare substrate. Drawn AFTER the embedded design page (so
 * it paints over a thin band straddling the edge) and BEFORE the dots (so
 * the registration marks stay crisp on top). Round joins approximate a
 * true polygon offset well enough at this scale — a full geometric
 * offset isn't attempted here.
 */
function drawColorBleedStroke(page: PDFPage, outlineMm: Point[], color: Color, bleedMm: number) {
  if (outlineMm.length < 2 || bleedMm <= 0) return;
  page.pushOperators(
    pushGraphicsState(),
    setStrokingColor(color),
    setLineWidth(mmToPt(bleedMm * 2)),
    setLineJoin(LineJoinStyle.Round),
    setDashPattern([], 0),
    moveTo(mmToPt(outlineMm[0].x), mmToPt(outlineMm[0].y)),
    ...outlineMm.slice(1).map((p) => lineTo(mmToPt(p.x), mmToPt(p.y))),
    closePath(),
    stroke(),
    popGraphicsState()
  );
}

/**
 * Fills a closed polygon solid — used to lay down a color underneath the
 * printed artwork when a piece's bleed is being GENERATED by the tool
 * rather than already existing in the uploaded file (e.g. a keder-stitch
 * allowance of 12-14mm beyond the print size). The embedded PDF page is
 * drawn on top of this afterward, so the fill only shows through in the
 * surrounding band the file itself doesn't cover.
 */
function drawFilledPolygon(page: PDFPage, pointsMm: Point[], color: Color) {
  if (pointsMm.length < 3) return;
  page.pushOperators(
    pushGraphicsState(),
    setFillingColor(color),
    moveTo(mmToPt(pointsMm[0].x), mmToPt(pointsMm[0].y)),
    ...pointsMm.slice(1).map((p) => lineTo(mmToPt(p.x), mmToPt(p.y))),
    closePath(),
    fill(),
    popGraphicsState()
  );
}

/** Axis-aligned rectangle, canvas-local mm, representing the full "effective content" (trim + generated bleed) area to fill before the embedded PDF page is drawn on top. */
export interface AddedBleedRect {
  x: number;
  y: number;
  width: number;
  height: number;
  colorRgb: RgbColor;
}

/**
 * Draws one cut-registration dot: a white halo (so the mark stays visible
 * to the operator when the material is flipped for cutting from the
 * reverse side on a Zund table) with the black dot on top. Order matters —
 * PDF content paints in the order it's issued, so the white circle is
 * drawn first and the black circle over it.
 */
function drawDot(page: PDFPage, xMm: number, yMm: number, dotDiameterMm: number, haloMm: number) {
  const xPt = mmToPt(xMm);
  const yPt = mmToPt(yMm);
  if (haloMm > 0) {
    page.drawCircle({ x: xPt, y: yPt, size: mmToPt(dotDiameterMm / 2 + haloMm), color: rgb(1, 1, 1) });
  }
  page.drawCircle({ x: xPt, y: yPt, size: mmToPt(dotDiameterMm / 2), color: rgb(0, 0, 0) });
}

let workerConfigured = false;
function ensureWorker() {
  if (workerConfigured) return;
  pdfjsLib.GlobalWorkerOptions.workerSrc = new URL("pdfjs-dist/build/pdf.worker.min.mjs", import.meta.url).toString();
  workerConfigured = true;
}

export interface LoadedPdf {
  bytes: ArrayBuffer;
  widthMm: number;
  heightMm: number;
  previewDataUrl: string;
  previewWidthPx: number;
  previewHeightPx: number;
}

/**
 * Loads a PDF file, reads its page size, and renders a capped-resolution
 * preview. The preview is intentionally low-res (longest side <= maxDimPx)
 * so a "very heavy" high-res source file (large embedded photos etc.)
 * doesn't stall the browser — only the final export touches full-resolution
 * content, and even then it re-embeds the original page rather than
 * re-rasterizing it, so nothing is lost.
 */
export async function loadPdf(file: File, maxDimPx = 1400): Promise<LoadedPdf> {
  ensureWorker();
  const bytes = await file.arrayBuffer();
  const doc = await pdfjsLib.getDocument({ data: bytes.slice(0) }).promise;
  const page = await doc.getPage(1);
  const [x0, y0, x1, y1] = page.view;
  const widthPt = x1 - x0;
  const heightPt = y1 - y0;
  const widthMm = ptToMm(widthPt);
  const heightMm = ptToMm(heightPt);

  const scale = Math.min(maxDimPx / widthPt, maxDimPx / heightPt, 1);
  const viewport = page.getViewport({ scale: Math.max(scale, 0.02) });
  const canvas = document.createElement("canvas");
  canvas.width = Math.round(viewport.width);
  canvas.height = Math.round(viewport.height);
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas 2D context unavailable");
  await page.render({ canvasContext: ctx, viewport, canvas }).promise;

  return {
    bytes,
    widthMm,
    heightMm,
    previewDataUrl: canvas.toDataURL("image/png"),
    previewWidthPx: canvas.width,
    previewHeightPx: canvas.height,
  };
}

/**
 * Builds the final bleed+dot-marks PDF for a single design: the original
 * page (trim + its own bleed, untouched) centered on a larger canvas, with
 * solid black circles stamped at each dot position.
 */
export async function buildDotPlacementPdf(opts: {
  originalBytes: ArrayBuffer;
  canvasWidthMm: number;
  canvasHeightMm: number;
  contentOffsetMm: number; // where the actual PDF page is drawn (already includes any generated-bleed offset)
  dots: DotSpec[];
  dotDiameterMm: number;
  dotHaloMm?: number; // white halo width around each black dot, default 2mm
  outline?: Point[]; // optional cut-contour, in the same canvas-local mm frame as `dots`
  bleedColorRgb?: RgbColor; // sampled fill color from auto-trace, for the color-bleed stroke below
  colorBleedMm?: number; // width of that stroke straddling the cut path
  addedBleedRect?: AddedBleedRect; // if the file's own bleed is being generated by the tool, fill this area before drawing the page
}): Promise<Blob> {
  const { originalBytes, canvasWidthMm, canvasHeightMm, contentOffsetMm, dots, dotDiameterMm, outline } = opts;
  const haloMm = opts.dotHaloMm ?? 2;

  const outDoc = await PDFDocument.create();
  const [embedded] = await outDoc.embedPdf(originalBytes, [0]);

  const page = outDoc.addPage([mmToPt(canvasWidthMm), mmToPt(canvasHeightMm)]);

  if (opts.addedBleedRect) {
    const r = opts.addedBleedRect;
    const corners: Point[] = [
      { x: r.x, y: r.y },
      { x: r.x + r.width, y: r.y },
      { x: r.x + r.width, y: r.y + r.height },
      { x: r.x, y: r.y + r.height },
    ];
    drawFilledPolygon(page, corners, rgb(r.colorRgb.r, r.colorRgb.g, r.colorRgb.b));
  }

  page.drawPage(embedded, {
    x: mmToPt(contentOffsetMm),
    y: mmToPt(contentOffsetMm),
  });

  if (outline && outline.length >= 3 && opts.bleedColorRgb && (opts.colorBleedMm ?? 0) > 0) {
    drawColorBleedStroke(page, outline, rgb(opts.bleedColorRgb.r, opts.bleedColorRgb.g, opts.bleedColorRgb.b), opts.colorBleedMm as number);
  }

  for (const dot of dots) {
    drawDot(page, dot.x, dot.y, dotDiameterMm, haloMm);
  }

  if (outline && outline.length >= 3) {
    drawCutPath(page, outline);
  }

  const bytes = await outDoc.save();
  return new Blob([bytes as unknown as BlobPart], { type: "application/pdf" });
}

export interface NestSourceFile {
  pieceId: string;
  bytes: ArrayBuffer;
  // The SAME local outline array that was passed into nestPieces() for this
  // piece (the un-rotated, un-translated cut-contour, in canvas-local mm —
  // i.e. the piece's own bottom-left-origin frame that also anchors
  // contentOffsetMm and dots below). Needed to recover exactly how nesting
  // rotated + translated this piece, so the design and dots can be placed
  // as one rigid body consistent with placement.outline, without having to
  // assume anything about nesting.ts's internal normalization math.
  outline: Point[];
  contentOffsetMm: Point; // where the original PDF page sits inside the canvas-local frame
  dots: DotSpec[]; // in the same canvas-local frame
  dotDiameterMm: number;
  dotHaloMm?: number;
  bleedColorRgb?: RgbColor; // sampled fill color from auto-trace, for the color-bleed stroke (print file only)
  colorBleedMm?: number;
  addedBleedRect?: AddedBleedRect; // canvas-local; filled before the embedded page when this piece's bleed is tool-generated rather than baked into the file
}

/**
 * Shared placement logic for both nested-sheet exports. "print" embeds each
 * piece's original full-resolution page content plus its printed dot marks
 * (no cut-path — that's not something a printer should lay ink for). "cut"
 * draws only the stroked cut-path plus the SAME dot marks, no raster
 * artwork — a small, vector-only file for the cutter. Both modes derive
 * every position from the exact same transform per placement, so the marks
 * (and, for print, the design itself) land in identical spots between the
 * two files — required for the printed sheet's registration dots to line
 * up with the cutter's vector file.
 */
async function buildNestedSheetPdfInternal(opts: {
  sheetWidthMm: number;
  sheetHeightMm: number;
  placements: NestPlacement[];
  sources: NestSourceFile[];
  mode: "print" | "cut";
  overallDots?: OverallDots | null;
}): Promise<Blob> {
  const { sheetWidthMm, sheetHeightMm, placements, sources, mode, overallDots } = opts;
  const outDoc = await PDFDocument.create();
  const page = outDoc.addPage([mmToPt(sheetWidthMm), mmToPt(sheetHeightMm)]);

  const embeddedByPiece = new Map<string, Awaited<ReturnType<typeof outDoc.embedPdf>>[number]>();
  if (mode === "print") {
    for (const src of sources) {
      const [embedded] = await outDoc.embedPdf(src.bytes, [0]);
      embeddedByPiece.set(src.pieceId, embedded);
    }
  }
  const sourceByPiece = new Map(sources.map((s) => [s.pieceId, s]));

  for (const placement of placements) {
    const src = sourceByPiece.get(placement.pieceId);
    if (!src || placement.outline.length === 0 || src.outline.length === 0) continue;

    // Recover the piece's actual rotate+translate transform empirically:
    // rotate the piece's own local outline by the placement's rotation and
    // compare its first vertex to the corresponding vertex nesting.ts (or a
    // manual drag/rotate in the UI) already placed on the sheet
    // (placement.outline). The difference is a constant translation for
    // this placement — apply that same rotate-then-translate to any other
    // local-frame point (the design's content offset, each dot center) to
    // keep everything rigidly attached, regardless of how the placement
    // got to its current position/rotation.
    const rot = placement.rotationDeg;
    const rotatedLocalOutline = rotatePolygon(src.outline, rot);
    const constX = placement.outline[0].x - rotatedLocalOutline[0].x;
    const constY = placement.outline[0].y - rotatedLocalOutline[0].y;
    const toSheet = (p: Point): Point => {
      const [r] = rotatePolygon([p], rot);
      return { x: r.x + constX, y: r.y + constY };
    };

    if (mode === "print") {
      if (src.addedBleedRect) {
        const r = src.addedBleedRect;
        const localCorners: Point[] = [
          { x: r.x, y: r.y },
          { x: r.x + r.width, y: r.y },
          { x: r.x + r.width, y: r.y + r.height },
          { x: r.x, y: r.y + r.height },
        ];
        drawFilledPolygon(page, localCorners.map(toSheet), rgb(r.colorRgb.r, r.colorRgb.g, r.colorRgb.b));
      }
      const embedded = embeddedByPiece.get(placement.pieceId);
      if (embedded) {
        const designPos = toSheet(src.contentOffsetMm);
        page.drawPage(embedded, {
          x: mmToPt(designPos.x),
          y: mmToPt(designPos.y),
          rotate: degrees(rot),
        });
      }
      if (src.bleedColorRgb && (src.colorBleedMm ?? 0) > 0) {
        drawColorBleedStroke(page, placement.outline, rgb(src.bleedColorRgb.r, src.bleedColorRgb.g, src.bleedColorRgb.b), src.colorBleedMm as number);
      }
    }

    // Marks: identical in both files by construction (same src.dots, same
    // toSheet transform, same drawDot call) so registration lines up.
    // Skipped entirely when overallDots is set — one ring around the whole
    // layout replaces a ring around every individual placement instead of
    // supplementing it.
    if (!overallDots) {
      for (const dot of src.dots) {
        const dp = toSheet({ x: dot.x, y: dot.y });
        drawDot(page, dp.x, dp.y, src.dotDiameterMm, src.dotHaloMm ?? 2);
      }
    }

    if (mode === "cut") {
      drawCutPath(page, placement.outline);
    }
  }

  // One ring of dots around the whole nested group, already in sheet-space
  // mm (computed from the placements' combined bounds) — drawn once, after
  // every placement's own artwork/cut-path, same as the per-piece dots this
  // replaces sat "on top" in the original per-piece loop.
  if (overallDots) {
    for (const dot of overallDots.dots) {
      drawDot(page, dot.x, dot.y, overallDots.dotDiameterMm, overallDots.dotHaloMm);
    }
  }

  const bytes = await outDoc.save();
  return new Blob([bytes as unknown as BlobPart], { type: "application/pdf" });
}

/** A single ring of registration dots around the WHOLE nested layout, in
 *  sheet-space mm already (no per-placement transform needed) — used in
 *  place of each piece drawing its own dots, when the operator wants one
 *  outer ring instead of a ring around every individual copy. */
export interface OverallDots {
  dots: DotSpec[];
  dotDiameterMm: number;
  dotHaloMm: number;
}

export interface BuildNestedPdfOpts {
  sheetWidthMm: number;
  sheetHeightMm: number;
  placements: NestPlacement[];
  sources: NestSourceFile[];
  // When set, draw ONE ring of dots around the whole layout instead of each
  // placement's own `src.dots` — see OverallDots above.
  overallDots?: OverallDots | null;
}

/** Print file: original full-resolution artwork + printed registration dots, no cut path. */
export async function buildNestedPrintPdf(opts: BuildNestedPdfOpts): Promise<Blob> {
  return buildNestedSheetPdfInternal({ ...opts, mode: "print" });
}

/** Cut file: only the vector cut-path + the same registration dots — no raster artwork, for the cutter. */
export async function buildNestedCutPdf(opts: BuildNestedPdfOpts): Promise<Blob> {
  return buildNestedSheetPdfInternal({ ...opts, mode: "cut" });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
