"use client";

import dynamic from "next/dynamic";
import { useRouter } from "next/navigation";
import { useToast } from "@/components/ui/Notifications";
import { useLfgUser } from "@/lib/LfgUserContext";
import { useLfgHost, lfgHref } from "@/lib/lfg-links";
import { supabase } from "@/lib/supabase";
import { LFG_STATUSES, type LfgStatus } from "@/lib/lfgStatus";
import type { LockedInstallationSite } from "@/components/installationReport/InstallationReportClient";

// Same ssr:false reasoning as the staff wrapper
// (workspaces/installation-report/page.tsx): this tool builds PDFs
// client-side (pdf-lib), which doesn't exist in the Node.js environment
// Next.js uses to prerender pages during `next build`. No
// ToolAccessGuard -- the real gate for /lfg/(app)/* is getLfgIdentity()
// in this app's own layout.tsx.
const InstallationReportClient = dynamic(() => import("@/components/installationReport/InstallationReportClient"), {
  ssr: false,
  loading: () => <p className="py-10 text-center text-sm text-ink-muted">Loading Installation Report…</p>,
});

// Bridges the standalone Installation Report Creator (which never
// persists anything on its own -- handleExport() just builds and
// downloads a PDF) into the LFG partner flow. On save:
//  1. Uploads the generated PDF as an lfg_site_documents row
//     (category="installation") via the already partner-aware
//     /api/lfg/sites/[siteId]/documents/upload-url route.
//  2. Upserts lfg_installations for this site, same shape as
//     InstallationTab.handleSave() in LfgSiteWorkspaceClient.tsx, always
//     installation_status: "completed" per the user's decision (the
//     report's own per-site "installationStatus" field is a report-level
//     free description with a different vocabulary -- see
//     InstallationReportClient.tsx's own comment on that distinction).
//  3. Advances site_status to "installation_completed" via the same
//     rank-guarded RPC pattern as LfgPartnerQuickStatusButtons.tsx.
export function LfgPartnerInstallationReportBridge({ site }: { site: LockedInstallationSite & { site_status: string } }) {
  const router = useRouter();
  const { toast } = useToast();
  const identity = useLfgUser();
  const onLfgHost = useLfgHost();

  async function onSavedForSite({ pdfBlob, storeName, installationDate }: { pdfBlob: Blob; storeName: string; installationDate: string }) {
    const uploadRes = await fetch(`/api/lfg/sites/${site.id}/documents/upload-url`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        category: "installation",
        file_name: `${storeName || "installation-report"}.pdf`,
        file_type: "application/pdf",
      }),
    });
    const uploadData = await uploadRes.json();
    if (!uploadRes.ok) {
      toast("danger", uploadData?.message || "Couldn't save the report file");
      return;
    }
    await fetch(uploadData.url, { method: "PUT", headers: { "Content-Type": "application/pdf" }, body: pdfBlob });
    const {
      data: { user },
    } = await supabase.auth.getUser();
    await supabase.from("lfg_site_documents").insert({
      site_id: site.id,
      category: "installation",
      file_name: `${storeName || "installation-report"}.pdf`,
      file_type: "application/pdf",
      relative_path: uploadData.relative_path,
      uploaded_by: user?.id ?? null,
      uploaded_by_role: "partner",
    });

    await supabase.from("lfg_installations").upsert(
      {
        site_id: site.id,
        installation_required: true,
        installation_date: installationDate || new Date().toISOString().slice(0, 10),
        installation_team: identity?.partnerName ?? null,
        installation_status: "completed",
        updated_at: new Date().toISOString(),
      },
      { onConflict: "site_id" }
    );

    const currentRank = LFG_STATUSES.indexOf(site.site_status as LfgStatus);
    const targetRank = LFG_STATUSES.indexOf("installation_completed");
    if (currentRank < targetRank) {
      await supabase.rpc("lfg_change_site_status", {
        p_site_id: site.id,
        p_new_status: "installation_completed",
        p_remarks: "Installation Report generated by partner",
      });
    }

    toast("success", "Installation report saved — site marked Installed");
    router.push(lfgHref(`/sites/${site.id}`, onLfgHost));
  }

  return <InstallationReportClient lockedSite={site} onSavedForSite={onSavedForSite} />;
}
